In [1]:
import os
import sys
import re
import numpy as np
import pandas as pd
import plotly.express as px
import scipy.stats as stats
from dash import html, dcc, Input, Output, Dash
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

sys.path.append(os.path.join(os.getcwd(), '..', '..'))
from baseVR.base_functionality import init_import_paths
init_import_paths() 

from CustomLogger import CustomLogger as Logger
from analytics_processing import analytics

from analytics_processing.sessions_from_nas_parsing import sessionlist_fullfnames_from_args, fullfnames2snames
from dashsrc.plot_components.plots import plot_TrackFiringRate
from dashsrc.plot_components.plots import plot_unit_fr_stability

In [2]:
Logger().init_logger(None, None, logging_level="DEBUG")
animal_ids = [6]
paradigm = [1100]
session_range = [1,33]
session_ids = None
normalize = True
smooth = False
excl_session_names = None  #['2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min', '2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min', '2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min']

session_dirs = sessionlist_fullfnames_from_args(paradigm, animal_ids, session_ids, excl_session_names=excl_session_names)[0]
session_names= fullfnames2snames(session_dirs)

2026-02-03 12:21:37,223|DEBUG|86282|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Searching NAS for applicable sessions...
2026-02-03 12:21:38,947|DEBUG|86282|sessions_from_nas_parsing|get_sessionlist_fullfnames
	For paradigms [1100], animals [6], found 34 sessions.
2026-02-03 12:21:39,050|DEBUG|86282|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: [1100], animal_ids: [6], session_ids: None, from_date: None, to_date: None
	Merging 34 sessions

In [3]:
# firing rates and behavior data
fr = analytics.get_analytics('FiringRate40msHz', session_names=session_names)
fr_track = analytics.get_analytics('FiringRateTrackwiseHz', session_names=session_names)
fr_z_scored  = analytics.get_analytics('FiringRate40msZ', session_names=session_names)
fr_z_all_sess = fr.apply(lambda unit_fr: ((unit_fr - unit_fr.mean()) / unit_fr.std()))
behav = analytics.get_analytics('BehaviorTrackwise', session_names=session_names)
behav.index = behav.index.droplevel(('animal_id', 'paradigm_id', 'entry_id'))

2026-02-03 12:21:39,196|DEBUG|86282|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-03 12:21:39,658|DEBUG|86282|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 34 sessions

2026-02-03 12:21:39,676|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:39,704|INFO|86282|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-03 12:21:39,706|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-03 12:21:41,635|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-03 12:21:42,030|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-03 12:21:42,417|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-03 12:21:42,669|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-03 12:21:42,682|INFO|86282|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-03 12:21:42,683|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-03 12:21:42,884|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-03 12:21:43,592|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-03 12:21:43,725|INFO|86282|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-03 12:21:43,731|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:44,649|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-29_17-21') 2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min
2026-02-03 12:21:44,740|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-03 12:21:45,006|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:45,278|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:45,633|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-03 12:21:45,832|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-03 12:21:46,071|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:46,289|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-11_17-42') 2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:46,616|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-03 12:21:46,866|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:47,095|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:47,318|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:47,611|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:47,847|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:48,132|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-21_18-49') 2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:21:48,245|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-22_17-51') 2025-01-22_17-51_rYL006_P1100_LinearTrackStop_5min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-22_17-51_rYL006_P1100_LinearTrackStop_5min
2026-02-03 12:21:48,345|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-03 12:21:48,863|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-03 12:21:49,251|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-03 12:21:49,759|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-03 12:21:49,774|INFO|86282|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-03 12:21:49,775|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-03 12:21:50,333|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-03 12:21:50,350|INFO|86282|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-03 12:21:50,350|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-03 12:21:50,847|DEBUG|86282|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-03 12:21:51,858|INFO|86282|analytics|get_analytics
	Returning FiringRate40msHz for 29 sessions.
2026-02-03 12:21:52,026|DEBUG|86282|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 Unit0001  Unit0002  Unit0003  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0004  Unit0005  Unit0006  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0007  Unit0008  Unit0009  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0010  ...  Unit0070  \
paradigm_id animal_id session_id       entry_id            ...
1100        6         2024-11-14_16-40 0                0  ...         0
                                       1                0  ...         0
                                       2                0  ...         0
                                       3                0  ...         0
                                       4                0  ...         0
...                                                   ...  ...       ...
                      2025-01-27_13-39 110898           0  ...         0
                                       110899           0  ...         0
                                       110900           0  ...         0
                                       110901           0  ...         0
                                       110902           0  ...        25

                                                 Unit0071  Unit0072  Unit0073  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898          25         0         0
                                       110899          25         0         0
                                       110900          25         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0074  Unit0075  Unit0076  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898          50         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0        25         0

                                                 Unit0077  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0
                                       1                0
                                       2                0
                                       3                0
                                       4                0
...                                                   ...
                      2025-01-27_13-39 110898           0
                                       110899           0
                                       110900           0
                                       110901           0
                                       110902           0

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                            0
                                       1                        40000
                                       2                        80000
                                       3                       120000
                                       4                       160000
...                                                               ...
                      2025-01-27_13-39 110898              4435920000
                                       110899              4435960000
                                       110900              4436000000
                                       110901              4436040000
                                       110902              4436080000

                                                 to_ephys_timestamp
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      40000
                                       1                      80000
                                       2                     120000
                                       3                     160000

In [ ]:
# ensamble related data
ensambles = analytics.get_analytics('ConcatenatedEnsambles40ms', session_names=session_names)
ens_data = analytics.get_analytics('TrackwiseEnsembleProj', session_names=session_names)
ensamble_proj = analytics.get_analytics('ConcatenatedEnsambleProj40ms', session_names=session_names)#.drop("to_ephys_timestamp", axis=1)
ensamble_proj.set_index(['session_id'], inplace = True)
ens_data = ens_data.set_index(['session_id', 'trial_id']).sort_index()

2026-02-03 12:23:18,012|DEBUG|86282|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-03 12:23:18,363|DEBUG|86282|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 34 sessions

2026-02-03 12:23:18,364|DEBUG|86282|analytics|get_analytics
	Processing ConcatenatedEnsambles40ms, for n=34 sessions
2026-02-03 12:23:18,408|INFO|86282|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambles40ms` last modified on 2025-07-23T14:15:05.148205
2026-02-03 12:23:18,408|DEBUG|86282|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-03 12:23:18,411|DEBUG|86282|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 34 sessions

2026-02-03 12:23:18,411|DEBUG|86282|analytics|get_analytics
	Processing TrackwiseEnsembleProj, for n=34 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambles40ms.parquet
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/TrackwiseEnsembleProj.parquet

2026-02-03 12:23:35,525|INFO|86282|analytics|get_analytics
	Loaded animal-level analytic `TrackwiseEnsembleProj` last modified on 2026-01-30T17:48:01.007341
2026-02-03 12:23:35,555|DEBUG|86282|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-03 12:23:35,602|DEBUG|86282|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 34 sessions

2026-02-03 12:23:35,604|DEBUG|86282|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=34 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-03 12:24:14,899|INFO|86282|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2025-07-23T14:16:02.733331

In [5]:
# t0 bin
t0_events = analytics.get_analytics('TrialWiseT0Events40ms', session_names=session_names)
t0_events

2026-02-03 12:24:15,728|DEBUG|86282|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-03 12:24:16,028|DEBUG|86282|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 34 sessions

2026-02-03 12:24:16,030|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:16,081|INFO|86282|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-03 12:24:16,082|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-03 12:24:16,174|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-03 12:24:16,255|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-03 12:24:16,425|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-03 12:24:16,494|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-03 12:24:16,507|INFO|86282|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-03 12:24:16,507|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-03 12:24:16,610|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-03 12:24:16,665|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-03 12:24:16,692|INFO|86282|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-03 12:24:16,693|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:16,743|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-29_17-21') 2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min
2026-02-03 12:24:16,813|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-03 12:24:16,869|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:16,920|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:16,989|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-03 12:24:17,032|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-03 12:24:17,094|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:17,144|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-11_17-42') 2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:17,250|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-03 12:24:17,335|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:17,466|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:17,515|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:17,560|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:17,602|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:17,641|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-21_18-49') 2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min
2026-02-03 12:24:17,722|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-22_17-51') 2025-01-22_17-51_rYL006_P1100_LinearTrackStop_5min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-22_17-51_rYL006_P1100_LinearTrackStop_5min
2026-02-03 12:24:17,769|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-03 12:24:17,806|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-03 12:24:17,860|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-03 12:24:17,917|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-03 12:24:17,959|INFO|86282|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-03 12:24:17,960|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-03 12:24:18,002|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-03 12:24:18,013|INFO|86282|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-03 12:24:18,014|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-03 12:24:18,056|DEBUG|86282|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-03 12:24:18,157|INFO|86282|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 29 sessions.
2026-02-03 12:24:18,164|DEBUG|86282|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                1  1.0            0.0
                                       1                1  1.0            0.0
                                       2                1  1.0            0.0
                                       3                1  1.0            0.0
                                       4                1  1.0            0.0
...                                                   ...  ...            ...
                      2025-01-27_13-39 755            152  2.0            1.0
                                       756            152  2.0            1.0
                                       757            152  2.0            1.0
                                       758            152  2.0            1.0
                                       759            152  2.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0             False      False
                                       1             False      False
                                       2             False      False
                                       3             False      False
                                       4             False      False
...                                                    ...        ...
                      2025-01-27_13-39 755           False       True
                                       756           False       True
                                       757           False       True
                                       758           False       True
                                       759           False       True

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                      2025-01-27_13-39 755         cueZone_visible
                                       756           cueZone_entry
                                       757            cueZone_exit
                                       758       enter_reward1Zone
                                       759       enter_reward2Zone

                                                           t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0         4.600000e+06 -119.732063
                                       1         5.400000e+06  -79.536247
                                       2         6.760000e+06   24.898020
                                       3         7.080000e+06   51.438919
                                       4         9.480000e+06  170.376450
...                                                       ...         ...
                      2025-01-27_13-39 755       4.393240e+09 -120.656754
                                       756       4.394000e+09  -79.428299
                                       757       4.396000e+09   25.843262
                                       758       4.396480e+09   49.770477
                                       759       4.398880e+09  170.561493

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                      2025-01-27_13-39 755            -120.0
                                       756             -80.0
                                       757              25.0
                                       758              50.0
                                       759             170.0

                                                             pre_cue_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               (4400000.0, 4600000.0]
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 755       (4393040000.0, 4393240000.0]
                                       756                                NaN
                                       757                                NaN
                                       758                                NaN
                                       759                                NaN

                                                          nextto_cue_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1               (5400000.0, 5600000.0]
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 755                                NaN
                                       756       (4394000000.0, 4394200000.0]
                                       757                                NaN
                                       758                                NaN
                                       759                                NaN

                                                           cue_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               (4480000.0, 6080000.0]
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 755       (4393120000.0, 4394720000.0]
                                       756                                NaN
                                       757                                NaN
                                       758                                NaN
                                       759                                NaN

                                                            R1_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN

                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                1  1.0            0.0
                                       1                1  1.0            0.0
                                       2                1  1.0            0.0
                                       3                1  1.0            0.0
                                       4                1  1.0            0.0
...                                                   ...  ...            ...
                      2025-01-27_13-39 755            152  2.0            1.0
                                       756            152  2.0            1.0
                                       757            152  2.0            1.0
                                       758            152  2.0            1.0
                                       759            152  2.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0             False      False
                                       1             False      False
                                       2             False      False
                                       3             False      False
                                       4             False      False
...                                                    ...        ...
                      2025-01-27_13-39 755           False       True
                                       756           False       True
                                       757           False       True
                                       758           False       True
                                       759           False       True

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                      2025-01-27_13-39 755         cueZone_visible
                                       756           cueZone_entry
                                       757            cueZone_exit
                                       758       enter_reward1Zone
                                       759       enter_reward2Zone

                                                           t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0         4.600000e+06 -119.732063
                                       1         5.400000e+06  -79.536247
                                       2         6.760000e+06   24.898020
                                       3         7.080000e+06   51.438919
                                       4         9.480000e+06  170.376450
...                                                       ...         ...
                      2025-01-27_13-39 755       4.393240e+09 -120.656754
                                       756       4.394000e+09  -79.428299
                                       757       4.396000e+09   25.843262
                                       758       4.396480e+09   49.770477
                                       759       4.398880e+09  170.561493

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                      2025-01-27_13-39 755            -120.0
                                       756             -80.0
                                       757              25.0
                                       758              50.0
                                       759             170.0

                                                             pre_cue_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               (4400000.0, 4600000.0]
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 755       (4393040000.0, 4393240000.0]
                                       756                                NaN
                                       757                                NaN
                                       758                                NaN
                                       759                                NaN

                                                          nextto_cue_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1               (5400000.0, 5600000.0]
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 755                                NaN
                                       756       (4394000000.0, 4394200000.0]
                                       757                                NaN
                                       758                                NaN
                                       759                                NaN

                                                           cue_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               (4480000.0, 6080000.0]
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 755       (4393120000.0, 4394720000.0]
                                       756                                NaN
                                       757                                NaN
                                       758                                NaN
                                       759                                NaN

                                                            R1_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3               (6480000.0, 8280000.0]
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 755                                NaN
                                       756                                NaN
                                       757                                NaN
                                       758       (4395880000.0, 4397680000.0]
                                       759                                NaN

                                                            R2_entry_interval
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4              (9080000.0, 10680000.0]
...                                                                       ...
                      2025-01-27_13-39 755                                NaN
                                       756                                NaN
                                       757                                NaN
                                       758                                NaN
                                       759       (4398480000.0, 4400080000.0]

[14184 rows x 14 columns]

In [8]:
len(t0_events.index.get_level_values('session_id').unique())

for session_id in t0_events.index.get_level_values('session_id').unique():

29

In [ ]:
df = ens_data

# If session_id is in the index, bring it back as a column
if "session_id" not in df.columns:
    if isinstance(df.index, pd.MultiIndex) and "session_id" in df.index.names:
        df = df.reset_index()
    elif df.index.name == "session_id":
        df = df.reset_index()

trial_avg = (
    df.groupby(["session_id", "from_position_bin", "cue"], as_index=False)["Assembly012"]
      .mean()
      .rename(columns={"Assembly012": "Assembly012_mean"})
)

trial_avg = trial_avg[trial_avg["cue"].isin([1, 2])].copy()

# sorting x-axis values
pos_numeric = pd.to_numeric(trial_avg["from_position_bin"], errors="coerce")
if pos_numeric.notna().any():
    trial_avg["_pos"] = pos_numeric
    x_order = np.sort(trial_avg["_pos"].dropna().unique())
    # keep a numeric x for correct ordering/spacing
    trial_avg["_x"] = trial_avg["_pos"]
    x_ticks = x_order
    x_ticktext = [str(int(x)) if float(x).is_integer() else str(x) for x in x_order]
else:
    # fallback: treat as ordered categorical by appearance
    trial_avg["_x"] = trial_avg["from_position_bin"].astype(str)
    x_order = list(pd.unique(trial_avg["_x"]))
    x_ticks = x_order
    x_ticktext = x_order

# Ridgeline plot parameters
sessions = sorted(trial_avg["session_id"].unique())
dy = 0.8          # vertical spacing between sessions
cue_offset = 0.02 # vertical separation between cue 1 and cue 2 within a session
amp = 0.2

fig = go.Figure()

for i, s in enumerate(sessions):
    base = i * dy

    for cue, off in [(1, -cue_offset), (2, +cue_offset)]:
        sub = trial_avg[(trial_avg["session_id"] == s) & (trial_avg["cue"] == cue)].copy()

        # Ensure every x bin exists, fill missing with 0 (or np.nan if you prefer gaps)
        if pos_numeric.notna().any():
            sub = sub.set_index("_x").reindex(x_order).reset_index()
        else:
            sub = sub.set_index("_x").reindex(x_order).reset_index()

        y = sub["Assembly012_mean"].fillna(0.0).to_numpy()
        y_ridge = base + off + amp * y

        fig.add_trace(
            go.Scatter(
                x=sub["_x"],
                y=y_ridge,
                mode="lines",
                line=dict(width=1, color= cue == 1 and "orange" or "purple"),
                fill= None,
                name=f"session {s} | cue {cue}",
                hovertemplate=(
                    "session=%{customdata[0]}<br>"
                    "cue=%{customdata[1]}<br>"
                    "from_position_bin=%{x}<br>"
                    "mean(Assembly012)=%{customdata[2]:.4f}<extra></extra>"
                ),
                customdata=np.c_[np.full(len(sub), s), np.full(len(sub), cue), y],
                showlegend=True,
            )
        )



#Layout polish
fig.update_layout(
    title="Ridgeline: mean(Assembly012) per from_position_bin, one ridge per session",
    xaxis_title="from_position_bin",
    yaxis_title="session_id (stacked ridges)",
    # hovermode="x",
    height=max(450, 40 * len(sessions) + 200),
)

# Put session labels on the y-axis at each session baseline
fig.update_yaxes(
    tickmode="array",
    tickvals=[i * dy for i in range(len(sessions))],
    ticktext=[str(s) for s in sessions],
)

fig.add_vrect(x0=-80, x1=25,  fillcolor="orange", opacity=0.2, layer="below", line_width=0)
fig.add_vrect(x0=50,  x1=110, fillcolor="grey",   opacity=0.2, layer="below", line_width=0)
fig.add_vrect(x0=170, x1=230, fillcolor="grey",   opacity=0.2, layer="below", line_width=0)


if pos_numeric.notna().any():
    fig.update_xaxes(
        tickmode="array",
        ticktext=x_ticktext,
        showgrid=False, zeroline=False
    )

fig.show()

In [27]:
ens = ensamble_proj.copy()
t0 = t0_events.copy()

# Ensure columns exist (index -> columns if needed)
if isinstance(ens.index, pd.MultiIndex):
    ens = ens.reset_index()
elif ens.index.name is not None:
    ens = ens.reset_index()

if isinstance(t0.index, pd.MultiIndex):
    t0 = t0.reset_index()
elif t0.index.name is not None:
    t0 = t0.reset_index()

# Choose the assembly to plot
ens_col = "Assembly012"

# Midpoint time for each 40 ms bin
ens["t_mid"] = 0.5 * (ens["from_ephys_timestamp"].to_numpy() + ens["to_ephys_timestamp"].to_numpy())

import numpy as np
import pandas as pd

ens = ensamble_proj.copy()
t0  = t0_events.copy()

# Ensure columns exist
if isinstance(ens.index, pd.MultiIndex) or ens.index.name is not None:
    ens = ens.reset_index()
if isinstance(t0.index, pd.MultiIndex) or t0.index.name is not None:
    t0 = t0.reset_index()

# Midpoint time of each bin
ens["t_mid"] = 0.5 * (ens["from_ephys_timestamp"].to_numpy() + ens["to_ephys_timestamp"].to_numpy())

# 1) Build per-trial table from t0_events
# Identify interval columns (your analytic uses many "*_interval" columns)
interval_cols = [c for c in t0.columns if c.endswith("_interval")]

# Condense to one row per (session_id, trial_id) and compute trial_interval from ALL intervals
def build_trial_interval(g: pd.DataFrame) -> pd.Interval | None:
    lefts, rights = [], []
    for col in interval_cols:
        vals = g[col].dropna()
        if vals.empty:
            continue
        # vals should be pandas.Interval objects
        for iv in vals:
            lefts.append(iv.left)
            rights.append(iv.right)
    if len(lefts) == 0:
        return None
    return pd.Interval(min(lefts), max(rights), closed="both")

# Keep stable per-trial metadata (cue/t0 can be taken as first non-null)
meta_cols = [c for c in ["cue", "t0"] if c in t0.columns]
zone_cols = [c for c in ["cue_entry_interval", "R1_entry_interval", "R2_entry_interval"] if c in t0.columns]

t0_trial = (
    t0.groupby(["session_id", "trial_id"], as_index=False)
      .first()[["session_id", "trial_id"] + meta_cols + zone_cols]
)

trial_iv = (
    t0.groupby(["session_id", "trial_id"], as_index=False)
      .apply(build_trial_interval)
      .reset_index(name="trial_interval")
)

t0_trial = t0_trial.merge(trial_iv, on=["session_id", "trial_id"], how="left")

# Drop trials without any interval information
t0_trial = t0_trial.dropna(subset=["trial_interval"]).copy()

# 2) Assign each ensemble bin to a trial_id within each session
assigned = []
debug_rows = []

for s, ens_s in ens.groupby("session_id", sort=False):
    trials_s = t0_trial[t0_trial["session_id"] == s].copy()

    if trials_s.empty:
        debug_rows.append((s, "no_trials", np.nan, np.nan, np.nan, np.nan))
        continue

    iv = pd.IntervalIndex(trials_s["trial_interval"].tolist())

    t_mid = ens_s["t_mid"].to_numpy()
    idx = iv.get_indexer(t_mid)  # -1 if not contained

    n_ok = int((idx >= 0).sum())

    # Diagnostics: compare ranges
    ens_min, ens_max = float(np.nanmin(t_mid)), float(np.nanmax(t_mid))
    tri_min = float(min([x.left for x in iv]))
    tri_max = float(max([x.right for x in iv]))
    debug_rows.append((s, "ok" if n_ok > 0 else "no_match", n_ok, ens_min, ens_max, tri_min, tri_max))

    if n_ok == 0:
        continue

    ens_s = ens_s.copy()
    ens_s = ens_s.loc[idx >= 0].copy()
    ens_s["trial_id"] = trials_s["trial_id"].to_numpy()[idx[idx >= 0]]
    assigned.append(ens_s)

# If still empty, print a compact debug table to see what is wrong
if len(assigned) == 0:
    dbg = pd.DataFrame(
        debug_rows,
        columns=["session_id", "status", "n_assigned", "ens_t_min", "ens_t_max", "trial_t_min", "trial_t_max"]
    ).sort_values("session_id")
    display(dbg)
    raise ValueError("No bins could be assigned to trials. Inspect dbg above (time-base mismatch or trial intervals do not cover ensemble timestamps).")

ens_assigned = pd.concat(assigned, ignore_index=True)

# -------------------------
# 3) Ridgeline signal: mean activation per (session, cue, aligned time)
# -------------------------
ridge = (
    ens_assigned.groupby(["session_id", "cue", "t_bin"], as_index=False)[ens_col]
    .mean()
    .rename(columns={ens_col: "ens_mean"})
)

# -------------------------
# 4) Zone occupancy fractions per (session, cue, aligned time)
# -------------------------
def _in_interval(iv, x):
    if iv is None or (isinstance(iv, float) and np.isnan(iv)):
        return False
    return (x in iv)

ens_assigned["in_cue"] = ens_assigned.apply(lambda r: _in_interval(r["cue_entry_interval"], r["t_mid"]), axis=1)
ens_assigned["in_r1"]  = ens_assigned.apply(lambda r: _in_interval(r["R1_entry_interval"],  r["t_mid"]), axis=1)
ens_assigned["in_r2"]  = ens_assigned.apply(lambda r: _in_interval(r["R2_entry_interval"],  r["t_mid"]), axis=1)

occ = (
    ens_assigned.groupby(["session_id", "cue", "t_bin"], as_index=False)[["in_cue", "in_r1", "in_r2"]]
    .mean()
    .rename(columns={"in_cue": "f_cue", "in_r1": "f_r1", "in_r2": "f_r2"})
)

plot_df = ridge.merge(occ, on=["session_id", "cue", "t_bin"], how="left").fillna(0.0)

# -------------------------
# 5) Plot: ridgeline with time-varying saturation via short segments
# -------------------------
def hex_to_rgb01(h):
    h = h.lstrip("#")
    return np.array([int(h[i:i+2], 16) for i in (0, 2, 4)], dtype=float) / 255.0

def rgb01_to_hex(rgb01):
    rgb = np.clip(np.round(rgb01 * 255.0), 0, 255).astype(int)
    return "#{:02x}{:02x}{:02x}".format(rgb[0], rgb[1], rgb[2])

def mix_zone_color(f_cue, f_r1, f_r2,
                   cue_hex="#ff7f0e", r1_hex="#2ca02c", r2_hex="#9467bd",
                   background_hex="#ffffff"):
    cue = hex_to_rgb01(cue_hex)
    r1  = hex_to_rgb01(r1_hex)
    r2  = hex_to_rgb01(r2_hex)
    bg  = hex_to_rgb01(background_hex)

    f = np.array([f_cue, f_r1, f_r2], dtype=float)
    f = np.clip(f, 0.0, 1.0)
    s = f.sum()
    if s > 1.0:
        f = f / s
        s = 1.0

    rgb = bg * (1.0 - s) + cue * f[0] + r1 * f[1] + r2 * f[2]
    return rgb01_to_hex(rgb)

sessions = sorted(plot_df["session_id"].unique())
dy = 0.8
cue_offset = 0.03
amp = 0.25
downsample = 1  # raise to 2..5 if too slow

fig = go.Figure()

for i, s in enumerate(sessions):
    base = i * dy
    for cue, off in [(1, -cue_offset), (2, +cue_offset)]:
        sub = plot_df[(plot_df["session_id"] == s) & (plot_df["cue"] == cue)].sort_values("t_bin")
        if sub.empty:
            continue
        sub = sub.iloc[::downsample].reset_index(drop=True)

        x = sub["t_bin"].to_numpy()
        y = sub["ens_mean"].to_numpy()
        y_r = base + off + amp * y

        fc = sub["f_cue"].to_numpy()
        f1 = sub["f_r1"].to_numpy()
        f2 = sub["f_r2"].to_numpy()

        for k in range(len(sub) - 1):
            c = mix_zone_color(fc[k], f1[k], f2[k])
            fig.add_trace(
                go.Scatter(
                    x=[x[k], x[k+1]],
                    y=[y_r[k], y_r[k+1]],
                    mode="lines",
                    line=dict(width=1.6, color=c),
                    name=f"session {s} | cue {cue}",
                    showlegend=(k == 0),
                    customdata=[[s, cue, x[k], y[k], fc[k], f1[k], f2[k]]],
                    hovertemplate=(
                        "session=%{customdata[0]}<br>"
                        "cue=%{customdata[1]}<br>"
                        "t_rel_s=%{customdata[2]:.3f}<br>"
                        f"mean({ens_col})=%{{customdata[3]:.4f}}<br>"
                        "f_cue=%{customdata[4]:.2f}, f_R1=%{customdata[5]:.2f}, f_R2=%{customdata[6]:.2f}"
                        "<extra></extra>"
                    ),
                )
            )

fig.update_layout(
    title=f"Ridgeline over aligned time: mean({ens_col}) from ensamble_proj (colored by zone occupancy fraction)",
    xaxis_title="Aligned time (s) relative to t0",
    yaxis_title="session_id (stacked ridges)",
    height=max(450, 40 * len(sessions) + 200),
)
fig.update_yaxes(
    tickmode="array",
    tickvals=[i * dy for i in range(len(sessions))],
    ticktext=[str(s) for s in sessions],
)
fig.update_xaxes(showgrid=False, zeroline=False)

fig.show()

/var/folders/ml/fyq5x5t55wx4129dn03n32hm0000gn/T/ipykernel_86282/2104634433.py:66: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

TypeError: DataFrame.reset_index() got an unexpected keyword argument 'name'

In [30]:
fr_track

                                                 from_position_bin  trial_id  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    -169.0         1
                                       1                    -169.0         2
                                       2                    -169.0         3
                                       3                    -169.0         4
                                       4                    -169.0         5
...                                                            ...       ...
                      2025-01-27_13-39 65488                 262.0       123
                                       65489                 262.0       124
                                       65490                 262.0       128
                                       65491                 262.0       135
                                       65492                 262.0       139

                                                 Unit0001   Unit0002  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0         1.666667   0.000000
                                       1         0.000000   0.000000
                                       2         0.000000   3.333333
                                       3         3.333333   0.000000
                                       4         1.666667   0.000000
...                                                   ...        ...
                      2025-01-27_13-39 65488     0.000000   0.000000
                                       65489     0.000000   0.000000
                                       65490     0.000000  12.500000
                                       65491     0.000000   0.000000
                                       65492     0.000000   0.000000

                                                 Unit0003  Unit0004  Unit0005  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              0.0       0.0  1.666667
                                       1              0.0       0.0  0.000000
                                       2              0.0       0.0  0.000000
                                       3              0.0       0.0  0.000000
                                       4              0.0       0.0  1.666667
...                                                   ...       ...       ...
                      2025-01-27_13-39 65488          0.0       0.0  0.000000
                                       65489          0.0       0.0  0.000000
                                       65490          0.0      12.5  0.000000
                                       65491          0.0       0.0  0.000000
                                       65492          0.0       0.0  0.000000

                                                 Unit0006  Unit0007  Unit0008  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              0.0       0.0       0.0
                                       1              0.0       0.0       0.0
                                       2              0.0       0.0       0.0
                                       3              0.0       0.0       0.0
                                       4              0.0       0.0       0.0
...                                                   ...       ...       ...
                      2025-01-27_13-39 65488          0.0       0.0       0.0
                                       65489          0.0      25.0       0.0
                                       65490          0.0       0.0       0.0
                                       65491         12.5      25.0       0.0
                                       65492          0.0       0.0       0.0

                                                 ...  Unit0073   Unit0074  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 0         ...  0.000000   5.000000
                                       1         ...  1.666667   5.000000
                                       2         ...  0.000000   1.666667
                                       3         ...  0.000000  11.666667
                                       4         ...  0.000000   3.333333
...                                              ...       ...        ...
                      2025-01-27_13-39 65488     ...  0.000000  25.000000
                                       65489     ...  0.000000  12.500000
                                       65490     ...  0.000000  25.000000
                                       65491     ...  0.000000  25.000000
                                       65492     ...  0.000000  12.500000

                                                 Unit0075   Unit0076  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              0.0   0.000000
                                       1              0.0   0.000000
                                       2              0.0   0.000000
                                       3              0.0   0.000000
                                       4              0.0   1.666667
...                                                   ...        ...
                      2025-01-27_13-39 65488          0.0  12.500000
                                       65489          0.0   0.000000
                                       65490         12.5   0.000000
                                       65491          0.0   0.000000
                                       65492          0.0   0.000000

                                                 Unit0077  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              0.0    1              0
                                       1              0.0    2              0
                                       2              0.0    2             10
                                       3              0.0    1              0
                                       4              0.0    1              0
...                                                   ...  ...            ...
                      2025-01-27_13-39 65488          0.0    1              0
                                       65489          0.0    2              0
                                       65490          0.0    1              0
                                       65491          0.0    1              1
                                       65492          0.0    1              0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0             False      False
                                       1             False      False
                                       2              True      False
                                       3             False      False
                                       4              True      False
...                                                    ...        ...
                      2025-01-27_13-39 65488         False       True
                                       65489         False      False
                                       65490         False       True
                                       65491          True      False
                                       65492         False       True

                                                 bin_length
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.59680
                                       1            0.59850
                                       2            0.60285
                                       3            0.59675
                                       4            0.59665
...                                                     ...
                      2025-01-27_13-39 65488        0.08000
                                       65489        0.08000
                                       65490        0.08000
                                       65491        0.08000
                                       65492        0.08000

[1223260 rows x 84 columns]