In [1]:
import os
import sys
import re
import numpy as np
import pandas as pd
import plotly.express as px
import scipy.stats as stats
from scipy.stats import pearsonr
from dash import html, dcc, Input, Output, Dash
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

sys.path.append(os.path.join(os.getcwd(), '..', '..', '..'))
from baseVR.base_functionality import init_import_paths
init_import_paths() 

from CustomLogger import CustomLogger as Logger
from analytics_processing import analytics

from analytics_processing.sessions_from_nas_parsing import sessionlist_fullfnames_from_args, fullfnames2snames
from dashsrc.plot_components.plots import plot_TrackFiringRate
from dashsrc.plot_components.plots import plot_unit_fr_stability

In [2]:
Logger().init_logger(None, None, logging_level="DEBUG")
animal_ids = [6]
paradigm = [1100]
session_range = [1,33]
session_ids = None
normalize = True
smooth = False
excl_session_names =  ['2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min', '2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min', '2025-01-22_17-51_rYL006_P1100_LinearTrackStop_5min', '2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min'] # ignore short sessions (10, 24,25)

session_dirs = sessionlist_fullfnames_from_args(paradigm, animal_ids, session_ids, excl_session_names=excl_session_names)[0]
session_names= fullfnames2snames(session_dirs)

2026-02-26 16:41:51,337|DEBUG|41770|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Searching NAS for applicable sessions...
2026-02-26 16:41:51,693|DEBUG|41770|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Session 2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min.hdf5 excluded
2026-02-26 16:41:51,974|DEBUG|41770|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Session 2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min.hdf5 excluded
2026-02-26 16:41:52,151|DEBUG|41770|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Session 2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min.hdf5 excluded
2026-02-26 16:41:52,174|DEBUG|41770|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Session 2025-01-22_17-51_rYL006_P1100_LinearTrackStop_5min.hdf5 excluded
2026-02-26 16:41:52,418|DEBUG|41770|sessions_from_nas_parsing|get_sessionlist_fullfnames
	For paradigms [1100], animals [6], found 30 sessions.
2026-02-26 16:41:52,419|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: [1100], animal_ids: [6], session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

In [3]:
# firing rates and behavior data
fr = analytics.get_analytics('FiringRate40msHz', session_names=session_names)
fr_track = analytics.get_analytics('FiringRateTrackwiseHz', session_names=session_names)
# fr_z_scored  = analytics.get_analytics('FiringRate40msZ', session_names=session_names)
fr_z_all_sess = fr.apply(lambda unit_fr: ((unit_fr - unit_fr.mean()) / unit_fr.std()))
behav = analytics.get_analytics('BehaviorTrackwise', session_names=session_names)
# behav.index = behav.index.droplevel(('animal_id', 'paradigm_id', 'entry_id'))

2026-02-26 16:41:52,431|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:41:52,885|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-26 16:41:52,886|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:52,904|INFO|41770|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-26 16:41:52,905|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-26 16:41:53,267|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-26 16:41:53,547|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-26 16:41:53,746|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:41:54,012|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-26 16:41:54,037|INFO|41770|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-26 16:41:54,038|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-26 16:41:54,309|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:41:54,716|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-26 16:41:54,729|INFO|41770|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-26 16:41:54,730|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:55,114|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-26 16:41:55,352|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:55,625|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:55,931|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:41:56,278|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-26 16:41:56,521|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:56,804|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-26 16:41:57,156|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:57,489|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:57,851|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:58,291|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:58,619|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:41:58,926|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-26 16:41:59,366|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-26 16:41:59,661|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-26 16:41:59,970|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-26 16:41:59,997|INFO|41770|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-26 16:41:59,998|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-26 16:42:00,614|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-26 16:42:00,649|INFO|41770|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-26 16:42:00,650|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-26 16:42:01,132|DEBUG|41770|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-26 16:42:02,305|INFO|41770|analytics|get_analytics
	Returning FiringRate40msHz for 25 sessions.
2026-02-26 16:42:02,426|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 Unit0001  Unit0002  Unit0003  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0004  Unit0005  Unit0006  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0007  Unit0008  Unit0009  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0010  ...  Unit0070  \
paradigm_id animal_id session_id       entry_id            ...
1100        6         2024-11-14_16-40 0                0  ...         0
                                       1                0  ...         0
                                       2                0  ...         0
                                       3                0  ...         0
                                       4                0  ...         0
...                                                   ...  ...       ...
                      2025-01-27_13-39 110898           0  ...         0
                                       110899           0  ...         0
                                       110900           0  ...         0
                                       110901           0  ...         0
                                       110902           0  ...        25

                                                 Unit0071  Unit0072  Unit0073  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898          25         0         0
                                       110899          25         0         0
                                       110900          25         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0074  Unit0075  Unit0076  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898          50         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0        25         0

                                                 Unit0077  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0
                                       1                0
                                       2                0
                                       3                0
                                       4                0
...                                                   ...
                      2025-01-27_13-39 110898           0
                                       110899           0
                                       110900           0
                                       110901           0
                                       110902           0

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                            0
                                       1                        40000
                                       2                        80000
                                       3                       120000
                                       4                       160000
...                                                               ...
                      2025-01-27_13-39 110898              4435920000
                                       110899              4435960000
                                       110900              4436000000
                                       110901              4436040000
                                       110902              4436080000

                                                 to_ephys_timestamp
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      40000
                                       1                      80000
                                       2                     120000
                                       3                     160000
                                       4                     200000
...                                                             ...
                      2025-01-27_13-39 110898            4435960000
                                       110899            4436000000
                                       110900            4436040000
                                       110901            4436080000
                                       110902            4436120000

[1272389 rows x 79 columns]
paradigm_id                      1100
animal_id                           6
session_id           2025-01-14_18-08
entry_id                        21644
Unit0001                         25.0
Unit0002                          0.0
Unit0003                          0.0
Unit0004                          0.0
Unit0005                         25.0
...                               ...
Unit0075                         25.0
Unit0076                          0.0
Unit0077                          0.0
from_ephys_timestamp      865760000.0
to_ephys_timestamp        865800000.0

[79 rows x 1 columns]
2026-02-26 16:42:02,430|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...

In [4]:
behav.keys()

Index(['from_position_bin', 'to_position_bin', 'posbin_position',
       'posbin_velocity', 'posbin_acc', 'posbin_raw', 'posbin_yaw',
       'posbin_pitch', 'posbin_raw_500msMedian', 'posbin_yaw_500msMedian',
       'posbin_pitch_500msMedian', 'posbin_raw_abs_acc_500msMedian',
       'posbin_yaw_abs_acc_500msMedian', 'posbin_pitch_abs_acc_500msMedian',
       'posbin_RawYawPitch_abs_vel_sum',
       'posbin_RawYawPitch_abs_vel_sum_500msMedian',
       'posbin_RawYawPitch_abs_acc_sum_500msMedian',
       'posbin_YawPitch_abs_vel_sum_500msMedian',
       'posbin_YawPitch_abs_acc_sum_500msMedian', 'forward_vs_rotation_corr',
       'posbin_forward_prop', 'posbin_below_velocity_thr',
       'facecam_pose_nose_neck_body1_angle_velocity',
       'facecam_pose_body1_body2_body3_angle_velocity',
       'velocity_threshold_at_R1', 'velocity_threshold_at_R2',
       'facecam_pose_nose_x', 'facecam_pose_nose_y',
       'facecam_pose_nose_likelihood', 'facecam_pose_neck_x',
       'facecam_pose_neck_y', 'facecam_pose_neck_likelihood',
       'facecam_pose_body_1_x', 'facecam_pose_body_1_y',
       'facecam_pose_body_1_likelihood', 'facecam_pose_body_2_x',
       'facecam_pose_body_2_y', 'facecam_pose_body_2_likelihood',
       'facecam_pose_body_3_x', 'facecam_pose_body_3_y',
       'facecam_pose_body_3_likelihood', 'facecam_pose_ephys_timestamp',
       'facecam_pose_pc_timestamp', 'facecam_pose_nose_neck_length',
       'facecam_pose_neck_body1_length', 'facecam_pose_nose_neck_body1_angle',
       'facecam_pose_body1_body2_body3_angle',
       'facecam_pose_nose_neck_body1_angle_likelihood',
       'facecam_pose_body1_body2_body3_angle_likelihood', 'lick_count',
       'reward-removed_count', 'reward-sound_count', 'reward-valve-open_count',
       'posbin_to_pc_timestamp', 'posbin_to_ephys_timestamp', 'trial_id',
       'track_zone', 'track_zone_int', 'lick_detected',
       'reward-removed_detected', 'reward-sound_detected',
       'reward-valve-open_detected', 'trial_outcome', 'cue',
       'both_R1_R2_rewarded', 'choice_R1', 'choice_R2',
       'posbin_from_ephys_timestamp', 'posbin_from_pc_timestamp',
       'nframes_in_posbin', 'flip_Cue1R1_Cue2R2'],
      dtype='object')

In [5]:
t0_events = analytics.get_analytics('TrialWiseT0Events40ms', session_names=session_names, mode = 'recompute' )
t0_events

2026-02-26 16:43:26,190|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:43:26,603|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-26 16:43:26,604|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:43:26,620|DEBUG|41770|analytics|_compute_sess_analytic
	Computing TrialWiseT0Events40ms for 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:43:26,621|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:43:26,623|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:43:26,624|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:43:26,632|INFO|41770|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-26 16:43:26,633|WARNING|41770|analytics|_compute_sess_analytic
	Missing lower level analytic
2026-02-26 16:43:26,634|WARNING|41770|analytics|get_analytics
	Failed to compute TrialWiseT0Events40ms for (1100, 6, '2024-11-14_15-01')
================================================================================

2026-02-26 16:43:26,636|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-26 16:43:26,651|DEBUG|41770|analytics|_compute_sess_analytic
	Computing TrialWiseT0Events40ms for 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min:
2026-02-26 16:43:26,652|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:43:26,653|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:43:26,654|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
================================================================================

2026-02-26 16:43:27,308|INFO|41770|analytics|get_analytics
	Returning Behavior40msAligned for 1 sessions.
2026-02-26 16:43:27,315|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 frame_raw_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                                       32195                       NaN
                                       32196                       NaN
                                       32197                       NaN
                                       32198                       NaN
                                       32199                       NaN

                                                 frame_raw_abs_acc_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                   NaN
                                       1                                   NaN
                                       2                                   NaN
                                       3                                   NaN
                                       4                                   NaN
...                                                                        ...
                                       32195                               NaN
                                       32196                               NaN
                                       32197                               NaN
                                       32198                               NaN
                                       32199                               NaN

                                                 frame_YawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                                       32195                                        NaN
                                       32196                                        NaN
                                       32197                                        NaN
                                       32198                                        NaN
                                       32199                                        NaN

                                                 frame_YawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                                       32195                                        NaN
                                       32196                                        NaN
                                       32197                                        NaN
                                       32198                                        NaN
                                       32199                                        NaN

                                                 frame_RawYawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                                       32195                                           NaN
                                       32196                                           NaN
                                       32197                                           NaN
                                       32198                                           NaN
                                       32199                                           NaN

                                                 frame_RawYawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                                       32195                                           NaN
                                       32196                                           NaN
                                       32197                                           NaN
                                       32198                                           NaN
                                       32199                                           NaN

                                                 frame_forward_prop  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                        NaN
                                       1                        NaN
                                       2                        NaN
                                       3                        NaN
                                       4                        NaN
...                                                             ...
                                       32195                    NaN
                                       32196                    NaN
                                       32197                    NaN
                                       32198                    NaN
                                       32199                    NaN

                                                 forward_vs_rotation_corr  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                              NaN
                                       1                              NaN
                                       2                              NaN
                                       3                              NaN
                                       4                              NaN
...                                                                   ...
                                       32195                          NaN
                                       32196                          NaN
                                       32197                          NaN
                                       32198                          NaN
                                       32199                          NaN

                                                 frame_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    NaN
                                       1                    NaN
                                       2                    NaN
                                       3                    NaN
                                       4                    NaN
...                                                         ...
                                       32195                NaN
                                       32196                NaN
                                       32197                NaN
                                       32198                NaN
                                       32199                NaN

                                                 facecam_pose_nose_neck_body1_angle_velocity  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                                 NaN
                                       1                                                 NaN
                                       2                                                 NaN
                                       3                                                 NaN
                                       4                                                 NaN
...                                                                                      ...
                                       32195                                             NaN
                                       32196                                             NaN
                                       32197                                             NaN
                                       32198                                             NaN
                                       32199                                             NaN

                                                 ...  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 0         ...  NaN            NaN
                                       1         ...  NaN            NaN
                                       2         ...  NaN            NaN
                                       3         ...  NaN            NaN
                                       4         ...  NaN            NaN
...                                              ...  ...            ...
                                       32195     ...  NaN            NaN
                                       32196     ...  NaN            NaN
                                       32197     ...  NaN            NaN
                                       32198     ...  NaN            NaN
                                       32199     ...  NaN            NaN

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               NaN        NaN
                                       1               NaN        NaN
                                       2               NaN        NaN
                                       3               NaN        NaN
                                       4               NaN        NaN
...                                                    ...        ...
                                       32195           NaN        NaN
                                       32196           NaN        NaN
                                       32197           NaN        NaN
                                       32198           NaN        NaN
                                       32199           NaN        NaN

                                                 lick_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                   NaN
                                       1                   NaN
                                       2                   NaN
                                       3                   NaN
                                       4                   NaN
...                                                        ...
                                       32195               NaN
                                       32196               NaN
                                       32197               NaN
                                       32198               NaN
                                       32199               NaN

                                                 reward-sound_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                                       32195                       NaN
                                       32196                       NaN
                                       32197                       NaN
                                       32198                       NaN
                                       32199                       NaN

                                                 reward-valve-open_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       32195                            NaN
                                       32196                            NaN
                                       32197                            NaN
                                       32198                            NaN
                                       32199                            NaN

                                                 track_zone  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                NaN
                                       1                NaN
                                       2                NaN
                                       3                NaN
                                       4                NaN
...                                                     ...
                                       32195            NaN
                                       32196            NaN
                                       32197            NaN
                                       32198            NaN
                                       32199            NaN

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                            0
                                       1                        40000
                                       2                        80000
                                       3                       120000
                                       4                       160000
...                                                               ...
                                       32195               1287800000
                                       32196               1287840000
                                       32197               1287880000
                                       32198               1287920000
                                       32199               1287960000

                                                 to_ephys_timestamp
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      40000

In [6]:
behav['reward-valve-open_detected']

paradigm_id  animal_id  session_id        entry_id
1100         6          2024-11-14_15-01  0           0.0
                                          1           0.0
                                          2           0.0
                                          3           0.0
                                          4           0.0
                                                     ...
                        2025-01-27_13-39  65051       0.0
                                          65052       0.0
                                          65053       0.0
                                          65054       0.0
                                          65055       0.0
Name: reward-valve-open_detected, Length: 1442177, dtype: float64

In [7]:
behavior = analytics.get_analytics(analytic="Behavior40msAligned", session_names=session_names)
behavior

2026-02-26 16:44:08,640|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:44:08,904|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-26 16:44:08,906|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:08,919|INFO|41770|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-26 16:44:08,922|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-26 16:44:09,735|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-26 16:44:10,687|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-26 16:44:11,397|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:44:12,012|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-26 16:44:12,026|INFO|41770|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-26 16:44:12,026|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-26 16:44:12,619|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:44:13,220|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-26 16:44:13,228|INFO|41770|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-26 16:44:13,229|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:14,147|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-26 16:44:15,149|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:16,109|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:17,128|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:44:17,886|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-26 16:44:18,712|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:19,461|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-26 16:44:20,168|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:21,055|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:21,981|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:22,932|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:23,728|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:24,596|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-26 16:44:26,005|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-26 16:44:27,105|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-26 16:44:28,126|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-26 16:44:28,127|INFO|41770|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-26 16:44:28,127|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-26 16:44:29,409|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-26 16:44:29,440|INFO|41770|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-26 16:44:29,440|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-26 16:44:30,729|DEBUG|41770|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-26 16:44:32,509|INFO|41770|analytics|get_analytics
	Returning Behavior40msAligned for 25 sessions.
2026-02-26 16:44:32,622|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 frame_raw_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                      2025-01-27_13-39 110898                      NaN
                                       110899                      NaN
                                       110900                      NaN
                                       110901                      NaN
                                       110902                      NaN

                                                 frame_raw_abs_acc_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                   NaN
                                       1                                   NaN
                                       2                                   NaN
                                       3                                   NaN
                                       4                                   NaN
...                                                                        ...
                      2025-01-27_13-39 110898                              NaN
                                       110899                              NaN
                                       110900                              NaN
                                       110901                              NaN
                                       110902                              NaN

                                                 frame_YawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                      2025-01-27_13-39 110898                                       NaN
                                       110899                                       NaN
                                       110900                                       NaN
                                       110901                                       NaN
                                       110902                                       NaN

                                                 frame_YawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                      2025-01-27_13-39 110898                                       NaN
                                       110899                                       NaN
                                       110900                                       NaN
                                       110901                                       NaN
                                       110902                                       NaN

                                                 frame_RawYawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                      2025-01-27_13-39 110898                                          NaN
                                       110899                                          NaN
                                       110900                                          NaN
                                       110901                                          NaN
                                       110902                                          NaN

                                                 frame_RawYawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                      2025-01-27_13-39 110898                                          NaN
                                       110899                                          NaN
                                       110900                                          NaN
                                       110901                                          NaN
                                       110902                                          NaN

                                                 frame_forward_prop  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                        NaN
                                       1                        NaN
                                       2                        NaN
                                       3                        NaN
                                       4                        NaN
...                                                             ...
                      2025-01-27_13-39 110898                   NaN
                                       110899                   NaN
                                       110900                   NaN
                                       110901                   NaN
                                       110902                   NaN

                                                 forward_vs_rotation_corr  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                              NaN
                                       1                              NaN
                                       2                              NaN
                                       3                              NaN
                                       4                              NaN
...                                                                   ...
                      2025-01-27_13-39 110898                         NaN
                                       110899                         NaN
                                       110900                         NaN
                                       110901                         NaN
                                       110902                         NaN

                                                 frame_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    NaN
                                       1                    NaN
                                       2                    NaN
                                       3                    NaN
                                       4                    NaN
...                                                         ...
                      2025-01-27_13-39 110898               NaN
                                       110899               NaN
                                       110900               NaN
                                       110901               NaN
                                       110902               NaN


                                                 frame_raw_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                      2025-01-27_13-39 110898                      NaN
                                       110899                      NaN
                                       110900                      NaN
                                       110901                      NaN
                                       110902                      NaN

                                                 frame_raw_abs_acc_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                   NaN
                                       1                                   NaN
                                       2                                   NaN
                                       3                                   NaN
                                       4                                   NaN
...                                                                        ...
                      2025-01-27_13-39 110898                              NaN
                                       110899                              NaN
                                       110900                              NaN
                                       110901                              NaN
                                       110902                              NaN

                                                 frame_YawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                      2025-01-27_13-39 110898                                       NaN
                                       110899                                       NaN
                                       110900                                       NaN
                                       110901                                       NaN
                                       110902                                       NaN

                                                 frame_YawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                      2025-01-27_13-39 110898                                       NaN
                                       110899                                       NaN
                                       110900                                       NaN
                                       110901                                       NaN
                                       110902                                       NaN

                                                 frame_RawYawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                      2025-01-27_13-39 110898                                          NaN
                                       110899                                          NaN
                                       110900                                          NaN
                                       110901                                          NaN
                                       110902                                          NaN

                                                 frame_RawYawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                      2025-01-27_13-39 110898                                          NaN
                                       110899                                          NaN
                                       110900                                          NaN
                                       110901                                          NaN
                                       110902                                          NaN

                                                 frame_forward_prop  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                        NaN
                                       1                        NaN
                                       2                        NaN
                                       3                        NaN
                                       4                        NaN
...                                                             ...
                      2025-01-27_13-39 110898                   NaN
                                       110899                   NaN
                                       110900                   NaN
                                       110901                   NaN
                                       110902                   NaN

                                                 forward_vs_rotation_corr  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                              NaN
                                       1                              NaN
                                       2                              NaN
                                       3                              NaN
                                       4                              NaN
...                                                                   ...
                      2025-01-27_13-39 110898                         NaN
                                       110899                         NaN
                                       110900                         NaN
                                       110901                         NaN
                                       110902                         NaN

                                                 frame_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    NaN
                                       1                    NaN
                                       2                    NaN
                                       3                    NaN
                                       4                    NaN
...                                                         ...
                      2025-01-27_13-39 110898               NaN
                                       110899               NaN
                                       110900               NaN
                                       110901               NaN
                                       110902               NaN

                                                 facecam_pose_nose_neck_body1_angle_velocity  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                                 NaN
                                       1                                                 NaN
                                       2                                                 NaN
                                       3                                                 NaN
                                       4                                                 NaN
...                                                                                      ...
                      2025-01-27_13-39 110898                                            NaN
                                       110899                                            NaN
                                       110900                                            NaN
                                       110901                                            NaN
                                       110902                                            NaN

                                                 ...  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 0         ...  NaN            NaN
                                       1         ...  NaN            NaN
                                       2         ...  NaN            NaN
                                       3         ...  NaN            NaN
                                       4         ...  NaN            NaN
...                                              ...  ...            ...
                      2025-01-27_13-39 110898    ...  NaN            NaN
                                       110899    ...  NaN            NaN
                                       110900    ...  NaN            NaN
                                       110901    ...  NaN            NaN
                                       110902    ...  NaN            NaN

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               NaN        NaN
                                       1               NaN        NaN
                                       2               NaN        NaN
                                       3               NaN        NaN
                                       4               NaN        NaN
...                                                    ...        ...
                      2025-01-27_13-39 110898          NaN        NaN
                                       110899          NaN        NaN
                                       110900          NaN        NaN
                                       110901          NaN        NaN
                                       110902          NaN        NaN

                                                 lick_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                   NaN
                                       1                   NaN
                                       2                   NaN
                                       3                   NaN
                                       4                   NaN
...                                                        ...
                      2025-01-27_13-39 110898              NaN
                                       110899              NaN
                                       110900              NaN
                                       110901              NaN
                                       110902              NaN

                                                 reward-sound_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                      2025-01-27_13-39 110898                      NaN
                                       110899                      NaN
                                       110900                      NaN
                                       110901                      NaN
                                       110902                      NaN

                                                 reward-valve-open_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                      2025-01-27_13-39 110898                           NaN
                                       110899                           NaN
                                       110900                           NaN
                                       110901                           NaN
                                       110902                           NaN

                                                 track_zone  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                NaN
                                       1                NaN
                                       2                NaN
                                       3                NaN
                                       4                NaN
...                                                     ...
                      2025-01-27_13-39 110898           NaN
                                       110899           NaN
                                       110900           NaN
                                       110901           NaN
                                       110902           NaN

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                            0
                                       1                        40000
                                       2                        80000
                                       3                       120000
                                       4                       160000
...                                                               ...
                      2025-01-27_13-39 110898              4435920000
                                       110899              4435960000
                                       110900              4436000000
                                       110901              4436040000
                                       110902              4436080000

                                                 to_ephys_timestamp
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      40000
                                       1                      80000
                                       2                     120000
                                       3                     160000
                                       4                     200000
...                                                             ...
                      2025-01-27_13-39 110898            4435960000
                                       110899            4436000000
                                       110900            4436040000
                                       110901            4436080000
                                       110902            4436120000

[1272389 rows x 25 columns]

In [8]:
behavior.keys()

Index(['frame_raw_500msMedian', 'frame_raw_abs_acc_500msMedian',
       'frame_YawPitch_abs_vel_sum_500msMedian',
       'frame_YawPitch_abs_acc_sum_500msMedian',
       'frame_RawYawPitch_abs_vel_sum_500msMedian',
       'frame_RawYawPitch_abs_acc_sum_500msMedian', 'frame_forward_prop',
       'forward_vs_rotation_corr', 'frame_position',
       'facecam_pose_nose_neck_body1_angle_velocity',
       'facecam_pose_nose_neck_body1_angle',
       'facecam_pose_nose_neck_body1_angle_likelihood',
       'frame_ephys_timestamp', 'frame_pc_timestamp', 'trial_id', 'cue',
       'trial_outcome', 'choice_R1', 'choice_R2', 'lick_detected',
       'reward-sound_detected', 'reward-valve-open_detected', 'track_zone',
       'from_ephys_timestamp', 'to_ephys_timestamp'],
      dtype='object')

In [9]:
reward_timings = behavior[behavior['reward-valve-open_detected'] == True]
reward_timings

                                                 frame_raw_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                   14.732325
                                       1347                  22.936904
                                       6379                  12.859367
                                       11081                  2.205580
                                       11198                 19.452242
...                                                                ...
                      2025-01-27_13-39 99281                  4.348683
                                       100297                 0.832736
                                       102590                 0.339174
                                       106862                14.668530
                                       109991                 5.217457

                                                 frame_raw_abs_acc_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                          310.168217
                                       1347                           0.000000
                                       6379                           7.795358
                                       11081                         11.072584
                                       11198                          7.710925
...                                                                        ...
                      2025-01-27_13-39 99281                         36.065566
                                       100297                         6.237060
                                       102590                        24.522804
                                       106862                        31.236423
                                       109991                        86.699173

                                                 frame_YawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                                     1.461005
                                       1347                                   10.432527
                                       6379                                   24.825595
                                       11081                                   0.726808
                                       11198                                   9.221894
...                                                                                 ...
                      2025-01-27_13-39 99281                                   5.339812
                                       100297                                  4.755868
                                       102590                                  6.674218
                                       106862                                  5.348795
                                       109991                                  7.163785

                                                 frame_YawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                                    36.401281
                                       1347                                   24.777545
                                       6379                                   45.513830
                                       11081                                   4.830232
                                       11198                                   6.281803
...                                                                                 ...
                      2025-01-27_13-39 99281                                  20.600760
                                       100297                                  1.327205
                                       102590                                  4.561808
                                       106862                                 71.832940
                                       109991                                 20.827230

                                                 frame_RawYawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                                       16.193330
                                       1347                                      33.369431
                                       6379                                      37.684962
                                       11081                                      2.932388
                                       11198                                     28.674137
...                                                                                    ...
                      2025-01-27_13-39 99281                                      9.688496
                                       100297                                     5.588603
                                       102590                                     7.013392
                                       106862                                    20.017325
                                       109991                                    12.381242

                                                 frame_RawYawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                                      346.569497
                                       1347                                      24.777545
                                       6379                                      53.309187
                                       11081                                     15.902816
                                       11198                                     13.992728
...                                                                                    ...
                      2025-01-27_13-39 99281                                     56.666325
                                       100297                                     7.564265
                                       102590                                    29.084612
                                       106862                                   103.069363
                                       109991                                   107.526402

                                                 frame_forward_prop  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                 0.910480
                                       1347                0.687395
                                       6379                0.341309
                                       11081               0.752215
                                       11198               0.678388
...                                                             ...
                      2025-01-27_13-39 99281               0.448353
                                       100297              0.148973
                                       102590              0.047106
                                       106862              0.733958
                                       109991              0.418291

                                                 forward_vs_rotation_corr  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                       0.307134
                                       1347                      0.028520
                                       6379                      0.739110
                                       11081                     0.126886
                                       11198                    -0.166192
...                                                                   ...
                      2025-01-27_13-39 99281                     0.537463
                                       100297                    0.259129
                                       102590                    0.161064
                                       106862                    0.635466
                                       109991                    0.037629

                                                 frame_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690            59.532880
                                       1347          111.716450
                                       6379          214.887100
                                       11081          51.968597
                                       11198         177.145800
...                                                         ...
                      2025-01-27_13-39 99281         183.205900
                                       100297        177.204400
                                       102590        189.363900
                                       106862        179.107250
                                       109991        175.711750

                                                 facecam_pose_nose_neck_body1_angle_velocity  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                                       -183.715079
                                       1347                                       267.108374
                                       6379                                       -77.500494
                                       11081                                     -211.435564
                                       11198                                      115.702129
...                                                                                      ...
                      2025-01-27_13-39 99281                                      115.033275
                                       100297                                     125.998581
                                       102590                                      23.285388
                                       106862                                      62.891860
                                       109991                                      98.102223

                                                 ...  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 690       ...  2.0           10.0
                                       1347      ...  1.0            0.0
                                       6379      ...  1.0            1.0
                                       11081     ...  1.0           11.0
                                       11198     ...  1.0           11.0
...                                              ...  ...            ...
                      2025-01-27_13-39 99281     ...  2.0            1.0
                                       100297    ...  2.0            1.0
                                       102590    ...  2.0            1.0
                                       106862    ...  2.0            1.0
                                       109991    ...  2.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690             1.0        0.0
                                       1347            1.0        0.0
                                       6379            1.0        1.0
                                       11081           1.0        1.0
                                       11198           1.0        1.0
...                                                    ...        ...
                      2025-01-27_13-39 99281           0.0        1.0
                                       100297          0.0        1.0
                                       102590          0.0        1.0
                                       106862          0.0        1.0
                                       109991          0.0        1.0

                                                 lick_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                 0.0
                                       1347                0.0
                                       6379                0.0
                                       11081               0.0
                                       11198               0.0
...                                                        ...
                      2025-01-27_13-39 99281               0.0
                                       100297              0.0
                                       102590              0.0
                                       106862              0.0
                                       109991              0.0

                                                 reward-sound_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                         0.0
                                       1347                        0.0
                                       6379                        0.0
                                       11081                       0.0
                                       11198                       0.0
...                                                                ...
                      2025-01-27_13-39 99281                       0.0
                                       100297                      0.0
                                       102590                      0.0
                                       106862                      0.0
                                       109991                      0.0

                                                 reward-valve-open_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                              1.0
                                       1347                             1.0
                                       6379                             1.0
                                       11081                            1.0
                                       11198                            1.0
...                                                                     ...
                      2025-01-27_13-39 99281                            1.0
                                       100297                           1.0
                                       102590                           1.0
                                       106862                           1.0
                                       109991                           1.0

                                                         track_zone  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690              reward1Zone
                                       1347      bewteenRewardZones
                                       6379             reward2Zone
                                       11081            reward1Zone
                                       11198            reward2Zone
...                                                             ...
                      2025-01-27_13-39 99281            reward2Zone
                                       100297           reward2Zone
                                       102590           reward2Zone
                                       106862           reward2Zone
                                       109991           reward2Zone

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                   27600000
                                       1347                  53880000
                                       6379                 255160000
                                       11081                443240000
                                       11198                447920000
...                                                               ...
                      2025-01-27_13-39 99281               3971240000
                                       100297              4011880000
                                       102590              4103600000
                                       106862              4274480000
                                       109991              4399640000

                                                 to_ephys_timestamp
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 690                 27640000
                                       1347                53920000
                                       6379               255200000
                                       11081              443280000
                                       11198              447960000
...                                                             ...
                      2025-01-27_13-39 99281             3971280000
                                       100297            4011920000
                                       102590            4103640000
                                       106862            4274520000
                                       109991            4399680000

[1056 rows x 25 columns]

In [10]:
t0_ens = analytics.get_analytics('EnsembleT0Projection', session_names=session_names, mode='recompute')

2026-02-26 16:44:32,807|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:44:32,867|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-26 16:44:32,868|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:44:32,873|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:44:32,873|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:44:32,874|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:44:32,875|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:45:11,402|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:11,405|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:11,425|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:11,425|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:45:11,440|INFO|41770|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-26 16:45:11,441|WARNING|41770|analytics|_compute_sess_analytic
	Missing lower level analytic
2026-02-26 16:45:11,450|WARNING|41770|analytics|get_analytics
	Failed to compute EnsembleT0Projection for (1100, 6, '2024-11-14_15-01')
================================================================================

2026-02-26 16:45:11,451|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-26 16:45:11,463|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min:
2026-02-26 16:45:11,464|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:11,470|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:11,470|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:45:14,946|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:14,946|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:14,953|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:14,953|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
================================================================================

2026-02-26 16:45:14,991|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:15,002|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              1.0  1.0            0.0
                                       1              1.0  1.0            0.0
                                       2              1.0  1.0            0.0
                                       3              1.0  1.0            0.0
                                       4              1.0  1.0            0.0
...                                                   ...  ...            ...
                                       724          102.0  1.0            0.0
                                       725          102.0  1.0            0.0
                                       726          102.0  1.0            0.0
                                       727          102.0  1.0            0.0
                                       728          102.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0        0.0
                                       1               0.0        0.0
                                       2               0.0        0.0
                                       3               0.0        0.0
                                       4               0.0        0.0
...                                                    ...        ...
                                       724             0.0        0.0
                                       725             0.0        0.0
                                       726             0.0        0.0
                                       727             0.0        0.0
                                       728             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       724            cueZone_exit
                                       725       enter_reward1Zone
                                       726       enter_reward2Zone
                                       727        exit_reward1Zone
                                       728        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            4600000 -119.732067
                                       1            5400000  -79.536247
                                       2            6760000   24.898020
                                       3            7080000   51.438920
                                       4            9480000  170.376450
...                                                     ...         ...
                                       724       1281240000   25.444143
                                       725       1281840000   49.118980
                                       726       1284120000  170.746800
                                       727       1283040000  109.076567
                                       728       1285320000  229.460000

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       724              25.0
                                       725              50.0
                                       726             170.0
                                       727             110.0
                                       728             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-14_16-40 0         (4400000.0, 4600000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       724                          NaN  ...
                                       725                          NaN  ...
                                       726                          NaN  ...
                                       727                          NaN  ...
                                       728                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4              (9080000.0, 10680000.0]
...                                                                       ...
                                       724                                NaN
                                       725                                NaN
                                       726       (1283720000.0, 1285320000.0]
                                       727                                NaN
                                       728                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       724                                                    None
                                       725                                                    None
                                       726                                                    None
                                       727                                                    None
                                       728                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       724                                NaN
                                       725                                NaN
                                       726                                NaN
                                       727       (1282640000.0, 1284240000.0]
                                       728                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       724                       None
                                       725                       None
                                       726                       None
                                       727                       None
                                       728                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       724                                NaN
                                       725                                NaN
                                       726                                NaN
                                       727                                NaN
                                       728       (1284920000.0, 1286520000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       724                       None
                                       725                       None
                                       726                       None
                                       727                       None
                                       728                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       724                              NaN
                                       725                              NaN
                                       726                              NaN
                                       727                              NaN
                                       728                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       724                                  None
                                       725                                  None
                                       726                                  None
                                       727                                  None
                                       728                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       724                              NaN
                                       725                              NaN
                                       726                              NaN
                                       727                              NaN
                                       728                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       724                                  None
                                       725                                  None
                                       726                                  None
                                       727                                  None
                                       728                                  None

[729 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-11-14_16-40
entry_id                                                 364
trial_id                                                52.0
cue                                                      2.0
trial_outcome                                            0.0
choice_R1                                                0.0
choice_R2                                                0.0
t0_event_name                                cueZone_visible
t0                                                 628800000
x_position                                        -118.75005
x_alignment                                           -120.0
pre_cue_interval                  (628600000.0, 628800000.0]
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                (628680000.0, 630280000.0]
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                                        NaN
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                                         NaN
R1_exit_interval_bins                                   None
R2_exit_interval                                         NaN
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None
2026-02-26 16:45:16,616|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-14_16-40 1100        6         0                      4400000
                                       0                      4440000
                                       0                      4480000
                                       0                      4520000
                                       0                      4560000
...                                                               ...
                                       728                 1286320000
                                       728                 1286360000
                                       728                 1286400000
                                       728                 1286440000
                                       728                 1286480000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-14_16-40 1100        6         0                    4440000
                                       0                    4480000
                                       0                    4520000
                                       0                    4560000

No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:18,399|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-26 16:45:18,415|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min:
2026-02-26 16:45:18,416|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:18,425|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:18,427|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:45:20,085|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:20,086|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:20,087|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:20,088|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
================================================================================

2026-02-26 16:45:20,133|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:20,140|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0              1.0  0.0            0.0
                                       1              1.0  0.0            0.0
                                       2              1.0  0.0            0.0
                                       3              1.0  0.0            0.0
                                       4              1.0  0.0            0.0
...                                                   ...  ...            ...
                                       883          121.0  1.0            0.0
                                       884          121.0  1.0            0.0
                                       885          121.0  1.0            0.0
                                       886          121.0  1.0            0.0
                                       887          121.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0               0.0        0.0
                                       1               0.0        0.0
                                       2               0.0        0.0
                                       3               0.0        0.0
                                       4               0.0        0.0
...                                                    ...        ...
                                       883             1.0        0.0
                                       884             1.0        0.0
                                       885             1.0        0.0
                                       886             1.0        0.0
                                       887             1.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       883            cueZone_exit
                                       884       enter_reward1Zone
                                       885       enter_reward2Zone
                                       886        exit_reward1Zone
                                       887        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0            4920000 -119.304450
                                       1            5800000  -79.896305
                                       2            7440000   24.000575
                                       3            7840000   50.051890
                                       4           10760000  169.714950
...                                                     ...         ...
                                       883       2135600000   24.605805
                                       884       2136040000   50.328423
                                       885       2140000000  170.526800
                                       886       2138680000  110.283433
                                       887       2141000000  231.228400

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       883              25.0
                                       884              50.0
                                       885             170.0
                                       886             110.0
                                       887             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-15_15-48 0         (4720000.0, 4920000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       883                          NaN  ...
                                       884                          NaN  ...
                                       885                          NaN  ...
                                       886                          NaN  ...
                                       887                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (10360000.0, 11960000.0]
...                                                                       ...
                                       883                                NaN
                                       884                                NaN
                                       885       (2139600000.0, 2141200000.0]
                                       886                                NaN
                                       887                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       883                                                    None
                                       884                                                    None
                                       885                                                    None
                                       886                                                    None
                                       887                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       883                                NaN
                                       884                                NaN
                                       885                                NaN
                                       886       (2138280000.0, 2139880000.0]
                                       887                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       883                       None
                                       884                       None
                                       885                       None
                                       886                       None
                                       887                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       883                                NaN
                                       884                                NaN
                                       885                                NaN
                                       886                                NaN
                                       887       (2140600000.0, 2142200000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       883                       None
                                       884                       None
                                       885                       None
                                       886                       None
                                       887                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       883                              NaN
                                       884                              NaN
                                       885                              NaN
                                       886                              NaN
                                       887                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       883                                  None
                                       884                                  None
                                       885                                  None
                                       886                                  None
                                       887                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       883                              NaN
                                       884                              NaN
                                       885                              NaN
                                       886                              NaN
                                       887                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-15_15-48 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       883                                  None
                                       884                                  None
                                       885                                  None
                                       886                                  None
                                       887                                  None

[888 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2024-11-15_15-48
entry_id                                                   444
trial_id                                                  60.0
cue                                                        1.0
trial_outcome                                              0.0
choice_R1                                                  0.0
choice_R2                                                  1.0
t0_event_name                                enter_reward2Zone
t0                                                  1220120000
x_position                                           168.89075
x_alignment                                              170.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                 (1219720000.0, 1221320000.0]
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40

2026-02-26 16:45:21,983|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0                      4720000
                                       0                      4760000
                                       0                      4800000
                                       0                      4840000
                                       0                      4880000
...                                                               ...
                                       887                 2142000000
                                       887                 2142040000
                                       887                 2142080000
                                       887                 2142120000
                                       887                 2142160000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0                    4760000
                                       0                    4800000
                                       0                    4840000
                                       0                    4880000
                                       0                    4920000
...                                                             ...
                                       887               2142040000
                                       887               2142080000
                                       887               2142120000
                                       887               2142160000
                                       887               2142200000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0           -0.056155     0.201012
                                       0            0.266791    -0.305036
                                       0            0.742083     0.901590
                                       0           -0.084525    -0.288073
                                       0           -0.225884    -0.630276
...                                                      ...          ...
                                       887          0.038712     0.191496
                                       887          1.352252     1.232128
                                       887         -0.170600    -0.137965
                                       887         -0.013705    -0.126552
                                       887          0.045991     0.362361

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0           -0.031098    -0.163762
                                       0           -0.053491    -0.253866
                                       0            0.006495    -2.013645
                                       0           -0.128994    -0.063436
                                       0           -0.228107    -0.052868
...                                                      ...          ...
                                       887         -0.215505    -0.179105
                                       887         -0.308793    -0.428622
                                       887         -0.123788     0.085477
                                       887         -0.015478    -0.100125
                                       887         -0.070388    -0.743771

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0           -0.137596    -0.366703
                                       0           -0.147612    -0.615286
                                       0            0.132161    -0.391449
                                       0           -0.080212    -0.073350
                                       0           -0.595339     0.288135
...                                                      ...          ...
                                       887         -0.214054    -0.660588
                                       887         -0.618706    -0.667644
                                       887         -0.124832     1.164888
                                       887         -0.110155    -0.316755
                                       887         -0.197938     0.142973

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0            1.923421    -0.017774
                                       0            0.003293     0.905843
                                       0           -1.655031     1.581563
                                       0            0.114827    -0.410007
                                       0           -0.142472    -0.258602
...                                                      ...          ...
                                       887         -0.625740     0.177732
                                       887         -0.316267     0.760309
                                       887          0.521003     0.447702
                                       887          0.445600    -0.100553
                                       887         -0.189566     0.386227

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-11-15_15-48 1100        6         0         ...       1.0  0.0
                                       0         ...       1.0  0.0
                                       0         ...       1.0  0.0
                                       0         ...       1.0  0.0
                                       0         ...       1.0  0.0
...                                              ...       ...  ...
                                       887       ...     121.0  1.0
                                       887       ...     121.0  1.0
                                       887       ...     121.0  1.0
                                       887       ...     121.0  1.0
                                       887       ...     121.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
...                                                        ...        ...
                                       887                 0.0        1.0
                                       887                 0.0        1.0
                                       887                 0.0        1.0
                                       887                 0.0        1.0
                                       887                 0.0        1.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
...                                                    ...               ...
                                       887             0.0  exit_reward2Zone
                                       887             0.0  exit_reward2Zone
                                       887             0.0  exit_reward2Zone
                                       887             0.0  exit_reward2Zone
                                       887             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0            4920000  -119.30445
                                       0            4920000  -119.30445
                                       0            4920000  -119.30445
                                       0            4920000  -119.30445
                                       0            4920000  -119.30445
...                                                     ...         ...
                                       887       2141000000   231.22840
                                       887       2141000000   231.22840
                                       887       2141000000   231.22840
                                       887       2141000000   231.22840
                                       887       2141000000   231.22840

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-11-15_15-48 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       887             230.0  R2_exit_interval
                                       887             230.0  R2_exit_interval
                                       887             230.0  R2_exit_interval
                                       887             230.0  R2_exit_interval
                                       887             230.0  R2_exit_interval

[30250 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:23,958|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-26 16:45:23,980|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min:
2026-02-26 16:45:23,982|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:23,996|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:23,996|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:24,144|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:24,148|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:24,148|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:24,149|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:45:24,203|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:24,210|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0              1.0  1.0            0.0
                                       1              1.0  1.0            0.0
                                       2              1.0  1.0            0.0
                                       3              1.0  1.0            0.0
                                       4              1.0  1.0            0.0
...                                                   ...  ...            ...
                                       477           67.0  2.0            0.0
                                       478           67.0  2.0            0.0
                                       479           67.0  2.0            0.0
                                       480           67.0  2.0            0.0
                                       481           67.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0               0.0        0.0
                                       1               0.0        0.0
                                       2               0.0        0.0
                                       3               0.0        0.0
                                       4               0.0        0.0
...                                                    ...        ...
                                       477             0.0        0.0
                                       478             0.0        0.0
                                       479             0.0        0.0
                                       480             0.0        0.0
                                       481             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       477            cueZone_exit
                                       478       enter_reward1Zone
                                       479       enter_reward2Zone
                                       480        exit_reward1Zone
                                       481        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0            4840000 -120.597400
                                       1            5480000  -80.675010
                                       2            7000000   24.886453
                                       3            7400000   49.706483
                                       4           10600000  169.489800
...                                                     ...         ...
                                       477       1347520000   23.594257
                                       478       1347800000   51.153397
                                       479       1349680000  169.954750
                                       480       1348560000  108.961700
                                       481       1350520000  230.217633

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       477              25.0
                                       478              50.0
                                       479             170.0
                                       480             110.0
                                       481             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-20_17-46 0         (4640000.0, 4840000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       477                          NaN  ...
                                       478                          NaN  ...
                                       479                          NaN  ...
                                       480                          NaN  ...
                                       481                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (10200000.0, 11800000.0]
...                                                                       ...
                                       477                                NaN
                                       478                                NaN
                                       479       (1349280000.0, 1350880000.0]
                                       480                                NaN
                                       481                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       477                                                    None
                                       478                                                    None
                                       479                                                    None
                                       480                                                    None
                                       481                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       477                                NaN
                                       478                                NaN
                                       479                                NaN
                                       480       (1348160000.0, 1349760000.0]
                                       481                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       477                       None
                                       478                       None
                                       479                       None
                                       480                       None
                                       481                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       477                                NaN
                                       478                                NaN
                                       479                                NaN
                                       480                                NaN
                                       481       (1350120000.0, 1351720000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       477                       None
                                       478                       None
                                       479                       None
                                       480                       None
                                       481                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       477                              NaN
                                       478                              NaN
                                       479                              NaN
                                       480                              NaN
                                       481                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       477                                  None
                                       478                                  None
                                       479                                  None
                                       480                                  None
                                       481                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       477                              NaN
                                       478                              NaN
                                       479                              NaN
                                       480                              NaN
                                       481                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-20_17-46 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       477                                  None
                                       478                                  None
                                       479                                  None
                                       480                                  None
                                       481                                  None

[482 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-11-20_17-46
entry_id                                                 241
trial_id                                                33.0
cue                                                      1.0
trial_outcome                                            0.0
choice_R1                                                0.0
choice_R2                                                0.0
t0_event_name                               exit_reward1Zone
t0                                                 808760000
x_position                                          110.1128
x_alignment                                            110.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                                        NaN
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                  (808360000.0, 809960000.0]
R1_exit_interval_bins                                   None
R2_exit_interval                                         NaN
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48

2026-02-26 16:45:25,254|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0                      4640000
                                       0                      4680000
                                       0                      4720000
                                       0                      4760000
                                       0                      4800000
...                                                               ...
                                       481                 1351520000
                                       481                 1351560000
                                       481                 1351600000
                                       481                 1351640000
                                       481                 1351680000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0                    4680000
                                       0                    4720000
                                       0                    4760000
                                       0                    4800000
                                       0                    4840000
...                                                             ...
                                       481               1351560000
                                       481               1351600000
                                       481               1351640000
                                       481               1351680000
                                       481               1351720000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0           -0.164927    -0.365296
                                       0           -0.084824     0.220376
                                       0            0.179187     0.088809
                                       0           -0.115590    -0.261299
                                       0            0.334721    -0.048524
...                                                      ...          ...
                                       481          0.071895    -0.263451
                                       481         -0.162710     0.027265
                                       481         -0.029517     0.259299
                                       481         -0.013608     0.067353
                                       481          0.344009    -0.190437

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0           -0.193012    -0.638142
                                       0           -0.427540    -0.048179
                                       0            0.220001    -0.032803
                                       0           -0.530451     0.339422
                                       0            0.413271     0.122684
...                                                      ...          ...
                                       481          0.236200     0.376497
                                       481         -0.075984    -0.043484
                                       481         -0.054937     0.313323
                                       481         -0.078936    -0.061099
                                       481          0.359922    -0.750606

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0           -0.497562    -0.182219
                                       0            1.457859     1.356620
                                       0            0.052130    -0.298048
                                       0            0.813531    -0.641802
                                       0            0.355125     0.116341
...                                                      ...          ...
                                       481         -0.263087    -0.327486
                                       481         -0.113628    -0.148395
                                       481          0.082142     0.093819
                                       481          0.030068    -0.243165
                                       481          0.015059    -0.431053

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0            2.064478     0.871247
                                       0           -0.950374    -0.473457
                                       0           -0.529209    -0.028554
                                       0            2.038437     1.023897
                                       0           -0.122551     0.183206
...                                                      ...          ...
                                       481         -0.192557     0.602341
                                       481          0.105712    -0.150865
                                       481          0.070843     0.064151
                                       481          0.216647     0.031373
                                       481         -0.262835     0.949444

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-11-20_17-46 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       481       ...      67.0  2.0
                                       481       ...      67.0  2.0
                                       481       ...      67.0  2.0
                                       481       ...      67.0  2.0
                                       481       ...      67.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
...                                                        ...        ...
                                       481                 0.0        0.0
                                       481                 0.0        0.0
                                       481                 0.0        0.0
                                       481                 0.0        0.0
                                       481                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
...                                                    ...               ...
                                       481             0.0  exit_reward2Zone
                                       481             0.0  exit_reward2Zone
                                       481             0.0  exit_reward2Zone
                                       481             0.0  exit_reward2Zone
                                       481             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0            4840000 -120.597400
                                       0            4840000 -120.597400
                                       0            4840000 -120.597400
                                       0            4840000 -120.597400
                                       0            4840000 -120.597400
...                                                     ...         ...
                                       481       1350520000  230.217633
                                       481       1350520000  230.217633
                                       481       1350520000  230.217633
                                       481       1350520000  230.217633
                                       481       1350520000  230.217633

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-11-20_17-46 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       481             230.0  R2_exit_interval
                                       481             230.0  R2_exit_interval
                                       481             230.0  R2_exit_interval
                                       481             230.0  R2_exit_interval
                                       481             230.0  R2_exit_interval

[16750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:26,569|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:45:26,581|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min:
2026-02-26 16:45:26,582|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:26,594|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:26,595|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:26,723|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:26,724|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:26,734|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:26,735|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:45:26,806|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:26,813|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0              1.0  0.0            0.0
                                       1              1.0  0.0            0.0
                                       2              1.0  0.0            0.0
                                       3              1.0  0.0            0.0
                                       4              1.0  0.0            0.0
...                                                   ...  ...            ...
                                       496           67.0  1.0            0.0
                                       497           67.0  1.0            0.0
                                       498           67.0  1.0            0.0
                                       499           67.0  1.0            0.0
                                       500           67.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0               0.0        0.0
                                       1               0.0        0.0
                                       2               0.0        0.0
                                       3               0.0        0.0
                                       4               0.0        0.0
...                                                    ...        ...
                                       496             0.0        0.0
                                       497             0.0        0.0
                                       498             0.0        0.0
                                       499             0.0        0.0
                                       500             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       496            cueZone_exit
                                       497       enter_reward1Zone
                                       498       enter_reward2Zone
                                       499        exit_reward1Zone
                                       500        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0            4720000 -118.841800
                                       1            5240000  -78.853135
                                       2            6520000   23.543375
                                       3            6880000   50.812613
                                       4            9760000  169.558450
...                                                     ...         ...
                                       496       1546640000   25.601170
                                       497       1546920000   51.552260
                                       498       1548680000  169.658700
                                       499       1547760000  111.060100
                                       500       1549560000  229.961633

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       496              25.0
                                       497              50.0
                                       498             170.0
                                       499             110.0
                                       500             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-21_17-22 0         (4520000.0, 4720000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       496                          NaN  ...
                                       497                          NaN  ...
                                       498                          NaN  ...
                                       499                          NaN  ...
                                       500                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4              (9360000.0, 10960000.0]
...                                                                       ...
                                       496                                NaN
                                       497                                NaN
                                       498       (1548280000.0, 1549880000.0]
                                       499                                NaN
                                       500                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       496                                                    None
                                       497                                                    None
                                       498                                                    None
                                       499                                                    None
                                       500                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       496                                NaN
                                       497                                NaN
                                       498                                NaN
                                       499       (1547360000.0, 1548960000.0]
                                       500                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       496                       None
                                       497                       None
                                       498                       None
                                       499                       None
                                       500                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       496                                NaN
                                       497                                NaN
                                       498                                NaN
                                       499                                NaN
                                       500       (1549160000.0, 1550760000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       496                       None
                                       497                       None
                                       498                       None
                                       499                       None
                                       500                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       496                              NaN
                                       497                              NaN
                                       498                              NaN
                                       499                              NaN
                                       500                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       496                                  None
                                       497                                  None
                                       498                                  None
                                       499                                  None
                                       500                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       496                              NaN
                                       497                              NaN
                                       498                              NaN
                                       499                              NaN
                                       500                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-21_17-22 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       496                                  None
                                       497                                  None
                                       498                                  None
                                       499                                  None
                                       500                                  None

[501 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-11-21_17-22
entry_id                                                 250
trial_id                                                33.0
cue                                                      2.0
trial_outcome                                           15.0
choice_R1                                                1.0
choice_R2                                                1.0
t0_event_name                               exit_reward2Zone
t0                                                 907320000
x_position                                         230.00715
x_alignment                                            230.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                                        NaN
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                                         NaN
R1_exit_interval_bins                                   None
R2_exit_interval                  (906920000.0, 908520000.0]
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46

2026-02-26 16:45:27,915|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0                      4520000
                                       0                      4560000
                                       0                      4600000
                                       0                      4640000
                                       0                      4680000
...                                                               ...
                                       500                 1550560000
                                       500                 1550600000
                                       500                 1550640000
                                       500                 1550680000
                                       500                 1550720000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0                    4560000
                                       0                    4600000
                                       0                    4640000
                                       0                    4680000
                                       0                    4720000
...                                                             ...
                                       500               1550600000
                                       500               1550640000
                                       500               1550680000
                                       500               1550720000
                                       500               1550760000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0           -0.246455     1.901233
                                       0            0.005480    -0.331370
                                       0           -0.356262    -0.309968
                                       0           -0.047149    -0.148848
                                       0           -0.231100     0.238972
...                                                      ...          ...
                                       500          0.003839     0.470813
                                       500          1.845076    -0.430176
                                       500         -0.024218    -0.108451
                                       500         -0.009611    -0.099819
                                       500         -0.024713    -0.182104

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0           -0.293587    -0.581745
                                       0            0.012426     0.356138
                                       0            0.283335    -0.373079
                                       0           -0.059278    -0.230065
                                       0           -0.355944     3.235419
...                                                      ...          ...
                                       500         -0.069030     0.150362
                                       500         -0.002350     0.206173
                                       500         -0.063439     0.067620
                                       500         -0.178324    -0.087556
                                       500         -0.091728     0.084355

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0           -0.726060    -0.749134
                                       0           -0.503886    -0.037943
                                       0           -0.100411    -0.897034
                                       0           -0.145836    -0.181274
                                       0           -0.340422     0.058465
...                                                      ...          ...
                                       500         -0.109869    -0.109639
                                       500         -0.647255    -0.539700
                                       500          0.034672    -0.015154
                                       500          0.262951    -0.454420
                                       500         -0.153547    -0.015973

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0            0.163686    -0.421749
                                       0           -0.245135    -0.177491
                                       0            0.050312    -0.546704
                                       0           -0.164150    -0.125608
                                       0           -0.785367    -0.315807
...                                                      ...          ...
                                       500          0.351046     0.003050
                                       500         -0.257641     5.286215
                                       500          0.205694    -0.086218
                                       500         -0.036905    -0.147035
                                       500          0.285777    -0.087723

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-11-21_17-22 1100        6         0         ...       1.0  0.0
                                       0         ...       1.0  0.0
                                       0         ...       1.0  0.0
                                       0         ...       1.0  0.0
                                       0         ...       1.0  0.0
...                                              ...       ...  ...
                                       500       ...      67.0  1.0
                                       500       ...      67.0  1.0
                                       500       ...      67.0  1.0
                                       500       ...      67.0  1.0
                                       500       ...      67.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
...                                                        ...        ...
                                       500                 0.0        0.0
                                       500                 0.0        0.0
                                       500                 0.0        0.0
                                       500                 0.0        0.0
                                       500                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
...                                                    ...               ...
                                       500             0.0  exit_reward2Zone
                                       500             0.0  exit_reward2Zone
                                       500             0.0  exit_reward2Zone
                                       500             0.0  exit_reward2Zone
                                       500             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0            4720000 -118.841800
                                       0            4720000 -118.841800
                                       0            4720000 -118.841800
                                       0            4720000 -118.841800
                                       0            4720000 -118.841800
...                                                     ...         ...
                                       500       1549560000  229.961633
                                       500       1549560000  229.961633
                                       500       1549560000  229.961633
                                       500       1549560000  229.961633
                                       500       1549560000  229.961633

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-11-21_17-22 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       500             230.0  R2_exit_interval
                                       500             230.0  R2_exit_interval
                                       500             230.0  R2_exit_interval
                                       500             230.0  R2_exit_interval
                                       500             230.0  R2_exit_interval

[16750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:29,236|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-26 16:45:29,253|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min:
2026-02-26 16:45:29,253|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:29,272|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:29,272|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:29,411|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:29,412|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:29,413|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:29,414|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-26 16:45:29,420|INFO|41770|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-26 16:45:29,420|WARNING|41770|analytics|_compute_sess_analytic
	Missing lower level analytic
2026-02-26 16:45:29,429|WARNING|41770|analytics|get_analytics
	Failed to compute EnsembleT0Projection for (1100, 6, '2024-11-22_16-01')
================================================================================

2026-02-26 16:45:29,430|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-26 16:45:29,440|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min:
2026-02-26 16:45:29,441|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:29,446|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:29,446|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:45:29,534|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:29,535|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:29,536|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:29,536|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
================================================================================

2026-02-26 16:45:29,607|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:29,614|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0              1.0  1.0           55.0
                                       1              1.0  1.0           55.0
                                       2              1.0  1.0           55.0
                                       3              1.0  1.0           55.0
                                       4              1.0  1.0           55.0
...                                                   ...  ...            ...
                                       397           55.0  1.0            0.0
                                       398           55.0  1.0            0.0
                                       399           55.0  1.0            0.0
                                       400           55.0  1.0            0.0
                                       401           55.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       397             0.0        0.0
                                       398             0.0        0.0
                                       399             0.0        0.0
                                       400             0.0        0.0
                                       401             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       397            cueZone_exit
                                       398       enter_reward1Zone
                                       399       enter_reward2Zone
                                       400        exit_reward1Zone
                                       401        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0            4400000 -118.880867
                                       1            4920000  -78.540623
                                       2            6040000   24.692160
                                       3            6440000   51.283950
                                       4           21920000  169.980950
...                                                     ...         ...
                                       397       1092440000   25.974330
                                       398       1092680000   48.444097
                                       399       1094160000  170.646033
                                       400       1093520000  110.874500
                                       401       1095520000  230.352550

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       397              25.0
                                       398              50.0
                                       399             170.0
                                       400             110.0
                                       401             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-25_16-25 0         (4200000.0, 4400000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       397                          NaN  ...
                                       398                          NaN  ...
                                       399                          NaN  ...
                                       400                          NaN  ...
                                       401                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (21520000.0, 23120000.0]
...                                                                       ...
                                       397                                NaN
                                       398                                NaN
                                       399       (1093760000.0, 1095360000.0]
                                       400                                NaN
                                       401                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       397                                                    None
                                       398                                                    None
                                       399                                                    None
                                       400                                                    None
                                       401                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       397                                NaN
                                       398                                NaN
                                       399                                NaN
                                       400       (1093120000.0, 1094720000.0]
                                       401                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       397                       None
                                       398                       None
                                       399                       None
                                       400                       None
                                       401                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       397                                NaN
                                       398                                NaN
                                       399                                NaN
                                       400                                NaN
                                       401       (1095120000.0, 1096720000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       397                       None
                                       398                       None
                                       399                       None
                                       400                       None
                                       401                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       397                              NaN
                                       398                              NaN
                                       399                              NaN
                                       400                              NaN
                                       401                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       397                                  None
                                       398                                  None
                                       399                                  None
                                       400                                  None
                                       401                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       397                              NaN
                                       398                              NaN
                                       399                              NaN
                                       400                              NaN
                                       401                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-25_16-25 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       397                                  None
                                       398                                  None
                                       399                                  None
                                       400                                  None
                                       401                                  None

[402 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-11-25_16-25
entry_id                                                 201
trial_id                                                27.0
cue                                                      2.0
trial_outcome                                           10.0
choice_R1                                                1.0
choice_R2                                                1.0
t0_event_name                               exit_reward2Zone
t0                                                 665480000
x_position                                          230.8231
x_alignment                                            230.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                                        NaN
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                                         NaN
R1_exit_interval_bins                                   None
R2_exit_interval                  (665080000.0, 666680000.0]
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22

2026-02-26 16:45:30,549|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0                      4200000
                                       0                      4240000
                                       0                      4280000
                                       0                      4320000
                                       0                      4360000
...                                                               ...
                                       401                 1096520000
                                       401                 1096560000
                                       401                 1096600000
                                       401                 1096640000
                                       401                 1096680000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0                    4240000
                                       0                    4280000
                                       0                    4320000
                                       0                    4360000
                                       0                    4400000
...                                                             ...
                                       401               1096560000
                                       401               1096600000
                                       401               1096640000
                                       401               1096680000
                                       401               1096720000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0            0.240734    -0.112506
                                       0           -0.071550     0.169509
                                       0           -0.104420    -0.221124
                                       0            0.149976    -0.373446
                                       0           -0.063985     0.523718
...                                                      ...          ...
                                       401         -0.080643    -0.036208
                                       401         -0.027797     0.089656
                                       401         -0.100053    -0.273558
                                       401         -0.034757    -0.096355
                                       401         -0.052976    -0.048943

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0            0.020958     0.737900
                                       0            0.204098     0.360820
                                       0            0.479059    -0.312126
                                       0           -0.048378    -0.111127
                                       0           -0.050359     0.281005
...                                                      ...          ...
                                       401         -0.100237    -0.084000
                                       401         -0.170773    -0.557472
                                       401         -0.134768    -0.204637
                                       401         -0.047007    -0.110209
                                       401         -0.089571     0.142845

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0            0.128841     1.964878
                                       0           -0.347945     0.487943
                                       0            2.974757    -0.356816
                                       0            0.267721     0.273335
                                       0           -0.380874     0.126452
...                                                      ...          ...
                                       401         -0.104628    -0.077610
                                       401         -0.101328     1.509581
                                       401          0.051586     0.102849
                                       401         -0.016673     0.579506
                                       401          0.010870    -0.458676

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0           -0.035008     0.089575
                                       0           -0.129750     0.002082
                                       0            0.254541     1.773894
                                       0           -0.060084     0.242920
                                       0           -0.158678    -0.119423
...                                                      ...          ...
                                       401          0.868466     0.172836
                                       401         -0.196634     0.121126
                                       401         -0.091151     0.262649
                                       401          0.211956     0.109409
                                       401         -0.024986    -0.013307

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-11-25_16-25 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       401       ...      55.0  1.0
                                       401       ...      55.0  1.0
                                       401       ...      55.0  1.0
                                       401       ...      55.0  1.0
                                       401       ...      55.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0                  55.0        1.0
                                       0                  55.0        1.0
                                       0                  55.0        1.0
                                       0                  55.0        1.0
                                       0                  55.0        1.0
...                                                        ...        ...
                                       401                 0.0        0.0
                                       401                 0.0        0.0
                                       401                 0.0        0.0
                                       401                 0.0        0.0
                                       401                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       401             0.0  exit_reward2Zone
                                       401             0.0  exit_reward2Zone
                                       401             0.0  exit_reward2Zone
                                       401             0.0  exit_reward2Zone
                                       401             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0            4400000 -118.880867
                                       0            4400000 -118.880867
                                       0            4400000 -118.880867
                                       0            4400000 -118.880867
                                       0            4400000 -118.880867
...                                                     ...         ...
                                       401       1095520000  230.352550
                                       401       1095520000  230.352550
                                       401       1095520000  230.352550
                                       401       1095520000  230.352550
                                       401       1095520000  230.352550

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-11-25_16-25 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       401             230.0  R2_exit_interval
                                       401             230.0  R2_exit_interval
                                       401             230.0  R2_exit_interval
                                       401             230.0  R2_exit_interval
                                       401             230.0  R2_exit_interval

[13750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:31,438|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:45:31,449|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min:
2026-02-26 16:45:31,449|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:31,461|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:31,462|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:31,559|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:31,560|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:31,561|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:31,561|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
================================================================================

2026-02-26 16:45:31,601|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:31,608|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0              1.0  2.0           23.0
                                       1              1.0  2.0           23.0
                                       2              1.0  2.0           23.0
                                       3              1.0  2.0           23.0
                                       4              1.0  2.0           23.0
...                                                   ...  ...            ...
                                       637           87.0  1.0            0.0
                                       638           87.0  1.0            0.0
                                       639           87.0  1.0            0.0
                                       640           87.0  1.0            0.0
                                       641           87.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       637             0.0        0.0
                                       638             0.0        0.0
                                       639             0.0        0.0
                                       640             0.0        0.0
                                       641             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       637            cueZone_exit
                                       638       enter_reward1Zone
                                       639       enter_reward2Zone
                                       640        exit_reward1Zone
                                       641        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0            4360000 -119.617450
                                       1            4800000  -81.703780
                                       2            6120000   24.961235
                                       3            6560000   50.122310
                                       4           12760000  170.537567
...                                                     ...         ...
                                       637       1523120000   25.974073
                                       638       1523400000   49.873020
                                       639       1525000000  169.555350
                                       640       1524240000  108.962450
                                       641       1526120000  231.345867

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       637              25.0
                                       638              50.0
                                       639             170.0
                                       640             110.0
                                       641             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-26_16-39 0         (4160000.0, 4360000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       637                          NaN  ...
                                       638                          NaN  ...
                                       639                          NaN  ...
                                       640                          NaN  ...
                                       641                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (12360000.0, 13960000.0]
...                                                                       ...
                                       637                                NaN
                                       638                                NaN
                                       639       (1524600000.0, 1526200000.0]
                                       640                                NaN
                                       641                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       637                                                    None
                                       638                                                    None
                                       639                                                    None
                                       640                                                    None
                                       641                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       637                                NaN
                                       638                                NaN
                                       639                                NaN
                                       640       (1523840000.0, 1525440000.0]
                                       641                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       637                       None
                                       638                       None
                                       639                       None
                                       640                       None
                                       641                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       637                                NaN
                                       638                                NaN
                                       639                                NaN
                                       640                                NaN
                                       641       (1525720000.0, 1527320000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       637                       None
                                       638                       None
                                       639                       None
                                       640                       None
                                       641                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       637                              NaN
                                       638                              NaN
                                       639                              NaN
                                       640                              NaN
                                       641                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       637                                  None
                                       638                                  None
                                       639                                  None
                                       640                                  None
                                       641                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       637                              NaN
                                       638                              NaN
                                       639                              NaN
                                       640                              NaN
                                       641                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-26_16-39 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       637                                  None
                                       638                                  None
                                       639                                  None
                                       640                                  None
                                       641                                  None

[642 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-11-26_16-39
entry_id                                                 321
trial_id                                                43.0
cue                                                      1.0
trial_outcome                                           11.0
choice_R1                                                1.0
choice_R2                                                1.0
t0_event_name                              enter_reward1Zone
t0                                                 810000000
x_position                                          49.45411
x_alignment                                             50.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                 (809600000.0, 811200000.0]
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                                         NaN
R1_exit_interval_bins                                   None
R2_exit_interval                                         NaN
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet
No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25

2026-02-26 16:45:33,477|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0                      4160000
                                       0                      4200000
                                       0                      4240000
                                       0                      4280000
                                       0                      4320000
...                                                               ...
                                       641                 1527120000
                                       641                 1527160000
                                       641                 1527200000
                                       641                 1527240000
                                       641                 1527280000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0                    4200000
                                       0                    4240000
                                       0                    4280000
                                       0                    4320000
                                       0                    4360000
...                                                             ...
                                       641               1527160000
                                       641               1527200000
                                       641               1527240000
                                       641               1527280000
                                       641               1527320000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0           -0.166996    -0.075138
                                       0           -0.083316     0.601711
                                       0           -0.059636     0.031031
                                       0           -0.183050    -0.256306
                                       0           -0.044630    -0.132832
...                                                      ...          ...
                                       641         -0.009938    -0.147526
                                       641         -0.140066    -0.414721
                                       641         -0.088216     0.287730
                                       641         -0.121526    -0.121789
                                       641          0.047221     0.188752

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0           -0.438168    -0.390345
                                       0            1.243159     2.273290
                                       0           -0.139320     0.175397
                                       0           -0.149596    -0.154969
                                       0            0.027769    -0.043591
...                                                      ...          ...
                                       641          0.143217    -0.142194
                                       641         -0.297092     0.412095
                                       641         -0.317496    -0.066090
                                       641          0.533125    -0.101440
                                       641          0.036020    -0.063520

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0           -0.495557    -0.457360
                                       0           -0.190172    -0.576208
                                       0           -0.246472     3.740980
                                       0            1.129698     2.309855
                                       0           -0.153933     1.057278
...                                                      ...          ...
                                       641         -0.112215     0.731516
                                       641         -0.304117     1.449121
                                       641         -0.354811     2.888295
                                       641          0.631138    -0.301439
                                       641         -0.011341     0.620178

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0           -0.340656    -0.664789
                                       0           -0.646848     0.358565
                                       0            0.098252    -0.050271
                                       0           -0.169792     1.410273
                                       0            0.013595    -0.104484
...                                                      ...          ...
                                       641          0.488379    -0.135770
                                       641          0.592175     0.061121
                                       641          0.333675    -0.011916
                                       641         -0.158520    -0.064671
                                       641         -0.483439    -0.017330

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-11-26_16-39 1100        6         0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
...                                              ...       ...  ...
                                       641       ...      87.0  1.0
                                       641       ...      87.0  1.0
                                       641       ...      87.0  1.0
                                       641       ...      87.0  1.0
                                       641       ...      87.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0                  23.0        1.0
                                       0                  23.0        1.0
                                       0                  23.0        1.0
                                       0                  23.0        1.0
                                       0                  23.0        1.0
...                                                        ...        ...
                                       641                 0.0        0.0
                                       641                 0.0        0.0
                                       641                 0.0        0.0
                                       641                 0.0        0.0
                                       641                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       641             0.0  exit_reward2Zone
                                       641             0.0  exit_reward2Zone
                                       641             0.0  exit_reward2Zone
                                       641             0.0  exit_reward2Zone
                                       641             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0            4360000 -119.617450
                                       0            4360000 -119.617450
                                       0            4360000 -119.617450
                                       0            4360000 -119.617450
                                       0            4360000 -119.617450
...                                                     ...         ...
                                       641       1526120000  231.345867
                                       641       1526120000  231.345867
                                       641       1526120000  231.345867
                                       641       1526120000  231.345867
                                       641       1526120000  231.345867

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-11-26_16-39 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       641             230.0  R2_exit_interval
                                       641             230.0  R2_exit_interval
                                       641             230.0  R2_exit_interval
                                       641             230.0  R2_exit_interval
                                       641             230.0  R2_exit_interval

[21750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:35,782|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-26 16:45:35,793|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min:
2026-02-26 16:45:35,794|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:35,823|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:35,823|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:45:36,076|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:36,076|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:36,077|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:36,078|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-26 16:45:36,078|INFO|41770|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-26 16:45:36,079|WARNING|41770|analytics|_compute_sess_analytic
	Missing lower level analytic
2026-02-26 16:45:36,088|WARNING|41770|analytics|get_analytics
	Failed to compute EnsembleT0Projection for (1100, 6, '2024-11-27_16-11')
================================================================================

2026-02-26 16:45:36,089|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:45:36,217|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:45:36,218|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:36,225|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:36,225|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:36,366|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:36,366|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:36,368|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:36,368|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:45:36,471|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:36,483|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0              1.0  1.0            2.0
                                       1              1.0  1.0            2.0
                                       2              1.0  1.0            2.0
                                       3              1.0  1.0            2.0
                                       4              1.0  1.0            2.0
...                                                   ...  ...            ...
                                       958          133.0  2.0            0.0
                                       959          133.0  2.0            0.0
                                       960          133.0  2.0            0.0
                                       961          133.0  2.0            0.0
                                       962          133.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       958             1.0        0.0
                                       959             1.0        0.0
                                       960             1.0        0.0
                                       961             1.0        0.0
                                       962             1.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       958            cueZone_exit
                                       959       enter_reward1Zone
                                       960       enter_reward2Zone
                                       961        exit_reward1Zone
                                       962        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0            4400000 -117.987567
                                       1            4840000  -78.983440
                                       2            6280000   24.433100
                                       3            6640000   50.250810
                                       4           12840000  170.008650
...                                                     ...         ...
                                       958       1831080000   24.543613
                                       959       1831880000   49.895123
                                       960       1841280000  169.162900
                                       961       1837520000  108.928550
                                       962       1842160000  230.152050

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       958              25.0
                                       959              50.0
                                       960             170.0
                                       961             110.0
                                       962             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-28_17-41 0         (4200000.0, 4400000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       958                          NaN  ...
                                       959                          NaN  ...
                                       960                          NaN  ...
                                       961                          NaN  ...
                                       962                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (12440000.0, 14040000.0]
...                                                                       ...
                                       958                                NaN
                                       959                                NaN
                                       960       (1840880000.0, 1842480000.0]
                                       961                                NaN
                                       962                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       958                                                    None
                                       959                                                    None
                                       960                                                    None
                                       961                                                    None
                                       962                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       958                                NaN
                                       959                                NaN
                                       960                                NaN
                                       961       (1837120000.0, 1838720000.0]
                                       962                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       958                       None
                                       959                       None
                                       960                       None
                                       961                       None
                                       962                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       958                                NaN
                                       959                                NaN
                                       960                                NaN
                                       961                                NaN
                                       962       (1841760000.0, 1843360000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       958                       None
                                       959                       None
                                       960                       None
                                       961                       None
                                       962                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       958                              NaN
                                       959                              NaN
                                       960                              NaN
                                       961                              NaN
                                       962                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       958                                  None
                                       959                                  None
                                       960                                  None
                                       961                                  None
                                       962                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       958                              NaN
                                       959                              NaN
                                       960                              NaN
                                       961                              NaN
                                       962                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-28_17-41 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       958                                  None
                                       959                                  None
                                       960                                  None
                                       961                                  None
                                       962                                  None

[963 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-11-28_17-41
entry_id                                                 481
trial_id                                                67.0
cue                                                      1.0
trial_outcome                                            3.0
choice_R1                                                1.0
choice_R2                                                0.0
t0_event_name                                  cueZone_entry
t0                                                 958520000
x_position                                        -78.833865
x_alignment                                            -80.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval               (958520000.0, 958720000.0]
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                                        NaN
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                                         NaN
R1_exit_interval_bins                                   None
R2_exit_interval                                         NaN
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39

2026-02-26 16:45:38,654|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0                      4200000
                                       0                      4240000
                                       0                      4280000
                                       0                      4320000
                                       0                      4360000
...                                                               ...
                                       962                 1843160000
                                       962                 1843200000
                                       962                 1843240000
                                       962                 1843280000
                                       962                 1843320000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0                    4240000
                                       0                    4280000
                                       0                    4320000
                                       0                    4360000
                                       0                    4400000
...                                                             ...
                                       962               1843200000
                                       962               1843240000
                                       962               1843280000
                                       962               1843320000
                                       962               1843360000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0           -0.177498    -0.280760
                                       0           -0.185443     2.604363
                                       0            0.139530     0.563665
                                       0           -0.011884    -0.255328
                                       0           -0.060928    -0.157367
...                                                      ...          ...
                                       962         -0.096046     0.933526
                                       962          0.656684    -0.271642
                                       962         -0.097602    -0.672788
                                       962         -0.035866    -0.126916
                                       962         -0.068338     0.051097

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0           -0.599726    -0.002228
                                       0            0.939250    -0.123112
                                       0           -0.155556     0.471849
                                       0            0.870300    -0.169818
                                       0           -0.154801    -0.170907
...                                                      ...          ...
                                       962          0.264633    -0.244077
                                       962         -0.400222    -0.892225
                                       962          0.820247    -0.075025
                                       962          0.162414     0.224066
                                       962         -0.197084     0.015208

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0            1.309655    -0.759188
                                       0           -0.271384    -0.504413
                                       0            0.673771     0.799318
                                       0           -0.189786    -0.470946
                                       0           -0.020649     1.841881
...                                                      ...          ...
                                       962         -0.309879     2.646217
                                       962         -0.123049    -0.323375
                                       962          0.803688    -0.704901
                                       962         -0.176378    -0.372226
                                       962         -0.158788     2.202127

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0            0.039899    -0.122283
                                       0           -0.690396     2.294336
                                       0           -0.261823    -1.979289
                                       0           -0.594742     0.403336
                                       0            0.093123    -0.124850
...                                                      ...          ...
                                       962         -0.195194    -0.204360
                                       962         -0.206171    -0.191821
                                       962          1.219688    -0.346742
                                       962         -0.297181    -0.102890
                                       962          0.377795    -0.067056

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-11-28_17-41 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       962       ...     133.0  2.0
                                       962       ...     133.0  2.0
                                       962       ...     133.0  2.0
                                       962       ...     133.0  2.0
                                       962       ...     133.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
...                                                        ...        ...
                                       962                 0.0        1.0
                                       962                 0.0        1.0
                                       962                 0.0        1.0
                                       962                 0.0        1.0
                                       962                 0.0        1.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       962             0.0  exit_reward2Zone
                                       962             0.0  exit_reward2Zone
                                       962             0.0  exit_reward2Zone
                                       962             0.0  exit_reward2Zone
                                       962             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0            4400000 -117.987567
                                       0            4400000 -117.987567
                                       0            4400000 -117.987567
                                       0            4400000 -117.987567
                                       0            4400000 -117.987567
...                                                     ...         ...
                                       962       1842160000  230.152050
                                       962       1842160000  230.152050
                                       962       1842160000  230.152050
                                       962       1842160000  230.152050
                                       962       1842160000  230.152050

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-11-28_17-41 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       962             230.0  R2_exit_interval
                                       962             230.0  R2_exit_interval
                                       962             230.0  R2_exit_interval
                                       962             230.0  R2_exit_interval
                                       962             230.0  R2_exit_interval

[33250 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:40,896|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-26 16:45:40,943|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min:
2026-02-26 16:45:40,946|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:40,955|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:40,956|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:41,052|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:41,053|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:41,054|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:41,055|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
================================================================================

2026-02-26 16:45:41,100|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:41,107|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0              1.0  1.0            1.0
                                       1              1.0  1.0            1.0
                                       2              1.0  1.0            1.0
                                       3              1.0  1.0            1.0
                                       4              1.0  1.0            1.0
...                                                   ...  ...            ...
                                       755          105.0  1.0            1.0
                                       756          105.0  1.0            1.0
                                       757          105.0  1.0            1.0
                                       758          105.0  1.0            1.0
                                       759          105.0  1.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       755             1.0        0.0
                                       756             1.0        0.0
                                       757             1.0        0.0
                                       758             1.0        0.0
                                       759             1.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       755       enter_reward1Zone
                                       756       enter_reward2Zone
                                       757        exit_reward1Zone
                                       758        exit_reward2Zone
                                       759           reward1_sound

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0            4640000 -120.825367
                                       1            5400000  -79.187750
                                       2            9080000   23.957657
                                       3           10600000   50.056520
                                       4           18440000  170.172950
...                                                     ...         ...
                                       755       1704320000   50.319170
                                       756       1709840000  168.239000
                                       757       1707920000  109.913367
                                       758       1710560000  229.463067
                                       759       1704720000   51.969627

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       755              50.0
                                       756             170.0
                                       757             110.0
                                       758             230.0
                                       759               NaN

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-12-02_16-09 0         (4440000.0, 4640000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       755                          NaN  ...
                                       756                          NaN  ...
                                       757                          NaN  ...
                                       758                          NaN  ...
                                       759                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (18040000.0, 19640000.0]
...                                                                       ...
                                       755                                NaN
                                       756       (1709440000.0, 1711040000.0]
                                       757                                NaN
                                       758                                NaN
                                       759                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       755                                                    None
                                       756                                                    None
                                       757                                                    None
                                       758                                                    None
                                       759                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       755                                NaN
                                       756                                NaN
                                       757       (1707520000.0, 1709120000.0]
                                       758                                NaN
                                       759                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       755                       None
                                       756                       None
                                       757                       None
                                       758                       None
                                       759                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       755                                NaN
                                       756                                NaN
                                       757                                NaN
                                       758       (1710160000.0, 1711760000.0]
                                       759                                NaN

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       755                       None
                                       756                       None
                                       757                       None
                                       758                       None
                                       759                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       755                              NaN
                                       756                              NaN
                                       757                              NaN
                                       758                              NaN
                                       759                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       755                                  None
                                       756                                  None
                                       757                                  None
                                       758                                  None
                                       759                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       755                              NaN
                                       756                              NaN
                                       757                              NaN
                                       758                              NaN
                                       759                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-02_16-09 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       755                                  None
                                       756                                  None
                                       757                                  None
                                       758                                  None
                                       759                                  None

[760 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2024-12-02_16-09
entry_id                                                   380
trial_id                                                  53.0
cue                                                        1.0
trial_outcome                                              3.0
choice_R1                                                  1.0
choice_R2                                                  0.0
t0_event_name                                     cueZone_exit
t0                                                  1029400000
x_position                                           24.617375
x_alignment                                               25.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                 (1029000000.0, 1030600000.0]
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet
No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21

2026-02-26 16:45:42,646|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0                      4440000
                                       0                      4480000
                                       0                      4520000
                                       0                      4560000
                                       0                      4600000
...                                                               ...
                                       758                 1711560000
                                       758                 1711600000
                                       758                 1711640000
                                       758                 1711680000
                                       758                 1711720000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0                    4480000
                                       0                    4520000
                                       0                    4560000
                                       0                    4600000
                                       0                    4640000
...                                                             ...
                                       758               1711600000
                                       758               1711640000
                                       758               1711680000
                                       758               1711720000
                                       758               1711760000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0            0.287292    -0.177015
                                       0           -0.071569    -0.208628
                                       0           -0.061140    -0.132438
                                       0            0.034760    -0.370913
                                       0           -0.124416     0.106435
...                                                      ...          ...
                                       758          1.102977     0.503571
                                       758         -0.083274    -0.282632
                                       758         -0.190189     0.039698
                                       758          0.107014    -0.080730
                                       758          0.201468     0.990140

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0           -0.231960    -0.389901
                                       0            1.093825     0.330148
                                       0           -0.072651     0.087714
                                       0            1.631410    -0.113878
                                       0            2.041249    -0.245981
...                                                      ...          ...
                                       758          0.919090    -0.243451
                                       758         -0.183494    -0.200285
                                       758         -0.329436     0.821401
                                       758         -0.094936    -0.013243
                                       758         -0.017864     0.317208

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0            0.598796    -0.337921
                                       0           -0.467068     1.787402
                                       0           -0.137617     1.880923
                                       0           -0.193205    -0.149968
                                       0           -0.128405    -0.743356
...                                                      ...          ...
                                       758          0.052003     1.700485
                                       758         -0.215317     0.446880
                                       758         -0.245070     0.374232
                                       758         -0.129509    -0.289887
                                       758          1.748045     0.214102

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0            0.186356    -0.078047
                                       0            1.276047    -0.111938
                                       0            0.364511    -0.071321
                                       0           -0.555078     0.306528
                                       0            0.044423     0.523481
...                                                      ...          ...
                                       758         -0.011898    -0.242022
                                       758         -0.029926     0.972220
                                       758         -0.093938    -0.110672
                                       758          0.008504     0.091883
                                       758          0.125963     0.074629

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-12-02_16-09 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       758       ...     105.0  1.0
                                       758       ...     105.0  1.0
                                       758       ...     105.0  1.0
                                       758       ...     105.0  1.0
                                       758       ...     105.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
...                                                        ...        ...
                                       758                 1.0        1.0
                                       758                 1.0        1.0
                                       758                 1.0        1.0
                                       758                 1.0        1.0
                                       758                 1.0        1.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       758             0.0  exit_reward2Zone
                                       758             0.0  exit_reward2Zone
                                       758             0.0  exit_reward2Zone
                                       758             0.0  exit_reward2Zone
                                       758             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0            4640000 -120.825367
                                       0            4640000 -120.825367
                                       0            4640000 -120.825367
                                       0            4640000 -120.825367
                                       0            4640000 -120.825367
...                                                     ...         ...
                                       758       1710560000  229.463067
                                       758       1710560000  229.463067
                                       758       1710560000  229.463067
                                       758       1710560000  229.463067
                                       758       1710560000  229.463067

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-12-02_16-09 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       758             230.0  R2_exit_interval
                                       758             230.0  R2_exit_interval
                                       758             230.0  R2_exit_interval
                                       758             230.0  R2_exit_interval
                                       758             230.0  R2_exit_interval

[26250 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:44,218|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:45:44,232|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:45:44,233|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:44,246|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:44,248|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:44,362|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:44,362|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:44,363|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:44,364|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
================================================================================

2026-02-26 16:45:44,413|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:44,420|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0              1.0  1.0            2.0
                                       1              1.0  1.0            2.0
                                       2              1.0  1.0            2.0
                                       3              1.0  1.0            2.0
                                       4              1.0  1.0            2.0
...                                                   ...  ...            ...
                                       758          104.0  2.0            0.0
                                       759          104.0  2.0            0.0
                                       760          104.0  2.0            0.0
                                       761          104.0  2.0            0.0
                                       762          104.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       758             1.0        0.0
                                       759             1.0        0.0
                                       760             1.0        0.0
                                       761             1.0        0.0
                                       762             1.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       758            cueZone_exit
                                       759       enter_reward1Zone
                                       760       enter_reward2Zone
                                       761        exit_reward1Zone
                                       762        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0            4320000 -120.393050
                                       1            4960000  -80.351963
                                       2            9280000   24.748440
                                       3           11320000   49.885355
                                       4           26960000  170.437900
...                                                     ...         ...
                                       758       1793160000   25.536147
                                       759       1793560000   49.574383
                                       760       1800720000  169.774300
                                       761       1799880000  110.327900
                                       762       1801440000  230.182133

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       758              25.0
                                       759              50.0
                                       760             170.0
                                       761             110.0
                                       762             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-12-03_16-23 0         (4120000.0, 4320000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       758                          NaN  ...
                                       759                          NaN  ...
                                       760                          NaN  ...
                                       761                          NaN  ...
                                       762                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (26560000.0, 28160000.0]
...                                                                       ...
                                       758                                NaN
                                       759                                NaN
                                       760       (1800320000.0, 1801920000.0]
                                       761                                NaN
                                       762                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       758                                                    None
                                       759                                                    None
                                       760                                                    None
                                       761                                                    None
                                       762                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       758                                NaN
                                       759                                NaN
                                       760                                NaN
                                       761       (1799480000.0, 1801080000.0]
                                       762                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       758                       None
                                       759                       None
                                       760                       None
                                       761                       None
                                       762                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       758                                NaN
                                       759                                NaN
                                       760                                NaN
                                       761                                NaN
                                       762       (1801040000.0, 1802640000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       758                       None
                                       759                       None
                                       760                       None
                                       761                       None
                                       762                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       758                              NaN
                                       759                              NaN
                                       760                              NaN
                                       761                              NaN
                                       762                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       758                                  None
                                       759                                  None
                                       760                                  None
                                       761                                  None
                                       762                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       758                              NaN
                                       759                              NaN
                                       760                              NaN
                                       761                              NaN
                                       762                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-03_16-23 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       758                                  None
                                       759                                  None
                                       760                                  None
                                       761                                  None
                                       762                                  None

[763 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2024-12-03_16-23
entry_id                                                   381
trial_id                                                  52.0
cue                                                        2.0
trial_outcome                                              0.0
choice_R1                                                  0.0
choice_R2                                                  0.0
t0_event_name                                  cueZone_visible
t0                                                  1054840000
x_position                                           -120.1872
x_alignment                                             -120.0
pre_cue_interval                  (1054640000.0, 1054840000.0]
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                (1054720000.0, 1056320000.0]
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet
No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

2026-02-26 16:45:46,025|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0                      4120000
                                       0                      4160000
                                       0                      4200000
                                       0                      4240000
                                       0                      4280000
...                                                               ...
                                       762                 1802440000
                                       762                 1802480000
                                       762                 1802520000
                                       762                 1802560000
                                       762                 1802600000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0                    4160000
                                       0                    4200000
                                       0                    4240000
                                       0                    4280000
                                       0                    4320000
...                                                             ...
                                       762               1802480000
                                       762               1802520000
                                       762               1802560000
                                       762               1802600000
                                       762               1802640000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0           -0.103634    -0.366408
                                       0            0.014386     1.768543
                                       0           -0.012780     0.123472
                                       0            0.116447     0.046390
                                       0           -0.078393    -0.196187
...                                                      ...          ...
                                       762          0.108745     0.348894
                                       762         -0.096185     0.469117
                                       762          0.634640    -0.414811
                                       762          0.372932    -0.427500
                                       762         -0.191276     1.069014

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0           -0.279622    -0.248433
                                       0           -0.035731     0.642021
                                       0            0.068408    -0.139626
                                       0           -0.249898     0.330039
                                       0            0.417861    -0.179529
...                                                      ...          ...
                                       762          2.253204    -0.165511
                                       762         -0.615983    -0.415624
                                       762          0.755648    -0.204682
                                       762         -0.228003    -0.352610
                                       762         -0.099817    -0.351332

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0            0.100535     0.362919
                                       0            0.113365    -0.269730
                                       0           -0.060997    -0.015757
                                       0           -0.534361     0.166649
                                       0           -0.129485     0.885873
...                                                      ...          ...
                                       762         -0.219935    -0.522269
                                       762          1.479417     0.249968
                                       762         -3.310273    -0.274099
                                       762         -0.567281    -0.143980
                                       762         -0.015748    -0.715728

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0           -0.191161    -0.298067
                                       0           -0.235809    -0.091610
                                       0            0.585177    -0.243652
                                       0            0.028177    -0.143148
                                       0           -0.078133    -0.143350
...                                                      ...          ...
                                       762         -0.040165    -0.342563
                                       762         -0.104299    -0.296051
                                       762         -1.291997    -0.890080
                                       762         -0.269309    -0.221112
                                       762          1.135497     0.417467

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-12-03_16-23 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       762       ...     104.0  2.0
                                       762       ...     104.0  2.0
                                       762       ...     104.0  2.0
                                       762       ...     104.0  2.0
                                       762       ...     104.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
...                                                        ...        ...
                                       762                 0.0        1.0
                                       762                 0.0        1.0
                                       762                 0.0        1.0
                                       762                 0.0        1.0
                                       762                 0.0        1.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       762             0.0  exit_reward2Zone
                                       762             0.0  exit_reward2Zone
                                       762             0.0  exit_reward2Zone
                                       762             0.0  exit_reward2Zone
                                       762             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0            4320000 -120.393050
                                       0            4320000 -120.393050
                                       0            4320000 -120.393050
                                       0            4320000 -120.393050
                                       0            4320000 -120.393050
...                                                     ...         ...
                                       762       1801440000  230.182133
                                       762       1801440000  230.182133
                                       762       1801440000  230.182133
                                       762       1801440000  230.182133
                                       762       1801440000  230.182133

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-12-03_16-23 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       762             230.0  R2_exit_interval
                                       762             230.0  R2_exit_interval
                                       762             230.0  R2_exit_interval
                                       762             230.0  R2_exit_interval
                                       762             230.0  R2_exit_interval

[26000 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object
================================================================================

2026-02-26 16:45:48,355|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:45:48,369|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:45:48,370|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:48,384|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:48,384|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:48,531|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:48,532|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:48,533|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:48,534|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:45:48,605|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:48,626|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0              1.0  1.0            2.0
                                       1              1.0  1.0            2.0
                                       2              1.0  1.0            2.0
                                       3              1.0  1.0            2.0
                                       4              1.0  1.0            2.0
...                                                   ...  ...            ...
                                       878          120.0  2.0            0.0
                                       879          120.0  2.0            0.0
                                       880          120.0  2.0            0.0
                                       881          120.0  2.0            0.0
                                       882          120.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0               1.0        0.0
                                       1               1.0        0.0
                                       2               1.0        0.0
                                       3               1.0        0.0
                                       4               1.0        0.0
...                                                    ...        ...
                                       878             0.0        0.0
                                       879             0.0        0.0
                                       880             0.0        0.0
                                       881             0.0        0.0
                                       882             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       878            cueZone_exit
                                       879       enter_reward1Zone
                                       880       enter_reward2Zone
                                       881        exit_reward1Zone
                                       882        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0            4280000 -120.782700
                                       1            4840000  -79.537015
                                       2            8080000   26.441303
                                       3            8600000   49.595973
                                       4           21880000  170.270050
...                                                     ...         ...
                                       878       1826000000   23.917305
                                       879       1826360000   50.967327
                                       880       1828200000  169.351000
                                       881       1827160000  108.596500
                                       882       1829040000  229.501133

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       878              25.0
                                       879              50.0
                                       880             170.0
                                       881             110.0
                                       882             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-12-04_18-06 0         (4080000.0, 4280000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       878                          NaN  ...
                                       879                          NaN  ...
                                       880                          NaN  ...
                                       881                          NaN  ...
                                       882                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (21480000.0, 23080000.0]
...                                                                       ...
                                       878                                NaN
                                       879                                NaN
                                       880       (1827800000.0, 1829400000.0]
                                       881                                NaN
                                       882                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       878                                                    None
                                       879                                                    None
                                       880                                                    None
                                       881                                                    None
                                       882                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       878                                NaN
                                       879                                NaN
                                       880                                NaN
                                       881       (1826760000.0, 1828360000.0]
                                       882                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       878                       None
                                       879                       None
                                       880                       None
                                       881                       None
                                       882                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       878                                NaN
                                       879                                NaN
                                       880                                NaN
                                       881                                NaN
                                       882       (1828640000.0, 1830240000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       878                       None
                                       879                       None
                                       880                       None
                                       881                       None
                                       882                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       878                              NaN
                                       879                              NaN
                                       880                              NaN
                                       881                              NaN
                                       882                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       878                                  None
                                       879                                  None
                                       880                                  None
                                       881                                  None
                                       882                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       878                              NaN
                                       879                              NaN
                                       880                              NaN
                                       881                              NaN
                                       882                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-04_18-06 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       878                                  None
                                       879                                  None
                                       880                                  None
                                       881                                  None
                                       882                                  None

[883 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2024-12-04_18-06
entry_id                                                   441
trial_id                                                  60.0
cue                                                        1.0
trial_outcome                                              3.0
choice_R1                                                  1.0
choice_R2                                                  0.0
t0_event_name                                enter_reward1Zone
t0                                                  1061520000
x_position                                            50.34179
x_alignment                                               50.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                 (1061120000.0, 1062720000.0]
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23

2026-02-26 16:45:50,443|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0                      4080000
                                       0                      4120000
                                       0                      4160000
                                       0                      4200000
                                       0                      4240000
...                                                               ...
                                       882                 1830040000
                                       882                 1830080000
                                       882                 1830120000
                                       882                 1830160000
                                       882                 1830200000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0                    4120000
                                       0                    4160000
                                       0                    4200000
                                       0                    4240000
                                       0                    4280000
...                                                             ...
                                       882               1830080000
                                       882               1830120000
                                       882               1830160000
                                       882               1830200000
                                       882               1830240000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0           -0.055265    -0.379721
                                       0           -0.100587     0.074767
                                       0            0.309761     0.395211
                                       0            0.432601     0.918565
                                       0           -0.105364     0.535657
...                                                      ...          ...
                                       882         -0.231495    -0.544992
                                       882         -1.057499     3.800094
                                       882         -0.404378    -0.400934
                                       882         -0.195248     3.247372
                                       882         -0.061603     0.342188

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0           -0.249591     0.808688
                                       0            0.496709    -0.159640
                                       0           -0.325072     0.495036
                                       0            0.642870     0.220930
                                       0            0.145848    -0.438564
...                                                      ...          ...
                                       882          0.867373    -0.163634
                                       882          2.151588     2.299055
                                       882          0.247281     1.316506
                                       882         -0.270080    -0.369162
                                       882         -0.547333    -0.152804

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0           -0.338724    -0.463355
                                       0           -0.146610     0.216350
                                       0           -0.113152     0.349189
                                       0           -0.032645    -0.646851
                                       0           -0.174041     0.905285
...                                                      ...          ...
                                       882          0.050545     0.151015
                                       882         -0.214599     5.073962
                                       882         -0.228395    -0.761063
                                       882         -0.138961    -0.642967
                                       882         -0.816005    -1.199141

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0           -0.033162     1.054568
                                       0            0.267432    -0.237587
                                       0            0.320366     0.097552
                                       0            0.242843     2.366780
                                       0           -0.185021    -0.139399
...                                                      ...          ...
                                       882         -0.145407     0.574115
                                       882         -0.820449     0.016044
                                       882         -0.562820    -1.319416
                                       882         -0.235027     0.882110
                                       882          3.045196    -1.104538

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-12-04_18-06 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       882       ...     120.0  2.0
                                       882       ...     120.0  2.0
                                       882       ...     120.0  2.0
                                       882       ...     120.0  2.0
                                       882       ...     120.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
...                                                        ...        ...
                                       882                 0.0        0.0
                                       882                 0.0        0.0
                                       882                 0.0        0.0
                                       882                 0.0        0.0
                                       882                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
...                                                    ...               ...
                                       882             0.0  exit_reward2Zone
                                       882             0.0  exit_reward2Zone
                                       882             0.0  exit_reward2Zone
                                       882             0.0  exit_reward2Zone
                                       882             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0            4280000 -120.782700
                                       0            4280000 -120.782700
                                       0            4280000 -120.782700
                                       0            4280000 -120.782700
                                       0            4280000 -120.782700
...                                                     ...         ...
                                       882       1829040000  229.501133
                                       882       1829040000  229.501133
                                       882       1829040000  229.501133
                                       882       1829040000  229.501133
                                       882       1829040000  229.501133

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-12-04_18-06 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       882             230.0  R2_exit_interval
                                       882             230.0  R2_exit_interval
                                       882             230.0  R2_exit_interval
                                       882             230.0  R2_exit_interval
                                       882             230.0  R2_exit_interval

[30000 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:52,151|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-26 16:45:52,163|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min:
2026-02-26 16:45:52,163|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:52,176|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:52,179|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:52,362|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:52,363|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:52,364|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:52,364|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:45:52,423|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:52,429|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0              1.0  1.0            2.0
                                       1              1.0  1.0            2.0
                                       2              1.0  1.0            2.0
                                       3              1.0  1.0            2.0
                                       4              1.0  1.0            2.0
...                                                   ...  ...            ...
                                       696           95.0  1.0            0.0
                                       697           95.0  1.0            0.0
                                       698           95.0  1.0            0.0
                                       699           95.0  1.0            0.0
                                       700           95.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       696             0.0        0.0
                                       697             0.0        0.0
                                       698             0.0        0.0
                                       699             0.0        0.0
                                       700             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       696            cueZone_exit
                                       697       enter_reward1Zone
                                       698       enter_reward2Zone
                                       699        exit_reward1Zone
                                       700        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0            4520000 -119.878800
                                       1            5000000  -80.186457
                                       2            6880000   25.101303
                                       3            7320000   50.128225
                                       4           21920000  169.708800
...                                                     ...         ...
                                       696       1533280000   23.312070
                                       697       1533680000   50.272400
                                       698       1535360000  170.205567
                                       699       1534400000  111.337150
                                       700       1536120000  229.209900

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       696              25.0
                                       697              50.0
                                       698             170.0
                                       699             110.0
                                       700             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-12-06_16-49 0         (4320000.0, 4520000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       696                          NaN  ...
                                       697                          NaN  ...
                                       698                          NaN  ...
                                       699                          NaN  ...
                                       700                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (21520000.0, 23120000.0]
...                                                                       ...
                                       696                                NaN
                                       697                                NaN
                                       698       (1534960000.0, 1536560000.0]
                                       699                                NaN
                                       700                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       696                                                    None
                                       697                                                    None
                                       698                                                    None
                                       699                                                    None
                                       700                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       696                                NaN
                                       697                                NaN
                                       698                                NaN
                                       699       (1534000000.0, 1535600000.0]
                                       700                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       696                       None
                                       697                       None
                                       698                       None
                                       699                       None
                                       700                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       696                                NaN
                                       697                                NaN
                                       698                                NaN
                                       699                                NaN
                                       700       (1535720000.0, 1537320000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       696                       None
                                       697                       None
                                       698                       None
                                       699                       None
                                       700                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       696                              NaN
                                       697                              NaN
                                       698                              NaN
                                       699                              NaN
                                       700                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       696                                  None
                                       697                                  None
                                       698                                  None
                                       699                                  None
                                       700                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       696                              NaN
                                       697                              NaN
                                       698                              NaN
                                       699                              NaN
                                       700                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-06_16-49 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       696                                  None
                                       697                                  None
                                       698                                  None
                                       699                                  None
                                       700                                  None

[701 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-12-06_16-49
entry_id                                                 350
trial_id                                                48.0
cue                                                      2.0
trial_outcome                                            0.0
choice_R1                                                0.0
choice_R2                                                0.0
t0_event_name                               exit_reward2Zone
t0                                                 841960000
x_position                                          229.1513
x_alignment                                            230.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                                        NaN
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                                         NaN
R1_exit_interval_bins                                   None
R2_exit_interval                  (841560000.0, 843160000.0]
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06

2026-02-26 16:45:53,805|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0                      4320000
                                       0                      4360000
                                       0                      4400000
                                       0                      4440000
                                       0                      4480000
...                                                               ...
                                       700                 1537120000
                                       700                 1537160000
                                       700                 1537200000
                                       700                 1537240000
                                       700                 1537280000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0                    4360000
                                       0                    4400000
                                       0                    4440000
                                       0                    4480000
                                       0                    4520000
...                                                             ...
                                       700               1537160000
                                       700               1537200000
                                       700               1537240000
                                       700               1537280000
                                       700               1537320000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0            0.112863    -0.000738
                                       0            0.119913     1.153704
                                       0           -0.264006    -0.468610
                                       0            0.143101    -0.392267
                                       0           -0.108822    -0.168603
...                                                      ...          ...
                                       700         -0.383368     0.065804
                                       700          0.121967     0.304168
                                       700          0.344175     0.192299
                                       700         -0.537795     8.035264
                                       700         -0.170800    -0.539644

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0           -0.133982    -0.164358
                                       0           -0.191495    -0.363949
                                       0            0.620014    -0.192778
                                       0            0.168234    -0.818135
                                       0            0.467670    -0.082947
...                                                      ...          ...
                                       700         -0.360687    -0.709536
                                       700         -0.182804    -0.185166
                                       700          0.661322     0.341165
                                       700         -0.551580     0.335940
                                       700          0.335947     3.029221

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0           -0.032537     2.038323
                                       0           -0.263091    -0.112862
                                       0            0.441360     2.110797
                                       0           -0.539547    -0.340404
                                       0            0.146848     0.879400
...                                                      ...          ...
                                       700         -0.901891    -0.424224
                                       700          1.039261    -0.218724
                                       700         -0.516543    -0.193519
                                       700          0.072928    -1.100893
                                       700         -0.176347    -1.883129

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0           -0.102216    -0.018063
                                       0           -0.739961    -0.158867
                                       0           -0.077936    -0.209933
                                       0           -0.328967    -0.106258
                                       0           -0.387090    -0.138043
...                                                      ...          ...
                                       700         -0.545413    -0.919100
                                       700         -0.146913    -0.365746
                                       700         -0.608702     1.220843
                                       700         -1.011171     0.772518
                                       700          1.722133    -0.631228

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-12-06_16-49 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       700       ...      95.0  1.0
                                       700       ...      95.0  1.0
                                       700       ...      95.0  1.0
                                       700       ...      95.0  1.0
                                       700       ...      95.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
...                                                        ...        ...
                                       700                 0.0        0.0
                                       700                 0.0        0.0
                                       700                 0.0        0.0
                                       700                 0.0        0.0
                                       700                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       700             0.0  exit_reward2Zone
                                       700             0.0  exit_reward2Zone
                                       700             0.0  exit_reward2Zone
                                       700             0.0  exit_reward2Zone
                                       700             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0            4520000   -119.8788
                                       0            4520000   -119.8788
                                       0            4520000   -119.8788
                                       0            4520000   -119.8788
                                       0            4520000   -119.8788
...                                                     ...         ...
                                       700       1536120000    229.2099
                                       700       1536120000    229.2099
                                       700       1536120000    229.2099
                                       700       1536120000    229.2099
                                       700       1536120000    229.2099

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-12-06_16-49 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       700             230.0  R2_exit_interval
                                       700             230.0  R2_exit_interval
                                       700             230.0  R2_exit_interval
                                       700             230.0  R2_exit_interval
                                       700             230.0  R2_exit_interval

[23750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:55,382|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-26 16:45:55,396|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min:
2026-02-26 16:45:55,396|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:55,409|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:55,409|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:55,513|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:55,513|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:55,515|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:55,515|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
================================================================================

2026-02-26 16:45:55,586|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:55,592|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0              1.0  1.0            3.0
                                       1              1.0  1.0            3.0
                                       2              1.0  1.0            3.0
                                       3              1.0  1.0            3.0
                                       4              1.0  1.0            3.0
...                                                   ...  ...            ...
                                       613           83.0  2.0            0.0
                                       614           83.0  2.0            0.0
                                       615           83.0  2.0            0.0
                                       616           83.0  2.0            0.0
                                       617           83.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       613             0.0        0.0
                                       614             0.0        0.0
                                       615             0.0        0.0
                                       616             0.0        0.0
                                       617             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       613            cueZone_exit
                                       614       enter_reward1Zone
                                       615       enter_reward2Zone
                                       616        exit_reward1Zone
                                       617        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0            7840000 -119.689950
                                       1            8360000  -80.908623
                                       2           10880000   25.251135
                                       3           12440000   49.931615
                                       4           31320000  169.937750
...                                                     ...         ...
                                       613       1563480000   23.442365
                                       614       1563760000   50.623463
                                       615       1565040000  169.693600
                                       616       1564400000  110.322500
                                       617       1565960000  228.874000

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       613              25.0
                                       614              50.0
                                       615             170.0
                                       616             110.0
                                       617             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-12-09_17-45 0         (7640000.0, 7840000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       613                          NaN  ...
                                       614                          NaN  ...
                                       615                          NaN  ...
                                       616                          NaN  ...
                                       617                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (30920000.0, 32520000.0]
...                                                                       ...
                                       613                                NaN
                                       614                                NaN
                                       615       (1564640000.0, 1566240000.0]
                                       616                                NaN
                                       617                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       613                                                    None
                                       614                                                    None
                                       615                                                    None
                                       616                                                    None
                                       617                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       613                                NaN
                                       614                                NaN
                                       615                                NaN
                                       616       (1564000000.0, 1565600000.0]
                                       617                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       613                       None
                                       614                       None
                                       615                       None
                                       616                       None
                                       617                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       613                                NaN
                                       614                                NaN
                                       615                                NaN
                                       616                                NaN
                                       617       (1565560000.0, 1567160000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       613                       None
                                       614                       None
                                       615                       None
                                       616                       None
                                       617                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       613                              NaN
                                       614                              NaN
                                       615                              NaN
                                       616                              NaN
                                       617                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       613                                  None
                                       614                                  None
                                       615                                  None
                                       616                                  None
                                       617                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       613                              NaN
                                       614                              NaN
                                       615                              NaN
                                       616                              NaN
                                       617                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-09_17-45 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       613                                  None
                                       614                                  None
                                       615                                  None
                                       616                                  None
                                       617                                  None

[618 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-12-09_17-45
entry_id                                                 309
trial_id                                                42.0
cue                                                      1.0
trial_outcome                                            2.0
choice_R1                                                1.0
choice_R2                                                0.0
t0_event_name                               exit_reward1Zone
t0                                                 826840000
x_position                                         110.14675
x_alignment                                            110.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                                        NaN
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                  (826440000.0, 828040000.0]
R1_exit_interval_bins                                   None
R2_exit_interval                                         NaN
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet
No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49

2026-02-26 16:45:56,872|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0                      7640000
                                       0                      7680000
                                       0                      7720000
                                       0                      7760000
                                       0                      7800000
...                                                               ...
                                       617                 1566960000
                                       617                 1567000000
                                       617                 1567040000
                                       617                 1567080000
                                       617                 1567120000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0                    7680000
                                       0                    7720000
                                       0                    7760000
                                       0                    7800000
                                       0                    7840000
...                                                             ...
                                       617               1567000000
                                       617               1567040000
                                       617               1567080000
                                       617               1567120000
                                       617               1567160000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0            0.021429    -0.128347
                                       0            0.785210    -1.057621
                                       0           -0.018783    -0.125190
                                       0           -0.066504    -0.343744
                                       0           -0.158095     0.337759
...                                                      ...          ...
                                       617         -0.454691    -0.572205
                                       617          0.161385    -0.215534
                                       617         -0.009484     0.282141
                                       617          0.051426     0.011482
                                       617          0.038600     0.400442

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0           -0.045215     0.377274
                                       0           -0.685956    -0.488239
                                       0           -0.135384    -0.050018
                                       0            0.392097    -0.110172
                                       0           -0.425976     0.243480
...                                                      ...          ...
                                       617          0.309418    -0.568528
                                       617          0.153041    -0.737703
                                       617         -0.346156    -0.080336
                                       617          0.089933     0.913924
                                       617         -0.103293    -0.585134

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0            0.765051     0.734588
                                       0           -0.786628    -0.625497
                                       0            1.118361     1.866360
                                       0            0.050503     0.182679
                                       0            0.624646    -0.097089
...                                                      ...          ...
                                       617         -0.555408    -0.381745
                                       617          1.556619    -0.184740
                                       617          1.141999     0.423565
                                       617         -0.110171    -0.159524
                                       617          0.323793    -0.518708

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0           -0.040812     0.051069
                                       0            0.742482     0.271730
                                       0           -0.131290     0.059331
                                       0           -0.024368     1.073028
                                       0           -0.701340     2.193002
...                                                      ...          ...
                                       617         -0.106011    -0.163698
                                       617          1.620228    -0.407524
                                       617         -0.661884     2.113670
                                       617         -0.057048    -0.073137
                                       617         -0.541231     1.500406

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-12-09_17-45 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       617       ...      83.0  2.0
                                       617       ...      83.0  2.0
                                       617       ...      83.0  2.0
                                       617       ...      83.0  2.0
                                       617       ...      83.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0                   3.0        1.0
                                       0                   3.0        1.0
                                       0                   3.0        1.0
                                       0                   3.0        1.0
                                       0                   3.0        1.0
...                                                        ...        ...
                                       617                 0.0        0.0
                                       617                 0.0        0.0
                                       617                 0.0        0.0
                                       617                 0.0        0.0
                                       617                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       617             0.0  exit_reward2Zone
                                       617             0.0  exit_reward2Zone
                                       617             0.0  exit_reward2Zone
                                       617             0.0  exit_reward2Zone
                                       617             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0            7840000  -119.68995
                                       0            7840000  -119.68995
                                       0            7840000  -119.68995
                                       0            7840000  -119.68995
                                       0            7840000  -119.68995
...                                                     ...         ...
                                       617       1565960000   228.87400
                                       617       1565960000   228.87400
                                       617       1565960000   228.87400
                                       617       1565960000   228.87400
                                       617       1565960000   228.87400

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-12-09_17-45 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       617             230.0  R2_exit_interval
                                       617             230.0  R2_exit_interval
                                       617             230.0  R2_exit_interval
                                       617             230.0  R2_exit_interval
                                       617             230.0  R2_exit_interval

[20750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:45:58,348|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:45:58,359|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:45:58,360|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:58,374|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:58,375|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:45:58,531|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:45:58,532|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:45:58,533|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:45:58,533|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:45:58,617|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:45:58,624|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0              1.0  2.0            0.0
                                       1              1.0  2.0            0.0
                                       2              1.0  2.0            0.0
                                       3              1.0  2.0            0.0
                                       4              1.0  2.0            0.0
...                                                   ...  ...            ...
                                       649           87.0  1.0            0.0
                                       650           87.0  1.0            0.0
                                       651           87.0  1.0            0.0
                                       652           87.0  1.0            0.0
                                       653           87.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0               1.0        0.0
                                       1               1.0        0.0
                                       2               1.0        0.0
                                       3               1.0        0.0
                                       4               1.0        0.0
...                                                    ...        ...
                                       649             0.0        1.0
                                       650             0.0        1.0
                                       651             0.0        1.0
                                       652             0.0        1.0
                                       653             0.0        1.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       649            cueZone_exit
                                       650       enter_reward1Zone
                                       651       enter_reward2Zone
                                       652        exit_reward1Zone
                                       653        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0           10240000 -119.725400
                                       1           11280000  -80.065145
                                       2           31640000   24.545157
                                       3           32280000   49.597775
                                       4           43960000  170.252350
...                                                     ...         ...
                                       649       1847240000   25.217467
                                       650       1847560000   49.357990
                                       651       1849200000  170.627050
                                       652       1848360000  108.350800
                                       653       1853600000  230.299367

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       649              25.0
                                       650              50.0
                                       651             170.0
                                       652             110.0
                                       653             230.0

                                                         pre_cue_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0         (10040000.0, 10240000.0]
                                       1                              NaN
                                       2                              NaN
                                       3                              NaN
                                       4                              NaN
...                                                                   ...
                                       649                            NaN
                                       650                            NaN
                                       651                            NaN
                                       652                            NaN
                                       653                            NaN

                                                 ...  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-12-10_17-20 0         ...
                                       1         ...
                                       2         ...
                                       3         ...
                                       4         ...
...                                              ...
                                       649       ...
                                       650       ...
                                       651       ...
                                       652       ...
                                       653       ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (43560000.0, 45160000.0]
...                                                                       ...
                                       649                                NaN
                                       650                                NaN
                                       651       (1848800000.0, 1850400000.0]
                                       652                                NaN
                                       653                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       649                                                    None
                                       650                                                    None
                                       651                                                    None
                                       652                                                    None
                                       653                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       649                                NaN
                                       650                                NaN
                                       651                                NaN
                                       652       (1847960000.0, 1849560000.0]
                                       653                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       649                       None
                                       650                       None
                                       651                       None
                                       652                       None
                                       653                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       649                                NaN
                                       650                                NaN
                                       651                                NaN
                                       652                                NaN
                                       653       (1853200000.0, 1854800000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       649                       None
                                       650                       None
                                       651                       None
                                       652                       None
                                       653                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       649                              NaN
                                       650                              NaN
                                       651                              NaN
                                       652                              NaN
                                       653                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       649                                  None
                                       650                                  None
                                       651                                  None
                                       652                                  None
                                       653                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       649                              NaN
                                       650                              NaN
                                       651                              NaN
                                       652                              NaN
                                       653                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-10_17-20 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       649                                  None
                                       650                                  None
                                       651                                  None
                                       652                                  None
                                       653                                  None

[654 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2024-12-10_17-20
entry_id                                                   327
trial_id                                                  44.0
cue                                                        1.0
trial_outcome                                              1.0
choice_R1                                                  1.0
choice_R2                                                  0.0
t0_event_name                                  cueZone_visible
t0                                                  1069960000
x_position                                          -119.20265
x_alignment                                             -120.0
pre_cue_interval                  (1069760000.0, 1069960000.0]
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                (1069840000.0, 1071440000.0]
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45

2026-02-26 16:46:00,125|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0                     10040000
                                       0                     10080000
                                       0                     10120000
                                       0                     10160000
                                       0                     10200000
...                                                               ...
                                       653                 1854600000
                                       653                 1854640000
                                       653                 1854680000
                                       653                 1854720000
                                       653                 1854760000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0                   10080000
                                       0                   10120000
                                       0                   10160000
                                       0                   10200000
                                       0                   10240000
...                                                             ...
                                       653               1854640000
                                       653               1854680000
                                       653               1854720000
                                       653               1854760000
                                       653               1854800000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0           -0.369416     4.241521
                                       0           -0.241728    -0.682081
                                       0            0.374934     4.396173
                                       0           -0.018399    -1.016055
                                       0           -0.181018    -0.867379
...                                                      ...          ...
                                       653          0.023699     0.459408
                                       653         -0.305151     3.426906
                                       653         -0.699336    -0.393070
                                       653         -0.010568     0.033034
                                       653          0.064620     3.044635

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0           63.242045    -0.136159
                                       0           -1.029107    -0.346368
                                       0           66.382998    -0.208757
                                       0           -0.672953     0.186353
                                       0           25.666327    -0.080887
...                                                      ...          ...
                                       653         -0.267008     0.007737
                                       653         -0.406336    -0.885512
                                       653          1.102663     0.841995
                                       653         -0.100949    -0.219352
                                       653          1.017511    -0.369650

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0           29.655727     5.089197
                                       0            5.934984     2.587561
                                       0           45.408092     9.807913
                                       0            4.319503    -4.678749
                                       0           52.242712    14.867539
...                                                      ...          ...
                                       653          1.798759    -0.267121
                                       653         -2.391368    -0.148495
                                       653          0.866970    -1.218482
                                       653         -0.357036    -0.136931
                                       653          2.888540     0.640239

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0           -2.220896     3.530468
                                       0            2.431716    -0.136371
                                       0           -1.390767     2.496943
                                       0           -0.989402     2.369011
                                       0           -0.798691     6.130208
...                                                      ...          ...
                                       653          0.094091    -0.087793
                                       653         -1.306338     5.318367
                                       653          0.053491    -0.734290
                                       653         -0.256016     0.611780
                                       653         -0.557405     0.617169

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-12-10_17-20 1100        6         0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
...                                              ...       ...  ...
                                       653       ...      87.0  1.0
                                       653       ...      87.0  1.0
                                       653       ...      87.0  1.0
                                       653       ...      87.0  1.0
                                       653       ...      87.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
...                                                        ...        ...
                                       653                 0.0        0.0
                                       653                 0.0        0.0
                                       653                 0.0        0.0
                                       653                 0.0        0.0
                                       653                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
...                                                    ...               ...
                                       653             1.0  exit_reward2Zone
                                       653             1.0  exit_reward2Zone
                                       653             1.0  exit_reward2Zone
                                       653             1.0  exit_reward2Zone
                                       653             1.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0           10240000 -119.725400
                                       0           10240000 -119.725400
                                       0           10240000 -119.725400
                                       0           10240000 -119.725400
                                       0           10240000 -119.725400
...                                                     ...         ...
                                       653       1853600000  230.299367
                                       653       1853600000  230.299367
                                       653       1853600000  230.299367
                                       653       1853600000  230.299367
                                       653       1853600000  230.299367

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-12-10_17-20 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       653             230.0  R2_exit_interval
                                       653             230.0  R2_exit_interval
                                       653             230.0  R2_exit_interval
                                       653             230.0  R2_exit_interval
                                       653             230.0  R2_exit_interval

[21750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:01,944|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-26 16:46:01,954|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min:
2026-02-26 16:46:01,955|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:01,967|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:01,968|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:46:02,121|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:02,121|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:02,122|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:02,123|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:46:02,191|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:02,198|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0              1.0  2.0            0.0
                                       1              1.0  2.0            0.0
                                       2              1.0  2.0            0.0
                                       3              1.0  2.0            0.0
                                       4              1.0  2.0            0.0
...                                                   ...  ...            ...
                                       532           74.0  2.0            0.0
                                       533           74.0  2.0            0.0
                                       534           74.0  2.0            0.0
                                       535           74.0  2.0            0.0
                                       536           74.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0               1.0        0.0
                                       1               1.0        0.0
                                       2               1.0        0.0
                                       3               1.0        0.0
                                       4               1.0        0.0
...                                                    ...        ...
                                       532             0.0        0.0
                                       533             0.0        0.0
                                       534             0.0        0.0
                                       535             0.0        0.0
                                       536             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       532            cueZone_exit
                                       533       enter_reward1Zone
                                       534       enter_reward2Zone
                                       535        exit_reward1Zone
                                       536        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0            8160000 -119.405700
                                       1            8920000  -80.827670
                                       2           10640000   24.722997
                                       3           11200000   49.725760
                                       4           28360000  170.334567
...                                                     ...         ...
                                       532       1599360000   26.507865
                                       533       1599640000   51.567675
                                       534       1601200000  170.230750
                                       535       1600320000  108.353400
                                       536       1602320000  231.065733

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       532              25.0
                                       533              50.0
                                       534             170.0
                                       535             110.0
                                       536             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-12-12_16-13 0         (7960000.0, 8160000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       532                          NaN  ...
                                       533                          NaN  ...
                                       534                          NaN  ...
                                       535                          NaN  ...
                                       536                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (27960000.0, 29560000.0]
...                                                                       ...
                                       532                                NaN
                                       533                                NaN
                                       534       (1600800000.0, 1602400000.0]
                                       535                                NaN
                                       536                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       532                                                    None
                                       533                                                    None
                                       534                                                    None
                                       535                                                    None
                                       536                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       532                                NaN
                                       533                                NaN
                                       534                                NaN
                                       535       (1599920000.0, 1601520000.0]
                                       536                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       532                       None
                                       533                       None
                                       534                       None
                                       535                       None
                                       536                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       532                                NaN
                                       533                                NaN
                                       534                                NaN
                                       535                                NaN
                                       536       (1601920000.0, 1603520000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       532                       None
                                       533                       None
                                       534                       None
                                       535                       None
                                       536                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       532                              NaN
                                       533                              NaN
                                       534                              NaN
                                       535                              NaN
                                       536                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       532                                  None
                                       533                                  None
                                       534                                  None
                                       535                                  None
                                       536                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       532                              NaN
                                       533                              NaN
                                       534                              NaN
                                       535                              NaN
                                       536                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-12_16-13 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       532                                  None
                                       533                                  None
                                       534                                  None
                                       535                                  None
                                       536                                  None

[537 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2024-12-12_16-13
entry_id                                                   268
trial_id                                                  37.0
cue                                                        2.0
trial_outcome                                              0.0
choice_R1                                                  1.0
choice_R2                                                  0.0
t0_event_name                                    cueZone_entry
t0                                                  1004080000
x_position                                          -81.141983
x_alignment                                              -80.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval               (1004080000.0, 1004280000.0]
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42

2026-02-26 16:46:03,411|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0                      7960000
                                       0                      8000000
                                       0                      8040000
                                       0                      8080000
                                       0                      8120000
...                                                               ...
                                       536                 1603320000
                                       536                 1603360000
                                       536                 1603400000
                                       536                 1603440000
                                       536                 1603480000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0                    8000000
                                       0                    8040000
                                       0                    8080000
                                       0                    8120000
                                       0                    8160000
...                                                             ...
                                       536               1603360000
                                       536               1603400000
                                       536               1603440000
                                       536               1603480000
                                       536               1603520000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0           -0.108967    -0.169718
                                       0           -0.027328    -0.463509
                                       0           -0.039341    -0.270478
                                       0           -0.193226    -0.412631
                                       0            0.049356    -0.809540
...                                                      ...          ...
                                       536         -0.081525    -0.127833
                                       536         -0.056734     0.614750
                                       536          0.582838    -0.348111
                                       536          0.017233    -0.391461
                                       536         -0.080308    -0.029292

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0            1.419180     0.295320
                                       0            0.087687    -0.623032
                                       0           -0.048430    -0.221226
                                       0           -0.285836     0.499511
                                       0           -0.239415     1.956861
...                                                      ...          ...
                                       536         -0.197416    -0.314033
                                       536          0.010349    -0.150319
                                       536         -0.279582    -0.058421
                                       536          1.185215     0.095905
                                       536          0.409458     0.142661

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0           -0.010819     0.041977
                                       0           -0.571396     0.116409
                                       0           -0.280995     0.081781
                                       0            0.716771     0.246613
                                       0            1.618236     4.230706
...                                                      ...          ...
                                       536         -0.360240     0.222131
                                       536         -0.316352     0.075847
                                       536         -0.095365    -1.077938
                                       536          1.033260    -0.381364
                                       536         -0.348445    -0.215386

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0           -1.164136    -0.096007
                                       0            0.410983    -0.278536
                                       0           -0.229964     0.338285
                                       0           -0.796956     2.577503
                                       0           -1.985862    -1.498488
...                                                      ...          ...
                                       536         -0.660680     0.003525
                                       536         -0.133439     0.861546
                                       536         -0.953822    -0.904269
                                       536         -0.419513    -0.143489
                                       536         -0.204531    -0.428704

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-12-12_16-13 1100        6         0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
...                                              ...       ...  ...
                                       536       ...      74.0  2.0
                                       536       ...      74.0  2.0
                                       536       ...      74.0  2.0
                                       536       ...      74.0  2.0
                                       536       ...      74.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
...                                                        ...        ...
                                       536                 0.0        0.0
                                       536                 0.0        0.0
                                       536                 0.0        0.0
                                       536                 0.0        0.0
                                       536                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
...                                                    ...               ...
                                       536             0.0  exit_reward2Zone
                                       536             0.0  exit_reward2Zone
                                       536             0.0  exit_reward2Zone
                                       536             0.0  exit_reward2Zone
                                       536             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0            8160000 -119.405700
                                       0            8160000 -119.405700
                                       0            8160000 -119.405700
                                       0            8160000 -119.405700
                                       0            8160000 -119.405700
...                                                     ...         ...
                                       536       1602320000  231.065733
                                       536       1602320000  231.065733
                                       536       1602320000  231.065733
                                       536       1602320000  231.065733
                                       536       1602320000  231.065733

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-12-12_16-13 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       536             230.0  R2_exit_interval
                                       536             230.0  R2_exit_interval
                                       536             230.0  R2_exit_interval
                                       536             230.0  R2_exit_interval
                                       536             230.0  R2_exit_interval

[18500 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:04,654|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:46:04,664|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:46:04,664|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:04,678|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:04,679|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:46:04,820|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:04,821|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:04,822|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:04,823|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:46:04,886|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:04,893|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0              1.0  2.0            1.0
                                       1              1.0  2.0            1.0
                                       2              1.0  2.0            1.0
                                       3              1.0  2.0            1.0
                                       4              1.0  2.0            1.0
...                                                   ...  ...            ...
                                       830          117.0  2.0            0.0
                                       831          117.0  2.0            0.0
                                       832          117.0  2.0            0.0
                                       833          117.0  2.0            0.0
                                       834          117.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       830             0.0        0.0
                                       831             0.0        0.0
                                       832             0.0        0.0
                                       833             0.0        0.0
                                       834             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       830            cueZone_exit
                                       831       enter_reward1Zone
                                       832       enter_reward2Zone
                                       833        exit_reward1Zone
                                       834        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0            7400000 -120.936650
                                       1            7880000  -78.976500
                                       2            9440000   24.120590
                                       3           10240000   50.135673
                                       4           18080000  170.004067
...                                                     ...         ...
                                       830       1841480000   26.426910
                                       831       1841720000   48.697245
                                       832       1843000000  169.983250
                                       833       1842360000  110.971667
                                       834       1843640000  228.537867

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       830              25.0
                                       831              50.0
                                       832             170.0
                                       833             110.0
                                       834             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-12-13_17-10 0         (7200000.0, 7400000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       830                          NaN  ...
                                       831                          NaN  ...
                                       832                          NaN  ...
                                       833                          NaN  ...
                                       834                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (17680000.0, 19280000.0]
...                                                                       ...
                                       830                                NaN
                                       831                                NaN
                                       832       (1842600000.0, 1844200000.0]
                                       833                                NaN
                                       834                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       830                                                    None
                                       831                                                    None
                                       832                                                    None
                                       833                                                    None
                                       834                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       830                                NaN
                                       831                                NaN
                                       832                                NaN
                                       833       (1841960000.0, 1843560000.0]
                                       834                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       830                       None
                                       831                       None
                                       832                       None
                                       833                       None
                                       834                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       830                                NaN
                                       831                                NaN
                                       832                                NaN
                                       833                                NaN
                                       834       (1843240000.0, 1844840000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       830                       None
                                       831                       None
                                       832                       None
                                       833                       None
                                       834                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       830                              NaN
                                       831                              NaN
                                       832                              NaN
                                       833                              NaN
                                       834                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       830                                  None
                                       831                                  None
                                       832                                  None
                                       833                                  None
                                       834                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       830                              NaN
                                       831                              NaN
                                       832                              NaN
                                       833                              NaN
                                       834                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-12-13_17-10 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       830                                  None
                                       831                                  None
                                       832                                  None
                                       833                                  None
                                       834                                  None

[835 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2024-12-13_17-10
entry_id                                                 417
trial_id                                                58.0
cue                                                      2.0
trial_outcome                                            0.0
choice_R1                                                0.0
choice_R2                                                0.0
t0_event_name                              enter_reward2Zone
t0                                                 977000000
x_position                                          171.0781
x_alignment                                            170.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                                        NaN
R1_entry_interval_bins                                  None
R2_entry_interval                 (976600000.0, 978200000.0]
R2_entry_interval_bins                                  None
R1_exit_interval                                         NaN
R1_exit_interval_bins                                   None
R2_exit_interval                                         NaN
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13

2026-02-26 16:46:06,616|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0                      7200000
                                       0                      7240000
                                       0                      7280000
                                       0                      7320000
                                       0                      7360000
...                                                               ...
                                       834                 1844640000
                                       834                 1844680000
                                       834                 1844720000
                                       834                 1844760000
                                       834                 1844800000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0                    7240000
                                       0                    7280000
                                       0                    7320000
                                       0                    7360000
                                       0                    7400000
...                                                             ...
                                       834               1844680000
                                       834               1844720000
                                       834               1844760000
                                       834               1844800000
                                       834               1844840000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0           -0.078896    -0.277738
                                       0           -0.083827    -0.409057
                                       0           -0.107087    -0.281554
                                       0           -0.071240     1.053411
                                       0           -0.027503    -0.146455
...                                                      ...          ...
                                       834          0.833691    -0.503391
                                       834         -0.081141    -0.342360
                                       834          0.023565    -0.152442
                                       834         -0.189351    -1.138302
                                       834         -0.346133     0.581401

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0           -0.125187     0.781130
                                       0            0.201221    -0.257454
                                       0           -0.198487    -0.386218
                                       0           -0.183734     0.121430
                                       0           -0.037755     1.126159
...                                                      ...          ...
                                       834         -0.196214    -0.045745
                                       834         -0.256400     0.741466
                                       834         -0.109564     0.478698
                                       834         -0.021752     0.085370
                                       834          0.045719    -0.316831

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0            1.594348    -0.281670
                                       0           -0.300426     0.039160
                                       0            0.243086    -0.281672
                                       0           -0.414916    -0.026527
                                       0           -0.194507    -0.387860
...                                                      ...          ...
                                       834          1.120948     0.421803
                                       834         -0.461200    -0.392539
                                       834         -0.275064     0.362981
                                       834         -1.278644     2.266981
                                       834         -0.374393     0.907614

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0            0.604384    -0.087479
                                       0           -0.276219     0.322867
                                       0           -0.063290     2.116563
                                       0            0.678186    -0.546387
                                       0            0.653670     0.228591
...                                                      ...          ...
                                       834          0.423890    -1.469830
                                       834         -0.435318    -0.117728
                                       834         -0.114794    -0.067554
                                       834         -0.893126     1.986872
                                       834         -1.502814     0.748648

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2024-12-13_17-10 1100        6         0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
...                                              ...       ...  ...
                                       834       ...     117.0  2.0
                                       834       ...     117.0  2.0
                                       834       ...     117.0  2.0
                                       834       ...     117.0  2.0
                                       834       ...     117.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
...                                                        ...        ...
                                       834                 0.0        0.0
                                       834                 0.0        0.0
                                       834                 0.0        0.0
                                       834                 0.0        0.0
                                       834                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       834             0.0  exit_reward2Zone
                                       834             0.0  exit_reward2Zone
                                       834             0.0  exit_reward2Zone
                                       834             0.0  exit_reward2Zone
                                       834             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0            7400000 -120.936650
                                       0            7400000 -120.936650
                                       0            7400000 -120.936650
                                       0            7400000 -120.936650
                                       0            7400000 -120.936650
...                                                     ...         ...
                                       834       1843640000  228.537867
                                       834       1843640000  228.537867
                                       834       1843640000  228.537867
                                       834       1843640000  228.537867
                                       834       1843640000  228.537867

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2024-12-13_17-10 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       834             230.0  R2_exit_interval
                                       834             230.0  R2_exit_interval
                                       834             230.0  R2_exit_interval
                                       834             230.0  R2_exit_interval
                                       834             230.0  R2_exit_interval

[29250 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:08,124|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:46:08,136|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:46:08,137|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:08,155|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:08,156|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:46:08,263|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:08,264|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:08,265|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:08,265|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:46:08,391|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:08,397|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0              1.0  1.0            3.0
                                       1              1.0  1.0            3.0
                                       2              1.0  1.0            3.0
                                       3              1.0  1.0            3.0
                                       4              1.0  1.0            3.0
...                                                   ...  ...            ...
                                       552           76.0  1.0            0.0
                                       553           76.0  1.0            0.0
                                       554           76.0  1.0            0.0
                                       555           76.0  1.0            0.0
                                       556           76.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       552             0.0        0.0
                                       553             0.0        0.0
                                       554             0.0        0.0
                                       555             0.0        0.0
                                       556             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       552            cueZone_exit
                                       553       enter_reward1Zone
                                       554       enter_reward2Zone
                                       555        exit_reward1Zone
                                       556        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0            8000000 -120.835600
                                       1            8800000  -78.846970
                                       2           11560000   24.975373
                                       3           12480000   49.991755
                                       4           26720000  169.912533
...                                                     ...         ...
                                       552       1803040000   23.726100
                                       553       1803360000   51.393943
                                       554       1804760000  171.042867
                                       555       1804040000  111.350250
                                       556       1805440000  229.687200

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       552              25.0
                                       553              50.0
                                       554             170.0
                                       555             110.0
                                       556             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-14_18-08 0         (7800000.0, 8000000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       552                          NaN  ...
                                       553                          NaN  ...
                                       554                          NaN  ...
                                       555                          NaN  ...
                                       556                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (26320000.0, 27920000.0]
...                                                                       ...
                                       552                                NaN
                                       553                                NaN
                                       554       (1804360000.0, 1805960000.0]
                                       555                                NaN
                                       556                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       552                                                    None
                                       553                                                    None
                                       554                                                    None
                                       555                                                    None
                                       556                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       552                                NaN
                                       553                                NaN
                                       554                                NaN
                                       555       (1803640000.0, 1805240000.0]
                                       556                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       552                       None
                                       553                       None
                                       554                       None
                                       555                       None
                                       556                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       552                                NaN
                                       553                                NaN
                                       554                                NaN
                                       555                                NaN
                                       556       (1805040000.0, 1806640000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       552                       None
                                       553                       None
                                       554                       None
                                       555                       None
                                       556                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       552                              NaN
                                       553                              NaN
                                       554                              NaN
                                       555                              NaN
                                       556                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       552                                  None
                                       553                                  None
                                       554                                  None
                                       555                                  None
                                       556                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       552                              NaN
                                       553                              NaN
                                       554                              NaN
                                       555                              NaN
                                       556                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-14_18-08 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       552                                  None
                                       553                                  None
                                       554                                  None
                                       555                                  None
                                       556                                  None

[557 rows x 29 columns]
paradigm_id                                             1100
animal_id                                                  6
session_id                                  2025-01-14_18-08
entry_id                                                 278
trial_id                                                38.0
cue                                                      2.0
trial_outcome                                            3.0
choice_R1                                                1.0
choice_R2                                                1.0
t0_event_name                              enter_reward1Zone
t0                                                 955880000
x_position                                         49.795407
x_alignment                                             50.0
pre_cue_interval                                         NaN
pre_cue_interval_bins                                   None
nextto_cue_interval                                      NaN
nextto_cue_interval_bins                                None
cue_entry_interval                                       NaN
cue_entry_interval_bins                                 None
cue_exit_interval                                        NaN
cue_exit_interval_bins                                  None
R1_entry_interval                 (955480000.0, 957080000.0]
R1_entry_interval_bins                                  None
R2_entry_interval                                        NaN
R2_entry_interval_bins                                  None
R1_exit_interval                                         NaN
R1_exit_interval_bins                                   None
R2_exit_interval                                         NaN
R2_exit_interval_bins                                   None
reward1_valve_open_interval                              NaN
reward1_valve_open_interval_bins                        None
reward2_valve_open_interval                              NaN
reward2_valve_open_interval_bins                        None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10

2026-02-26 16:46:09,809|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0                      7800000
                                       0                      7840000
                                       0                      7880000
                                       0                      7920000
                                       0                      7960000
...                                                               ...
                                       556                 1806440000
                                       556                 1806480000
                                       556                 1806520000
                                       556                 1806560000
                                       556                 1806600000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0                    7840000
                                       0                    7880000
                                       0                    7920000
                                       0                    7960000
                                       0                    8000000
...                                                             ...
                                       556               1806480000
                                       556               1806520000
                                       556               1806560000
                                       556               1806600000
                                       556               1806640000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0            0.104343     0.329431
                                       0            0.025069    -0.432071
                                       0            1.389287     1.095285
                                       0           -0.398410     0.039563
                                       0           -0.505585     4.693698
...                                                      ...          ...
                                       556         -0.137894     4.663660
                                       556         -0.132321     0.004971
                                       556          0.121161     0.528881
                                       556         -0.081715    -0.394882
                                       556         -0.215538    -0.763827

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0            0.440946    -0.104534
                                       0            0.571392    -0.195152
                                       0           -0.262505    -0.570431
                                       0           -0.820639    -0.669087
                                       0            3.362869     0.622768
...                                                      ...          ...
                                       556         -0.140074    -0.640316
                                       556          1.115778     0.023222
                                       556         -0.181776    -0.340957
                                       556          0.333671     0.568505
                                       556          0.070794     3.355168

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0           -0.150298    -0.317379
                                       0           -0.202324     0.339284
                                       0           -0.151691    -0.114932
                                       0           -0.355884     9.946712
                                       0           -1.433615     0.766664
...                                                      ...          ...
                                       556          0.567192    -0.837512
                                       556         -0.146520    -0.317562
                                       556         -0.159211    -0.317268
                                       556         -0.077274    -0.212747
                                       556         -0.293428    -0.155033

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0            0.244996     1.610495
                                       0            0.107479     1.578820
                                       0           -1.634390    -0.496623
                                       0           -1.566758     0.533323
                                       0           -0.979936     6.291923
...                                                      ...          ...
                                       556          0.032753    -0.848352
                                       556         -0.034152     1.456957
                                       556         -0.079029    -0.360370
                                       556          0.265683     1.241353
                                       556         -0.105282    -0.630418

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-14_18-08 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       556       ...      76.0  1.0
                                       556       ...      76.0  1.0
                                       556       ...      76.0  1.0
                                       556       ...      76.0  1.0
                                       556       ...      76.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0                   3.0        1.0
                                       0                   3.0        1.0
                                       0                   3.0        1.0
                                       0                   3.0        1.0
                                       0                   3.0        1.0
...                                                        ...        ...
                                       556                 0.0        0.0
                                       556                 0.0        0.0
                                       556                 0.0        0.0
                                       556                 0.0        0.0
                                       556                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       556             0.0  exit_reward2Zone
                                       556             0.0  exit_reward2Zone
                                       556             0.0  exit_reward2Zone
                                       556             0.0  exit_reward2Zone
                                       556             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0            8000000   -120.8356
                                       0            8000000   -120.8356
                                       0            8000000   -120.8356
                                       0            8000000   -120.8356
                                       0            8000000   -120.8356
...                                                     ...         ...
                                       556       1805440000    229.6872
                                       556       1805440000    229.6872
                                       556       1805440000    229.6872
                                       556       1805440000    229.6872
                                       556       1805440000    229.6872

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-14_18-08 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       556             230.0  R2_exit_interval
                                       556             230.0  R2_exit_interval
                                       556             230.0  R2_exit_interval
                                       556             230.0  R2_exit_interval
                                       556             230.0  R2_exit_interval

[19000 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:10,829|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:46:10,841|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:46:10,842|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:10,857|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:10,857|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:46:10,985|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:10,986|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:10,986|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:10,987|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
================================================================================

2026-02-26 16:46:11,039|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:11,047|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0              1.0  1.0            2.0
                                       1              1.0  1.0            2.0
                                       2              1.0  1.0            2.0
                                       3              1.0  1.0            2.0
                                       4              1.0  1.0            2.0
...                                                   ...  ...            ...
                                       645           88.0  2.0            0.0
                                       646           88.0  2.0            0.0
                                       647           88.0  2.0            0.0
                                       648           88.0  2.0            0.0
                                       649           88.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       645             0.0        0.0
                                       646             0.0        0.0
                                       647             0.0        0.0
                                       648             0.0        0.0
                                       649             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       645            cueZone_exit
                                       646       enter_reward1Zone
                                       647       enter_reward2Zone
                                       648        exit_reward1Zone
                                       649        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0            8880000 -120.556500
                                       1            9480000  -80.355563
                                       2           11520000   24.973317
                                       3           13400000   50.220997
                                       4           26000000  169.880700
...                                                     ...         ...
                                       645       1822600000   24.209513
                                       646       1823000000   50.455897
                                       647       1825280000  170.141300
                                       648       1823840000  109.824400
                                       649       1826120000  229.970933

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       645              25.0
                                       646              50.0
                                       647             170.0
                                       648             110.0
                                       649             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-15_17-18 0         (8680000.0, 8880000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       645                          NaN  ...
                                       646                          NaN  ...
                                       647                          NaN  ...
                                       648                          NaN  ...
                                       649                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (25600000.0, 27200000.0]
...                                                                       ...
                                       645                                NaN
                                       646                                NaN
                                       647       (1824880000.0, 1826480000.0]
                                       648                                NaN
                                       649                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       645                                                    None
                                       646                                                    None
                                       647                                                    None
                                       648                                                    None
                                       649                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       645                                NaN
                                       646                                NaN
                                       647                                NaN
                                       648       (1823440000.0, 1825040000.0]
                                       649                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       645                       None
                                       646                       None
                                       647                       None
                                       648                       None
                                       649                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       645                                NaN
                                       646                                NaN
                                       647                                NaN
                                       648                                NaN
                                       649       (1825720000.0, 1827320000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       645                       None
                                       646                       None
                                       647                       None
                                       648                       None
                                       649                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       645                              NaN
                                       646                              NaN
                                       647                              NaN
                                       648                              NaN
                                       649                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       645                                  None
                                       646                                  None
                                       647                                  None
                                       648                                  None
                                       649                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       645                              NaN
                                       646                              NaN
                                       647                              NaN
                                       648                              NaN
                                       649                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-15_17-18 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       645                                  None
                                       646                                  None
                                       647                                  None
                                       648                                  None
                                       649                                  None

[650 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-15_17-18
entry_id                                                   325
trial_id                                                  43.0
cue                                                        1.0
trial_outcome                                              3.0
choice_R1                                                  1.0
choice_R2                                                  0.0
t0_event_name                                 exit_reward2Zone
t0                                                  1008600000
x_position                                          229.408567
x_alignment                                              230.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                  (1008200000.0, 1009800000.0]
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet
No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08

2026-02-26 16:46:12,472|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0                      8680000
                                       0                      8720000
                                       0                      8760000
                                       0                      8800000
                                       0                      8840000
...                                                               ...
                                       649                 1827120000
                                       649                 1827160000
                                       649                 1827200000
                                       649                 1827240000
                                       649                 1827280000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0                    8720000
                                       0                    8760000
                                       0                    8800000
                                       0                    8840000
                                       0                    8880000
...                                                             ...
                                       649               1827160000
                                       649               1827200000
                                       649               1827240000
                                       649               1827280000
                                       649               1827320000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0           -0.401188    -1.261755
                                       0            0.430464    -0.681797
                                       0           -0.060764     0.274452
                                       0           -0.108288    -0.206622
                                       0            0.032407    -0.247175
...                                                      ...          ...
                                       649          0.053099    -0.147350
                                       649         -0.128231     4.031588
                                       649         -0.065185     0.412894
                                       649         -0.014126    -0.696164
                                       649          0.072950     0.043842

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0           -0.452261    -0.859040
                                       0            0.667276     0.243424
                                       0           -0.303963     7.114020
                                       0           -0.523101     0.436568
                                       0            0.864607    -0.335496
...                                                      ...          ...
                                       649         -0.239601    -0.090542
                                       649         -0.277638     1.302105
                                       649         -0.044043     3.433116
                                       649         -0.475011    -1.227873
                                       649          0.555317     0.372044

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0           -0.625193    -0.871038
                                       0           -0.228769    -0.653587
                                       0            3.798496     2.973767
                                       0            0.338117     1.394932
                                       0            0.008719     1.574235
...                                                      ...          ...
                                       649         -0.421979    -0.054316
                                       649         -0.030353    -1.276298
                                       649         -0.179407    -0.564500
                                       649          0.083721    -1.014579
                                       649         -0.445991    -0.356947

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0           -1.171289    -0.143207
                                       0           -0.155066     0.569573
                                       0            0.030386     2.917558
                                       0            2.215074     0.000610
                                       0            0.484624    -0.072985
...                                                      ...          ...
                                       649         -0.067701     0.436317
                                       649          0.441510     3.820516
                                       649         -0.814351     0.322953
                                       649          1.238136    -0.069680
                                       649         -0.102817    -0.107210

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-15_17-18 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       649       ...      88.0  2.0
                                       649       ...      88.0  2.0
                                       649       ...      88.0  2.0
                                       649       ...      88.0  2.0
                                       649       ...      88.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
...                                                        ...        ...
                                       649                 0.0        0.0
                                       649                 0.0        0.0
                                       649                 0.0        0.0
                                       649                 0.0        0.0
                                       649                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       649             0.0  exit_reward2Zone
                                       649             0.0  exit_reward2Zone
                                       649             0.0  exit_reward2Zone
                                       649             0.0  exit_reward2Zone
                                       649             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0            8880000 -120.556500
                                       0            8880000 -120.556500
                                       0            8880000 -120.556500
                                       0            8880000 -120.556500
                                       0            8880000 -120.556500
...                                                     ...         ...
                                       649       1826120000  229.970933
                                       649       1826120000  229.970933
                                       649       1826120000  229.970933
                                       649       1826120000  229.970933
                                       649       1826120000  229.970933

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-15_17-18 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       649             230.0  R2_exit_interval
                                       649             230.0  R2_exit_interval
                                       649             230.0  R2_exit_interval
                                       649             230.0  R2_exit_interval
                                       649             230.0  R2_exit_interval

[22000 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:14,237|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:46:14,325|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:46:14,325|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:14,343|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:14,344|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:46:14,596|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:14,597|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:14,598|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:14,599|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
================================================================================

2026-02-26 16:46:14,648|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:14,656|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0              1.0  1.0            2.0
                                       1              1.0  1.0            2.0
                                       2              1.0  1.0            2.0
                                       3              1.0  1.0            2.0
                                       4              1.0  1.0            2.0
...                                                   ...  ...            ...
                                       774          107.0  2.0            2.0
                                       775          107.0  2.0            2.0
                                       776          107.0  2.0            2.0
                                       777          107.0  2.0            2.0
                                       778          107.0  2.0            2.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       774             0.0        1.0
                                       775             0.0        1.0
                                       776             0.0        1.0
                                       777             0.0        1.0
                                       778             0.0        1.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       774       enter_reward1Zone
                                       775       enter_reward2Zone
                                       776        exit_reward1Zone
                                       777        exit_reward2Zone
                                       778           reward2_sound

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0            7440000 -120.955400
                                       1            8040000  -80.360187
                                       2           10040000   24.742017
                                       3           15600000   50.179875
                                       4           30840000  170.479533
...                                                     ...         ...
                                       774       1829360000   51.396520
                                       775       1830920000  170.032333
                                       776       1830040000  110.862200
                                       777       1837400000  229.012267
                                       778       1834440000  198.182600

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       774              50.0
                                       775             170.0
                                       776             110.0
                                       777             230.0
                                       778               NaN

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-16_17-47 0         (7240000.0, 7440000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       774                          NaN  ...
                                       775                          NaN  ...
                                       776                          NaN  ...
                                       777                          NaN  ...
                                       778                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (30440000.0, 32040000.0]
...                                                                       ...
                                       774                                NaN
                                       775       (1830520000.0, 1832120000.0]
                                       776                                NaN
                                       777                                NaN
                                       778                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       774                                                    None
                                       775                                                    None
                                       776                                                    None
                                       777                                                    None
                                       778                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       774                                NaN
                                       775                                NaN
                                       776       (1829640000.0, 1831240000.0]
                                       777                                NaN
                                       778                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       774                       None
                                       775                       None
                                       776                       None
                                       777                       None
                                       778                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       774                                NaN
                                       775                                NaN
                                       776                                NaN
                                       777       (1837000000.0, 1838600000.0]
                                       778                                NaN

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       774                       None
                                       775                       None
                                       776                       None
                                       777                       None
                                       778                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       774                              NaN
                                       775                              NaN
                                       776                              NaN
                                       777                              NaN
                                       778                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       774                                  None
                                       775                                  None
                                       776                                  None
                                       777                                  None
                                       778                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       774                              NaN
                                       775                              NaN
                                       776                              NaN
                                       777                              NaN
                                       778                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-16_17-47 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       774                                  None
                                       775                                  None
                                       776                                  None
                                       777                                  None
                                       778                                  None

[779 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-16_17-47
entry_id                                                   389
trial_id                                                  53.0
cue                                                        1.0
trial_outcome                                              2.0
choice_R1                                                  1.0
choice_R2                                                  0.0
t0_event_name                                 exit_reward1Zone
t0                                                  1039680000
x_position                                            108.7011
x_alignment                                              110.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                  (1039280000.0, 1040880000.0]
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18

2026-02-26 16:46:16,369|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0                      7240000
                                       0                      7280000
                                       0                      7320000
                                       0                      7360000
                                       0                      7400000
...                                                               ...
                                       777                 1838400000
                                       777                 1838440000
                                       777                 1838480000
                                       777                 1838520000
                                       777                 1838560000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0                    7280000
                                       0                    7320000
                                       0                    7360000
                                       0                    7400000
                                       0                    7440000
...                                                             ...
                                       777               1838440000
                                       777               1838480000
                                       777               1838520000
                                       777               1838560000
                                       777               1838600000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0           -0.037789    -0.087689
                                       0           -0.143172    -0.087264
                                       0           -0.029318     0.113020
                                       0           -0.029318     0.113020
                                       0            0.320542    -0.020254
...                                                      ...          ...
                                       777         -0.093068    -0.267426
                                       777          0.228580     0.265315
                                       777         -0.030245     2.774615
                                       777         -0.014370     0.213373
                                       777         -0.083214    -0.252262

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0           -0.124712    -0.094388
                                       0            0.014926     2.104884
                                       0           -0.063214     0.045631
                                       0           -0.063214     0.045631
                                       0           -0.811588    -0.314208
...                                                      ...          ...
                                       777          0.387999    -0.913926
                                       777         -0.044936     3.246215
                                       777          0.536141     0.405925
                                       777         -0.130611    -0.124811
                                       777          0.320844    -0.062908

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0            0.062388    -0.216067
                                       0           -0.277411    -0.270882
                                       0            0.019678     0.168550
                                       0            0.019678     0.168550
                                       0           -0.101289     0.994977
...                                                      ...          ...
                                       777          3.557192    -0.315739
                                       777          2.250607    -0.058926
                                       777         -0.185837    -0.195078
                                       777         -0.333027    -0.287691
                                       777         -0.166810    -0.248906

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0           -0.104133    -0.073624
                                       0            0.287294    -0.205917
                                       0            0.158618     0.048770
                                       0            0.158618     0.048770
                                       0           -0.829751    -0.237506
...                                                      ...          ...
                                       777          0.383196    -0.317273
                                       777          2.611642    -0.395704
                                       777          2.015528    -0.194289
                                       777         -0.080174    -0.128800
                                       777         -0.015473     0.401743

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-16_17-47 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       777       ...     107.0  2.0
                                       777       ...     107.0  2.0
                                       777       ...     107.0  2.0
                                       777       ...     107.0  2.0
                                       777       ...     107.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
                                       0                   2.0        1.0
...                                                        ...        ...
                                       777                 2.0        0.0
                                       777                 2.0        0.0
                                       777                 2.0        0.0
                                       777                 2.0        0.0
                                       777                 2.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       777             1.0  exit_reward2Zone
                                       777             1.0  exit_reward2Zone
                                       777             1.0  exit_reward2Zone
                                       777             1.0  exit_reward2Zone
                                       777             1.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0            7440000 -120.955400
                                       0            7440000 -120.955400
                                       0            7440000 -120.955400
                                       0            7440000 -120.955400
                                       0            7440000 -120.955400
...                                                     ...         ...
                                       777       1837400000  229.012267
                                       777       1837400000  229.012267
                                       777       1837400000  229.012267
                                       777       1837400000  229.012267
                                       777       1837400000  229.012267

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-16_17-47 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       777             230.0  R2_exit_interval
                                       777             230.0  R2_exit_interval
                                       777             230.0  R2_exit_interval
                                       777             230.0  R2_exit_interval
                                       777             230.0  R2_exit_interval

[26750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:18,191|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-26 16:46:18,202|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min:
2026-02-26 16:46:18,203|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:18,214|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:18,214|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:46:18,371|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:18,371|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:18,372|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:18,373|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:46:18,443|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:18,450|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0              1.0  2.0            0.0
                                       1              1.0  2.0            0.0
                                       2              1.0  2.0            0.0
                                       3              1.0  2.0            0.0
                                       4              1.0  2.0            0.0
...                                                   ...  ...            ...
                                       751          105.0  2.0            0.0
                                       752          105.0  2.0            0.0
                                       753          105.0  2.0            0.0
                                       754          105.0  2.0            0.0
                                       755          105.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0               1.0        0.0
                                       1               1.0        0.0
                                       2               1.0        0.0
                                       3               1.0        0.0
                                       4               1.0        0.0
...                                                    ...        ...
                                       751             0.0        0.0
                                       752             0.0        0.0
                                       753             0.0        0.0
                                       754             0.0        0.0
                                       755             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       751            cueZone_exit
                                       752       enter_reward1Zone
                                       753       enter_reward2Zone
                                       754        exit_reward1Zone
                                       755        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0            7600000 -119.778867
                                       1            8200000  -79.543443
                                       2           10160000   25.713735
                                       3           12800000   50.090957
                                       4           23800000  170.393167
...                                                     ...         ...
                                       751       1841920000   26.649473
                                       752       1842160000   48.849900
                                       753       1843600000  170.250050
                                       754       1842840000  110.349267
                                       755       1844280000  228.497500

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       751              25.0
                                       752              50.0
                                       753             170.0
                                       754             110.0
                                       755             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-17_16-55 0         (7400000.0, 7600000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       751                          NaN  ...
                                       752                          NaN  ...
                                       753                          NaN  ...
                                       754                          NaN  ...
                                       755                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (23400000.0, 25000000.0]
...                                                                       ...
                                       751                                NaN
                                       752                                NaN
                                       753       (1843200000.0, 1844800000.0]
                                       754                                NaN
                                       755                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       751                                                    None
                                       752                                                    None
                                       753                                                    None
                                       754                                                    None
                                       755                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       751                                NaN
                                       752                                NaN
                                       753                                NaN
                                       754       (1842440000.0, 1844040000.0]
                                       755                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       751                       None
                                       752                       None
                                       753                       None
                                       754                       None
                                       755                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       751                                NaN
                                       752                                NaN
                                       753                                NaN
                                       754                                NaN
                                       755       (1843880000.0, 1845480000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       751                       None
                                       752                       None
                                       753                       None
                                       754                       None
                                       755                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       751                              NaN
                                       752                              NaN
                                       753                              NaN
                                       754                              NaN
                                       755                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       751                                  None
                                       752                                  None
                                       753                                  None
                                       754                                  None
                                       755                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       751                              NaN
                                       752                              NaN
                                       753                              NaN
                                       754                              NaN
                                       755                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-17_16-55 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       751                                  None
                                       752                                  None
                                       753                                  None
                                       754                                  None
                                       755                                  None

[756 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-17_16-55
entry_id                                                   378
trial_id                                                  53.0
cue                                                        2.0
trial_outcome                                              0.0
choice_R1                                                  0.0
choice_R2                                                  0.0
t0_event_name                                     cueZone_exit
t0                                                  1011600000
x_position                                           25.920107
x_alignment                                               25.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                 (1011200000.0, 1012800000.0]
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47

2026-02-26 16:46:19,982|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0                      7400000
                                       0                      7440000
                                       0                      7480000
                                       0                      7520000
                                       0                      7560000
...                                                               ...
                                       755                 1845280000
                                       755                 1845320000
                                       755                 1845360000
                                       755                 1845400000
                                       755                 1845440000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0                    7440000
                                       0                    7480000
                                       0                    7520000
                                       0                    7560000
                                       0                    7600000
...                                                             ...
                                       755               1845320000
                                       755               1845360000
                                       755               1845400000
                                       755               1845440000
                                       755               1845480000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0            0.043572    -0.153545
                                       0           -0.306485    -0.236100
                                       0           -0.163783     0.060861
                                       0           -0.055089     0.185139
                                       0           -0.105315    -0.126373
...                                                      ...          ...
                                       755         -0.411758    -0.259289
                                       755         -0.266187     0.759876
                                       755         -0.056346    -0.140554
                                       755          0.351855    -0.227291
                                       755         -0.185569    -0.448149

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0            0.183114    -0.166058
                                       0            0.082265    -0.416719
                                       0           -0.204714    -0.589118
                                       0            1.541986    -0.374452
                                       0           -0.267609    -0.011484
...                                                      ...          ...
                                       755          0.447230    -4.397308
                                       755          1.201512    -0.309612
                                       755         -0.073536    -0.156804
                                       755         -0.375472    -0.518056
                                       755         -0.153876    -1.356512

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0            0.029457    -0.140417
                                       0            0.343454     0.581607
                                       0           -0.363146     3.488475
                                       0           -0.235561     0.551396
                                       0           -0.230126    -0.549425
...                                                      ...          ...
                                       755          0.421285     4.513072
                                       755         -1.067015    -0.292414
                                       755         -0.166112     3.080238
                                       755         -0.029033    -0.241823
                                       755         -0.246024     3.799990

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0           -0.314144    -0.035902
                                       0            1.462687    -0.629846
                                       0            0.214677     0.215668
                                       0           -0.107650    -0.076948
                                       0            0.832167    -0.014984
...                                                      ...          ...
                                       755         -0.291208    -0.488669
                                       755          0.295230    -1.275904
                                       755         -1.051620    -0.177537
                                       755         -0.457617    -0.160316
                                       755          0.070198    -0.261271

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-17_16-55 1100        6         0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
...                                              ...       ...  ...
                                       755       ...     105.0  2.0
                                       755       ...     105.0  2.0
                                       755       ...     105.0  2.0
                                       755       ...     105.0  2.0
                                       755       ...     105.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
...                                                        ...        ...
                                       755                 0.0        0.0
                                       755                 0.0        0.0
                                       755                 0.0        0.0
                                       755                 0.0        0.0
                                       755                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
...                                                    ...               ...
                                       755             0.0  exit_reward2Zone
                                       755             0.0  exit_reward2Zone
                                       755             0.0  exit_reward2Zone
                                       755             0.0  exit_reward2Zone
                                       755             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0            7600000 -119.778867
                                       0            7600000 -119.778867
                                       0            7600000 -119.778867
                                       0            7600000 -119.778867
                                       0            7600000 -119.778867
...                                                     ...         ...
                                       755       1844280000  228.497500
                                       755       1844280000  228.497500
                                       755       1844280000  228.497500
                                       755       1844280000  228.497500
                                       755       1844280000  228.497500

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-17_16-55 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       755             230.0  R2_exit_interval
                                       755             230.0  R2_exit_interval
                                       755             230.0  R2_exit_interval
                                       755             230.0  R2_exit_interval
                                       755             230.0  R2_exit_interval

[26250 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:22,065|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-26 16:46:22,078|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min:
2026-02-26 16:46:22,079|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:22,092|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:22,093|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:46:22,352|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:22,353|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:22,355|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:22,366|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
================================================================================

2026-02-26 16:46:22,424|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:22,432|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0              1.0  1.0            0.0
                                       1              1.0  1.0            0.0
                                       2              1.0  1.0            0.0
                                       3              1.0  1.0            0.0
                                       4              1.0  1.0            0.0
...                                                   ...  ...            ...
                                       904          127.0  2.0            0.0
                                       905          127.0  2.0            0.0
                                       906          127.0  2.0            0.0
                                       907          127.0  2.0            0.0
                                       908          127.0  2.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0               0.0        1.0
                                       1               0.0        1.0
                                       2               0.0        1.0
                                       3               0.0        1.0
                                       4               0.0        1.0
...                                                    ...        ...
                                       904             0.0        0.0
                                       905             0.0        0.0
                                       906             0.0        0.0
                                       907             0.0        0.0
                                       908             0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       904            cueZone_exit
                                       905       enter_reward1Zone
                                       906       enter_reward2Zone
                                       907        exit_reward1Zone
                                       908        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0            7720000 -121.160250
                                       1            8320000  -80.230140
                                       2           11120000   24.399693
                                       3           11640000   49.503967
                                       4           15080000  170.144933
...                                                     ...         ...
                                       904       2519800000   25.965080
                                       905       2520200000   50.406550
                                       906       2522840000  170.002033
                                       907       2521440000  110.286533
                                       908       2524840000  229.785100

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       904              25.0
                                       905              50.0
                                       906             170.0
                                       907             110.0
                                       908             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-23_16-48 0         (7520000.0, 7720000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       904                          NaN  ...
                                       905                          NaN  ...
                                       906                          NaN  ...
                                       907                          NaN  ...
                                       908                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (14680000.0, 16280000.0]
...                                                                       ...
                                       904                                NaN
                                       905                                NaN
                                       906       (2522440000.0, 2524040000.0]
                                       907                                NaN
                                       908                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       904                                                    None
                                       905                                                    None
                                       906                                                    None
                                       907                                                    None
                                       908                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       904                                NaN
                                       905                                NaN
                                       906                                NaN
                                       907       (2521040000.0, 2522640000.0]
                                       908                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       904                       None
                                       905                       None
                                       906                       None
                                       907                       None
                                       908                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       904                                NaN
                                       905                                NaN
                                       906                                NaN
                                       907                                NaN
                                       908       (2524440000.0, 2526040000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       904                       None
                                       905                       None
                                       906                       None
                                       907                       None
                                       908                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       904                              NaN
                                       905                              NaN
                                       906                              NaN
                                       907                              NaN
                                       908                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       904                                  None
                                       905                                  None
                                       906                                  None
                                       907                                  None
                                       908                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       904                              NaN
                                       905                              NaN
                                       906                              NaN
                                       907                              NaN
                                       908                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-23_16-48 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       904                                  None
                                       905                                  None
                                       906                                  None
                                       907                                  None
                                       908                                  None

[909 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-23_16-48
entry_id                                                   454
trial_id                                                  64.0
cue                                                        2.0
trial_outcome                                              1.0
choice_R1                                                  0.0
choice_R2                                                  1.0
t0_event_name                                    cueZone_entry
t0                                                  1333680000
x_position                                          -81.644155
x_alignment                                              -80.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval               (1333680000.0, 1333880000.0]
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51

2026-02-26 16:46:24,594|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0                      7520000
                                       0                      7560000
                                       0                      7600000
                                       0                      7640000
                                       0                      7680000
...                                                               ...
                                       908                 2525840000
                                       908                 2525880000
                                       908                 2525920000
                                       908                 2525960000
                                       908                 2526000000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0                    7560000
                                       0                    7600000
                                       0                    7640000
                                       0                    7680000
                                       0                    7720000
...                                                             ...
                                       908               2525880000
                                       908               2525920000
                                       908               2525960000
                                       908               2526000000
                                       908               2526040000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0           -0.033525    -0.055446
                                       0           -0.075623    -0.255445
                                       0           -0.067952     0.084100
                                       0            0.139670    -0.062955
                                       0           -0.059857    -0.146545
...                                                      ...          ...
                                       908          0.078558    -0.091628
                                       908         -0.069317     0.121179
                                       908         -0.164093     0.001325
                                       908          0.848206    -0.038479
                                       908          0.100244    -0.030396

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0           -0.043131    -0.177498
                                       0            1.250758     0.214314
                                       0           -0.034089    -0.156590
                                       0            0.303545     1.009154
                                       0           -0.085989    -0.208440
...                                                      ...          ...
                                       908         -0.123096    -0.171858
                                       908          0.036973    -0.105137
                                       908         -0.336222    -0.089815
                                       908         -0.395092    -0.243588
                                       908          0.272328    -0.186493

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0           -0.047972     0.040167
                                       0           -0.318875     0.047328
                                       0            0.266608     0.046949
                                       0            0.426274     1.722996
                                       0            0.340942    -0.137282
...                                                      ...          ...
                                       908         -0.230526     0.058854
                                       908         -0.149437    -0.407412
                                       908          1.087193     3.669640
                                       908          0.321259    -0.333419
                                       908         -0.251049    -0.355251

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0           -0.105763    -0.073644
                                       0           -0.119671     0.158720
                                       0           -0.022170    -0.081944
                                       0           -0.072570    -0.102653
                                       0            0.575195    -0.099897
...                                                      ...          ...
                                       908         -0.070592    -0.142139
                                       908         -0.591952     0.312343
                                       908         -0.113417    -0.296409
                                       908         -0.236404    -0.159015
                                       908          0.326740     0.400201

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-23_16-48 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       908       ...     127.0  2.0
                                       908       ...     127.0  2.0
                                       908       ...     127.0  2.0
                                       908       ...     127.0  2.0
                                       908       ...     127.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
...                                                        ...        ...
                                       908                 0.0        0.0
                                       908                 0.0        0.0
                                       908                 0.0        0.0
                                       908                 0.0        0.0
                                       908                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       908             0.0  exit_reward2Zone
                                       908             0.0  exit_reward2Zone
                                       908             0.0  exit_reward2Zone
                                       908             0.0  exit_reward2Zone
                                       908             0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0            7720000  -121.16025
                                       0            7720000  -121.16025
                                       0            7720000  -121.16025
                                       0            7720000  -121.16025
                                       0            7720000  -121.16025
...                                                     ...         ...
                                       908       2524840000   229.78510
                                       908       2524840000   229.78510
                                       908       2524840000   229.78510
                                       908       2524840000   229.78510
                                       908       2524840000   229.78510

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-23_16-48 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       908             230.0  R2_exit_interval
                                       908             230.0  R2_exit_interval
                                       908             230.0  R2_exit_interval
                                       908             230.0  R2_exit_interval
                                       908             230.0  R2_exit_interval

[31750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:26,723|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-26 16:46:26,750|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min:
2026-02-26 16:46:26,751|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:26,757|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:26,757|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:46:26,874|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:26,876|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:26,876|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:26,877|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
================================================================================

2026-02-26 16:46:26,929|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:26,935|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0              1.0  2.0            0.0
                                       1              1.0  2.0            0.0
                                       2              1.0  2.0            0.0
                                       3              1.0  2.0            0.0
                                       4              1.0  2.0            0.0
...                                                   ...  ...            ...
                                       1083         154.0  1.0            0.0
                                       1084         154.0  1.0            0.0
                                       1085         154.0  1.0            0.0
                                       1086         154.0  1.0            0.0
                                       1087         154.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       1083            0.0        0.0
                                       1084            0.0        0.0
                                       1085            0.0        0.0
                                       1086            0.0        0.0
                                       1087            0.0        0.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       1083           cueZone_exit
                                       1084      enter_reward1Zone
                                       1085      enter_reward2Zone
                                       1086       exit_reward1Zone
                                       1087       exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0            7560000 -118.495650
                                       1            8120000  -79.047940
                                       2           10320000   25.273493
                                       3           10800000   49.882275
                                       4           21880000  169.953950
...                                                     ...         ...
                                       1083      2499200000   25.659765
                                       1084      2499520000   49.208420
                                       1085      2501280000  169.881500
                                       1086      2500320000  110.215350
                                       1087      2502160000  230.876067

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       1083             25.0
                                       1084             50.0
                                       1085            170.0
                                       1086            110.0
                                       1087            230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-24_12-24 0         (7360000.0, 7560000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       1083                         NaN  ...
                                       1084                         NaN  ...
                                       1085                         NaN  ...
                                       1086                         NaN  ...
                                       1087                         NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (21480000.0, 23080000.0]
...                                                                       ...
                                       1083                               NaN
                                       1084                               NaN
                                       1085      (2500880000.0, 2502480000.0]
                                       1086                               NaN
                                       1087                               NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       1083                                                   None
                                       1084                                                   None
                                       1085                                                   None
                                       1086                                                   None
                                       1087                                                   None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       1083                               NaN
                                       1084                               NaN
                                       1085                               NaN
                                       1086      (2499920000.0, 2501520000.0]
                                       1087                               NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       1083                      None
                                       1084                      None
                                       1085                      None
                                       1086                      None
                                       1087                      None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       1083                               NaN
                                       1084                               NaN
                                       1085                               NaN
                                       1086                               NaN
                                       1087      (2501760000.0, 2503360000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       1083                      None
                                       1084                      None
                                       1085                      None
                                       1086                      None
                                       1087                      None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       1083                             NaN
                                       1084                             NaN
                                       1085                             NaN
                                       1086                             NaN
                                       1087                             NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       1083                                 None
                                       1084                                 None
                                       1085                                 None
                                       1086                                 None
                                       1087                                 None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       1083                             NaN
                                       1084                             NaN
                                       1085                             NaN
                                       1086                             NaN
                                       1087                             NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_12-24 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       1083                                 None
                                       1084                                 None
                                       1085                                 None
                                       1086                                 None
                                       1087                                 None

[1088 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-24_12-24
entry_id                                                   544
trial_id                                                  77.0
cue                                                        1.0
trial_outcome                                              0.0
choice_R1                                                  0.0
choice_R2                                                  1.0
t0_event_name                                enter_reward2Zone
t0                                                  1279320000
x_position                                           170.10275
x_alignment                                              170.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                 (1278920000.0, 1280520000.0]
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet
No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48

2026-02-26 16:46:29,133|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0                      7360000
                                       0                      7400000
                                       0                      7440000
                                       0                      7480000
                                       0                      7520000
...                                                               ...
                                       1087                2503160000
                                       1087                2503200000
                                       1087                2503240000
                                       1087                2503280000
                                       1087                2503320000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0                    7400000
                                       0                    7440000
                                       0                    7480000
                                       0                    7520000
                                       0                    7560000
...                                                             ...
                                       1087              2503200000
                                       1087              2503240000
                                       1087              2503280000
                                       1087              2503320000
                                       1087              2503360000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0            0.549409    -0.284915
                                       0           -0.078955    -0.138581
                                       0           -0.627608    -0.231235
                                       0            0.013704    -0.329913
                                       0           -0.029299    -0.084747
...                                                      ...          ...
                                       1087        -0.033079     0.432902
                                       1087         0.072811     0.035364
                                       1087         0.541170    -0.127371
                                       1087        -0.307647    -0.265627
                                       1087         0.083356     0.155729

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0            3.460950    -0.262884
                                       0           -0.208483    -0.092961
                                       0           -0.495549    -2.637609
                                       0           -0.385763    -0.541462
                                       0           -0.086979     0.016161
...                                                      ...          ...
                                       1087         0.647095    -0.354276
                                       1087        -0.075132    -0.186269
                                       1087        -0.062299    -0.123783
                                       1087         0.207551     0.092300
                                       1087         0.045043    -0.194967

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0            0.855928    -0.573565
                                       0            0.062997     0.417284
                                       0           -0.128014     0.599324
                                       0           -0.102027     0.438605
                                       0           -0.129059    -0.027834
...                                                      ...          ...
                                       1087        -0.411158    -0.336409
                                       1087        -0.008572     0.068825
                                       1087        -0.107044     0.183707
                                       1087         0.376362    -0.579159
                                       1087        -0.122258     0.206102

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0           -3.054527     0.331957
                                       0            0.154742    -0.016489
                                       0           -0.553816     1.676449
                                       0            1.089934     0.787120
                                       0           -0.152716    -0.057933
...                                                      ...          ...
                                       1087        -0.263443    -0.270815
                                       1087        -0.158405    -0.112236
                                       1087        -0.298827    -0.390916
                                       1087        -0.923546    -0.581990
                                       1087        -0.233618     0.287371

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-24_12-24 1100        6         0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
...                                              ...       ...  ...
                                       1087      ...     154.0  1.0
                                       1087      ...     154.0  1.0
                                       1087      ...     154.0  1.0
                                       1087      ...     154.0  1.0
                                       1087      ...     154.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
                                       0                   0.0        1.0
...                                                        ...        ...
                                       1087                0.0        0.0
                                       1087                0.0        0.0
                                       1087                0.0        0.0
                                       1087                0.0        0.0
                                       1087                0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       1087            0.0  exit_reward2Zone
                                       1087            0.0  exit_reward2Zone
                                       1087            0.0  exit_reward2Zone
                                       1087            0.0  exit_reward2Zone
                                       1087            0.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0            7560000 -118.495650
                                       0            7560000 -118.495650
                                       0            7560000 -118.495650
                                       0            7560000 -118.495650
                                       0            7560000 -118.495650
...                                                     ...         ...
                                       1087      2502160000  230.876067
                                       1087      2502160000  230.876067
                                       1087      2502160000  230.876067
                                       1087      2502160000  230.876067
                                       1087      2502160000  230.876067

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-24_12-24 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       1087            230.0  R2_exit_interval
                                       1087            230.0  R2_exit_interval
                                       1087            230.0  R2_exit_interval
                                       1087            230.0  R2_exit_interval
                                       1087            230.0  R2_exit_interval

[38500 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:31,662|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-26 16:46:31,678|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min:
2026-02-26 16:46:31,679|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:31,782|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:31,782|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:46:31,985|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:31,985|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:31,987|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:31,987|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
================================================================================

2026-02-26 16:46:32,050|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:32,058|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0              1.0  2.0            0.0
                                       1              1.0  2.0            0.0
                                       2              1.0  2.0            0.0
                                       3              1.0  2.0            0.0
                                       4              1.0  2.0            0.0
...                                                   ...  ...            ...
                                       872          124.0  1.0            0.0
                                       873          124.0  1.0            0.0
                                       874          124.0  1.0            0.0
                                       875          124.0  1.0            0.0
                                       876          124.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0               0.0        0.0
                                       1               0.0        0.0
                                       2               0.0        0.0
                                       3               0.0        0.0
                                       4               0.0        0.0
...                                                    ...        ...
                                       872             0.0        1.0
                                       873             0.0        1.0
                                       874             0.0        1.0
                                       875             0.0        1.0
                                       876             0.0        1.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       872            cueZone_exit
                                       873       enter_reward1Zone
                                       874       enter_reward2Zone
                                       875        exit_reward1Zone
                                       876        exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0            7440000 -120.549867
                                       1            7960000  -80.190570
                                       2            9480000   24.357545
                                       3           10040000   50.583883
                                       4           13560000  169.893800
...                                                     ...         ...
                                       872       2430760000   23.861537
                                       873       2431240000   49.378037
                                       874       2433440000  170.843933
                                       875       2432320000  110.523750
                                       876       2442720000  230.319400

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       872              25.0
                                       873              50.0
                                       874             170.0
                                       875             110.0
                                       876             230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-24_19-37 0         (7240000.0, 7440000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       872                          NaN  ...
                                       873                          NaN  ...
                                       874                          NaN  ...
                                       875                          NaN  ...
                                       876                          NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (13160000.0, 14760000.0]
...                                                                       ...
                                       872                                NaN
                                       873                                NaN
                                       874       (2433040000.0, 2434640000.0]
                                       875                                NaN
                                       876                                NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       872                                                    None
                                       873                                                    None
                                       874                                                    None
                                       875                                                    None
                                       876                                                    None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       872                                NaN
                                       873                                NaN
                                       874                                NaN
                                       875       (2431920000.0, 2433520000.0]
                                       876                                NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       872                       None
                                       873                       None
                                       874                       None
                                       875                       None
                                       876                       None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       872                                NaN
                                       873                                NaN
                                       874                                NaN
                                       875                                NaN
                                       876       (2442320000.0, 2443920000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       872                       None
                                       873                       None
                                       874                       None
                                       875                       None
                                       876                       None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       872                              NaN
                                       873                              NaN
                                       874                              NaN
                                       875                              NaN
                                       876                              NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       872                                  None
                                       873                                  None
                                       874                                  None
                                       875                                  None
                                       876                                  None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       872                              NaN
                                       873                              NaN
                                       874                              NaN
                                       875                              NaN
                                       876                              NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-24_19-37 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       872                                  None
                                       873                                  None
                                       874                                  None
                                       875                                  None
                                       876                                  None

[877 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-24_19-37
entry_id                                                   438
trial_id                                                  63.0
cue                                                        1.0
trial_outcome                                              0.0
choice_R1                                                  0.0
choice_R2                                                  0.0
t0_event_name                                  cueZone_visible
t0                                                  1042600000
x_position                                          -121.15635
x_alignment                                             -120.0
pre_cue_interval                  (1042400000.0, 1042600000.0]
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                (1042480000.0, 1044080000.0]
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24

2026-02-26 16:46:33,923|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0                      7240000
                                       0                      7280000
                                       0                      7320000
                                       0                      7360000
                                       0                      7400000
...                                                               ...
                                       876                 2443720000
                                       876                 2443760000
                                       876                 2443800000
                                       876                 2443840000
                                       876                 2443880000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0                    7280000
                                       0                    7320000
                                       0                    7360000
                                       0                    7400000
                                       0                    7440000
...                                                             ...
                                       876               2443760000
                                       876               2443800000
                                       876               2443840000
                                       876               2443880000
                                       876               2443920000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0            0.198804    -0.122949
                                       0            0.090918     0.228369
                                       0            0.107978    -0.025500
                                       0            0.106694    -0.112588
                                       0           -0.096884    -0.042779
...                                                      ...          ...
                                       876         -0.115243    -0.314909
                                       876         -0.117982     0.370164
                                       876         -0.003195    -0.088684
                                       876         -0.194327    -0.146405
                                       876         -0.131962     0.258311

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0           -0.131454    -0.161698
                                       0            0.381987    -0.787292
                                       0           -0.148127     0.168843
                                       0            0.054596     0.010179
                                       0           -0.014552     0.365118
...                                                      ...          ...
                                       876          1.262583    -0.744177
                                       876         -0.183170     0.514078
                                       876         -0.072590     0.162934
                                       876         -1.287710    -0.029066
                                       876         -0.268445     3.855275

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0           -0.258348    -0.011042
                                       0            0.069712    -0.325132
                                       0           -0.170689    -0.498871
                                       0           -0.074351     0.044678
                                       0           -0.068314    -0.258979
...                                                      ...          ...
                                       876          0.629296    -0.741944
                                       876         -0.270838    -0.352121
                                       876         -0.123149     0.064080
                                       876          2.215798     0.043760
                                       876         -0.445520     0.270025

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0           -0.157729    -0.100691
                                       0            1.070835    -0.096723
                                       0            0.357171     0.277184
                                       0           -0.086122     0.182101
                                       0           -0.220220    -0.038433
...                                                      ...          ...
                                       876          0.086971     0.320575
                                       876          0.408165    -0.195625
                                       876         -0.049520    -0.077719
                                       876         -0.307477     2.346582
                                       876         -0.788051    -0.201393

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-24_19-37 1100        6         0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
...                                              ...       ...  ...
                                       876       ...     124.0  1.0
                                       876       ...     124.0  1.0
                                       876       ...     124.0  1.0
                                       876       ...     124.0  1.0
                                       876       ...     124.0  1.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
...                                                        ...        ...
                                       876                 0.0        0.0
                                       876                 0.0        0.0
                                       876                 0.0        0.0
                                       876                 0.0        0.0
                                       876                 0.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
                                       0               0.0   cueZone_visible
...                                                    ...               ...
                                       876             1.0  exit_reward2Zone
                                       876             1.0  exit_reward2Zone
                                       876             1.0  exit_reward2Zone
                                       876             1.0  exit_reward2Zone
                                       876             1.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0            7440000 -120.549867
                                       0            7440000 -120.549867
                                       0            7440000 -120.549867
                                       0            7440000 -120.549867
                                       0            7440000 -120.549867
...                                                     ...         ...
                                       876       2442720000  230.319400
                                       876       2442720000  230.319400
                                       876       2442720000  230.319400
                                       876       2442720000  230.319400
                                       876       2442720000  230.319400

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-24_19-37 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       876             230.0  R2_exit_interval
                                       876             230.0  R2_exit_interval
                                       876             230.0  R2_exit_interval
                                       876             230.0  R2_exit_interval
                                       876             230.0  R2_exit_interval

[31000 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:35,641|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-26 16:46:35,653|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min:
2026-02-26 16:46:35,654|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:35,665|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:35,666|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:46:35,796|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:35,796|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:35,797|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:35,798|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-26 16:46:35,798|INFO|41770|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-26 16:46:35,799|WARNING|41770|analytics|_compute_sess_analytic
	Missing lower level analytic
2026-02-26 16:46:35,815|WARNING|41770|analytics|get_analytics
	Failed to compute EnsembleT0Projection for (1100, 6, '2025-01-25_10-55')
================================================================================

2026-02-26 16:46:35,816|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-26 16:46:35,838|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min:
2026-02-26 16:46:35,839|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:35,844|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:35,845|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:46:36,324|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:36,415|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:36,444|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:36,445|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
================================================================================

2026-02-26 16:46:36,589|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:36,607|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0              1.0  1.0            0.0
                                       1              1.0  1.0            0.0
                                       2              1.0  1.0            0.0
                                       3              1.0  1.0            0.0
                                       4              1.0  1.0            0.0
...                                                   ...  ...            ...
                                       1387         195.0  2.0            1.0
                                       1388         195.0  2.0            1.0
                                       1389         195.0  2.0            1.0
                                       1390         195.0  2.0            1.0
                                       1391         195.0  2.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0               0.0        1.0
                                       1               0.0        1.0
                                       2               0.0        1.0
                                       3               0.0        1.0
                                       4               0.0        1.0
...                                                    ...        ...
                                       1387            0.0        1.0
                                       1388            0.0        1.0
                                       1389            0.0        1.0
                                       1390            0.0        1.0
                                       1391            0.0        1.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       1387           cueZone_exit
                                       1388      enter_reward1Zone
                                       1389      enter_reward2Zone
                                       1390       exit_reward1Zone
                                       1391       exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0           10960000 -120.300550
                                       1           11600000  -81.043290
                                       2           13800000   26.184813
                                       3           14160000   49.220755
                                       4           16640000  169.795900
...                                                     ...         ...
                                       1387      3704800000   24.013680
                                       1388      3705280000   51.026950
                                       1389      3707200000  169.986350
                                       1390      3706240000  110.778150
                                       1391      3710560000  229.545800

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       1387             25.0
                                       1388             50.0
                                       1389            170.0
                                       1390            110.0
                                       1391            230.0

                                                         pre_cue_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0         (10760000.0, 10960000.0]
                                       1                              NaN
                                       2                              NaN
                                       3                              NaN
                                       4                              NaN
...                                                                   ...
                                       1387                           NaN
                                       1388                           NaN
                                       1389                           NaN
                                       1390                           NaN
                                       1391                           NaN

                                                 ...  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2025-01-25_21-29 0         ...
                                       1         ...
                                       2         ...
                                       3         ...
                                       4         ...
...                                              ...
                                       1387      ...
                                       1388      ...
                                       1389      ...
                                       1390      ...
                                       1391      ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (16240000.0, 17840000.0]
...                                                                       ...
                                       1387                               NaN
                                       1388                               NaN
                                       1389      (3706800000.0, 3708400000.0]
                                       1390                               NaN
                                       1391                               NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       1387                                                   None
                                       1388                                                   None
                                       1389                                                   None
                                       1390                                                   None
                                       1391                                                   None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       1387                               NaN
                                       1388                               NaN
                                       1389                               NaN
                                       1390      (3705840000.0, 3707440000.0]
                                       1391                               NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       1387                      None
                                       1388                      None
                                       1389                      None
                                       1390                      None
                                       1391                      None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       1387                               NaN
                                       1388                               NaN
                                       1389                               NaN
                                       1390                               NaN
                                       1391      (3710160000.0, 3711760000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       1387                      None
                                       1388                      None
                                       1389                      None
                                       1390                      None
                                       1391                      None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       1387                             NaN
                                       1388                             NaN
                                       1389                             NaN
                                       1390                             NaN
                                       1391                             NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       1387                                 None
                                       1388                                 None
                                       1389                                 None
                                       1390                                 None
                                       1391                                 None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       1387                             NaN
                                       1388                             NaN
                                       1389                             NaN
                                       1390                             NaN
                                       1391                             NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-25_21-29 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       1387                                 None
                                       1388                                 None
                                       1389                                 None
                                       1390                                 None
                                       1391                                 None

[1392 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-25_21-29
entry_id                                                   696
trial_id                                                  98.0
cue                                                        1.0
trial_outcome                                              0.0
choice_R1                                                  0.0
choice_R2                                                  1.0
t0_event_name                                enter_reward1Zone
t0                                                  1831360000
x_position                                            50.32868
x_alignment                                               50.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                 (1830960000.0, 1832560000.0]
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37

2026-02-26 16:46:39,757|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0                     10760000
                                       0                     10800000
                                       0                     10840000
                                       0                     10880000
                                       0                     10920000
...                                                               ...
                                       1391                3711560000
                                       1391                3711600000
                                       1391                3711640000
                                       1391                3711680000
                                       1391                3711720000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0                   10800000
                                       0                   10840000
                                       0                   10880000
                                       0                   10920000
                                       0                   10960000
...                                                             ...
                                       1391              3711600000
                                       1391              3711640000
                                       1391              3711680000
                                       1391              3711720000
                                       1391              3711760000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0           -0.171765    -0.414865
                                       0           -0.147423     0.311753
                                       0           -0.168946    -0.153420
                                       0            0.435540     0.103777
                                       0            0.195511    -0.165720
...                                                      ...          ...
                                       1391        -0.067821    -0.204163
                                       1391        -0.460267     0.103121
                                       1391        -0.019055    -3.136794
                                       1391        -0.074291    -0.114494
                                       1391        -0.091121     0.314776

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0           -0.411827    -0.031219
                                       0           -1.039527     0.284186
                                       0           -0.019963     2.196855
                                       0           -0.244436    -0.351616
                                       0           -0.794050    -0.688090
...                                                      ...          ...
                                       1391         0.219540     0.721431
                                       1391        -0.042229     1.673285
                                       1391        -1.421581    -3.961328
                                       1391        -0.226458    -0.381120
                                       1391         0.528959     0.952944

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0            1.508708     2.854310
                                       0           -0.803154    -1.509796
                                       0           -0.308751    -0.601654
                                       0            0.592062    -0.563021
                                       0            0.019703     2.098467
...                                                      ...          ...
                                       1391        -0.291018    -0.791364
                                       1391         3.343294     2.666059
                                       1391         1.307374     0.947435
                                       1391         0.419670     0.210041
                                       1391        -0.124101    -0.486466

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0            1.646632    -0.680016
                                       0           -0.756325     0.001235
                                       0           -0.216330    -0.118605
                                       0           -0.127154     0.010203
                                       0            0.808687    -0.062804
...                                                      ...          ...
                                       1391         0.470645     0.026948
                                       1391        -1.495694    -0.770722
                                       1391        -1.249856    -6.167075
                                       1391        -0.219247     0.078807
                                       1391        -0.280745    -0.152936

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-25_21-29 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       1391      ...     195.0  2.0
                                       1391      ...     195.0  2.0
                                       1391      ...     195.0  2.0
                                       1391      ...     195.0  2.0
                                       1391      ...     195.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
                                       0                   0.0        0.0
...                                                        ...        ...
                                       1391                1.0        0.0
                                       1391                1.0        0.0
                                       1391                1.0        0.0
                                       1391                1.0        0.0
                                       1391                1.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       1391            1.0  exit_reward2Zone
                                       1391            1.0  exit_reward2Zone
                                       1391            1.0  exit_reward2Zone
                                       1391            1.0  exit_reward2Zone
                                       1391            1.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0           10960000  -120.30055
                                       0           10960000  -120.30055
                                       0           10960000  -120.30055
                                       0           10960000  -120.30055
                                       0           10960000  -120.30055
...                                                     ...         ...
                                       1391      3710560000   229.54580
                                       1391      3710560000   229.54580
                                       1391      3710560000   229.54580
                                       1391      3710560000   229.54580
                                       1391      3710560000   229.54580

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-25_21-29 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       1391            230.0  R2_exit_interval
                                       1391            230.0  R2_exit_interval
                                       1391            230.0  R2_exit_interval
                                       1391            230.0  R2_exit_interval
                                       1391            230.0  R2_exit_interval

[48750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object

No data for session: 2025-01-26_21-48
No data for session: 2025-01-27_13-39

================================================================================

2026-02-26 16:46:42,827|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-26 16:46:42,845|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min:
2026-02-26 16:46:42,846|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:42,857|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:42,857|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:46:43,080|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:43,082|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:43,085|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:43,085|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-26 16:46:43,086|INFO|41770|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-26 16:46:43,086|WARNING|41770|analytics|_compute_sess_analytic
	Missing lower level analytic
2026-02-26 16:46:43,096|WARNING|41770|analytics|get_analytics
	Failed to compute EnsembleT0Projection for (1100, 6, '2025-01-26_13-45')
================================================================================

2026-02-26 16:46:43,097|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-26 16:46:43,107|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min:
2026-02-26 16:46:43,108|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:43,115|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:43,115|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions
2026-02-26 16:46:43,205|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:46:43,206|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:43,207|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:43,207|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

================================================================================

2026-02-26 16:46:43,363|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:46:43,371|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0              1.0  1.0            1.0
                                       1              1.0  1.0            1.0
                                       2              1.0  1.0            1.0
                                       3              1.0  1.0            1.0
                                       4              1.0  1.0            1.0
...                                                   ...  ...            ...
                                       1242         171.0  2.0            1.0
                                       1243         171.0  2.0            1.0
                                       1244         171.0  2.0            1.0
                                       1245         171.0  2.0            1.0
                                       1246         171.0  2.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       1242            1.0        1.0
                                       1243            1.0        1.0
                                       1244            1.0        1.0
                                       1245            1.0        1.0
                                       1246            1.0        1.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       1242           cueZone_exit
                                       1243      enter_reward1Zone
                                       1244      enter_reward2Zone
                                       1245       exit_reward1Zone
                                       1246       exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0            8160000 -120.989050
                                       1            8920000  -79.028413
                                       2           11360000   24.328250
                                       3           11840000   49.485977
                                       4           20600000  169.942400
...                                                     ...         ...
                                       1242      3340360000   25.544370
                                       1243      3340920000   49.937785
                                       1244      3344480000  169.685650
                                       1245      3343360000  109.259567
                                       1246      3348160000  230.027467

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       1242             25.0
                                       1243             50.0
                                       1244            170.0
                                       1245            110.0
                                       1246            230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-26_21-48 0         (7960000.0, 8160000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       1242                         NaN  ...
                                       1243                         NaN  ...
                                       1244                         NaN  ...
                                       1245                         NaN  ...
                                       1246                         NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (20200000.0, 21800000.0]
...                                                                       ...
                                       1242                               NaN
                                       1243                               NaN
                                       1244      (3344080000.0, 3345680000.0]
                                       1245                               NaN
                                       1246                               NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       1242                                                   None
                                       1243                                                   None
                                       1244                                                   None
                                       1245                                                   None
                                       1246                                                   None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       1242                               NaN
                                       1243                               NaN
                                       1244                               NaN
                                       1245      (3342960000.0, 3344560000.0]
                                       1246                               NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       1242                      None
                                       1243                      None
                                       1244                      None
                                       1245                      None
                                       1246                      None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       1242                               NaN
                                       1243                               NaN
                                       1244                               NaN
                                       1245                               NaN
                                       1246      (3347760000.0, 3349360000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       1242                      None
                                       1243                      None
                                       1244                      None
                                       1245                      None
                                       1246                      None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       1242                             NaN
                                       1243                             NaN
                                       1244                             NaN
                                       1245                             NaN
                                       1246                             NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       1242                                 None
                                       1243                                 None
                                       1244                                 None
                                       1245                                 None
                                       1246                                 None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       1242                             NaN
                                       1243                             NaN
                                       1244                             NaN
                                       1245                             NaN
                                       1246                             NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-26_21-48 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       1242                                 None
                                       1243                                 None
                                       1244                                 None
                                       1245                                 None
                                       1246                                 None

[1247 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-26_21-48
entry_id                                                   623
trial_id                                                  86.0
cue                                                        1.0
trial_outcome                                              1.0
choice_R1                                                  1.0
choice_R2                                                  1.0
t0_event_name                                 exit_reward2Zone
t0                                                  1603360000
x_position                                            230.5502
x_alignment                                              230.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                                          NaN
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                  (1602960000.0, 1604560000.0]
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-27_13-39

2026-02-26 16:46:46,000|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0                      7960000
                                       0                      8000000
                                       0                      8040000
                                       0                      8080000
                                       0                      8120000
...                                                               ...
                                       1246                3349160000
                                       1246                3349200000
                                       1246                3349240000
                                       1246                3349280000
                                       1246                3349320000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0                    8000000
                                       0                    8040000
                                       0                    8080000
                                       0                    8120000
                                       0                    8160000
...                                                             ...
                                       1246              3349200000
                                       1246              3349240000
                                       1246              3349280000
                                       1246              3349320000
                                       1246              3349360000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0            0.025160    -0.272000
                                       0           -0.124553     0.145182
                                       0           -0.434355    -0.887208
                                       0            1.284901    -0.129857
                                       0            0.074901    -0.114881
...                                                      ...          ...
                                       1246        -0.108624    -0.290540
                                       1246        -0.673280     1.102347
                                       1246         0.130736    -0.157915
                                       1246        -0.460158     0.888805
                                       1246        -0.006781     0.145974

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0            0.143903    -0.566240
                                       0           -0.237244    -0.426785
                                       0            0.239083     0.423124
                                       0           -0.113810    -0.261596
                                       0            0.095875    -0.135035
...                                                      ...          ...
                                       1246        -0.127254     0.280079
                                       1246         0.335672     0.790831
                                       1246         0.663785    -0.219577
                                       1246         0.567389     2.259329
                                       1246        -0.076386    -0.023925

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0            2.239526    -0.720687
                                       0           -0.223241     0.878867
                                       0           -0.766769     3.968722
                                       0           -0.173488     0.205536
                                       0           -0.054682     0.439128
...                                                      ...          ...
                                       1246         0.066320    -0.065941
                                       1246        -0.195599    -0.048577
                                       1246        -0.077434     0.334997
                                       1246        -0.013471    -0.314433
                                       1246         0.088966    -0.128907

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0            0.960828    -1.208582
                                       0           -0.352480     0.727762
                                       0           -2.555391     0.671086
                                       0           -0.432366    -0.768199
                                       0           -0.104731    -0.097739
...                                                      ...          ...
                                       1246        -0.420462    -0.056591
                                       1246        -0.191997    -0.621633
                                       1246         0.548420     0.339846
                                       1246        -0.944470     0.170725
                                       1246        -0.080742    -0.049049

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-26_21-48 1100        6         0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
                                       0         ...       1.0  1.0
...                                              ...       ...  ...
                                       1246      ...     171.0  2.0
                                       1246      ...     171.0  2.0
                                       1246      ...     171.0  2.0
                                       1246      ...     171.0  2.0
                                       1246      ...     171.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
...                                                        ...        ...
                                       1246                1.0        1.0
                                       1246                1.0        1.0
                                       1246                1.0        1.0
                                       1246                1.0        1.0
                                       1246                1.0        1.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       1246            1.0  exit_reward2Zone
                                       1246            1.0  exit_reward2Zone
                                       1246            1.0  exit_reward2Zone
                                       1246            1.0  exit_reward2Zone
                                       1246            1.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0            8160000 -120.989050
                                       0            8160000 -120.989050
                                       0            8160000 -120.989050
                                       0            8160000 -120.989050
                                       0            8160000 -120.989050
...                                                     ...         ...
                                       1246      3348160000  230.027467
                                       1246      3348160000  230.027467
                                       1246      3348160000  230.027467
                                       1246      3348160000  230.027467
                                       1246      3348160000  230.027467

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-26_21-48 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       1246            230.0  R2_exit_interval
                                       1246            230.0  R2_exit_interval
                                       1246            230.0  R2_exit_interval
                                       1246            230.0  R2_exit_interval
                                       1246            230.0  R2_exit_interval

[42750 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object
================================================================================

2026-02-26 16:46:50,101|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
2026-02-26 16:46:50,154|DEBUG|41770|analytics|_compute_sess_analytic
	Computing EnsembleT0Projection for 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min:
2026-02-26 16:46:50,155|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:46:50,170|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:46:50,171|DEBUG|41770|analytics|get_analytics
	Processing ConcatenatedEnsambleProj40ms, for n=1 sessions

/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min/../../animal_analytics/ConcatenatedEnsambleProj40ms.parquet

2026-02-26 16:47:11,452|INFO|41770|analytics|get_analytics
	Loaded animal-level analytic `ConcatenatedEnsambleProj40ms` last modified on 2026-02-05T15:20:02.204022
2026-02-26 16:47:11,455|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 16:47:11,464|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 1 sessions

2026-02-26 16:47:11,465|DEBUG|41770|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-26 16:47:11,514|INFO|41770|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 1 sessions.
2026-02-26 16:47:11,523|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0              1.0  2.0            1.0
                                       1              1.0  2.0            1.0
                                       2              1.0  2.0            1.0
                                       3              1.0  2.0            1.0
                                       4              1.0  2.0            1.0
...                                                   ...  ...            ...
                                       1104         152.0  2.0            1.0
                                       1105         152.0  2.0            1.0
                                       1106         152.0  2.0            1.0
                                       1107         152.0  2.0            1.0
                                       1108         152.0  2.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0               1.0        1.0
                                       1               1.0        1.0
                                       2               1.0        1.0
                                       3               1.0        1.0
                                       4               1.0        1.0
...                                                    ...        ...
                                       1104            0.0        1.0
                                       1105            0.0        1.0
                                       1106            0.0        1.0
                                       1107            0.0        1.0
                                       1108            0.0        1.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                                       1104           cueZone_exit
                                       1105      enter_reward1Zone
                                       1106      enter_reward2Zone
                                       1107       exit_reward1Zone
                                       1108       exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0            8200000 -120.596633
                                       1           10000000  -80.352480
                                       2           16080000   24.997480
                                       3           17760000   49.916965
                                       4           27640000  170.081700
...                                                     ...         ...
                                       1104      4396000000   25.843260
                                       1105      4396480000   49.770475
                                       1106      4398880000  170.561500
                                       1107      4397720000  109.711900
                                       1108      4401200000  229.449700

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                                       1104             25.0
                                       1105             50.0
                                       1106            170.0
                                       1107            110.0
                                       1108            230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2025-01-27_13-39 0         (8000000.0, 8200000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                                       1104                         NaN  ...
                                       1105                         NaN  ...
                                       1106                         NaN  ...
                                       1107                         NaN  ...
                                       1108                         NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4             (27240000.0, 28840000.0]
...                                                                       ...
                                       1104                               NaN
                                       1105                               NaN
                                       1106      (4398480000.0, 4400080000.0]
                                       1107                               NaN
                                       1108                               NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                                       1104                                                   None
                                       1105                                                   None
                                       1106                                                   None
                                       1107                                                   None
                                       1108                                                   None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       1104                               NaN
                                       1105                               NaN
                                       1106                               NaN
                                       1107      (4397320000.0, 4398920000.0]
                                       1108                               NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       1104                      None
                                       1105                      None
                                       1106                      None
                                       1107                      None
                                       1108                      None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                                       1104                               NaN
                                       1105                               NaN
                                       1106                               NaN
                                       1107                               NaN
                                       1108      (4400800000.0, 4402400000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                                       1104                      None
                                       1105                      None
                                       1106                      None
                                       1107                      None
                                       1108                      None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       1104                             NaN
                                       1105                             NaN
                                       1106                             NaN
                                       1107                             NaN
                                       1108                             NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       1104                                 None
                                       1105                                 None
                                       1106                                 None
                                       1107                                 None
                                       1108                                 None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                                       1104                             NaN
                                       1105                             NaN
                                       1106                             NaN
                                       1107                             NaN
                                       1108                             NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2025-01-27_13-39 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None
...                                                                          ...
                                       1104                                 None
                                       1105                                 None
                                       1106                                 None
                                       1107                                 None
                                       1108                                 None

[1109 rows x 29 columns]
paradigm_id                                               1100
animal_id                                                    6
session_id                                    2025-01-27_13-39
entry_id                                                   554
trial_id                                                  76.0
cue                                                        1.0
trial_outcome                                              0.0
choice_R1                                                  0.0
choice_R2                                                  1.0
t0_event_name                                enter_reward2Zone
t0                                                  2134000000
x_position                                             169.781
x_alignment                                              170.0
pre_cue_interval                                           NaN
pre_cue_interval_bins                                     None
nextto_cue_interval                                        NaN
nextto_cue_interval_bins                                  None
cue_entry_interval                                         NaN
cue_entry_interval_bins                                   None
cue_exit_interval                                          NaN
cue_exit_interval_bins                                    None
R1_entry_interval                                          NaN
R1_entry_interval_bins                                    None
R2_entry_interval                 (2133600000.0, 2135200000.0]
R2_entry_interval_bins                                    None
R1_exit_interval                                           NaN
R1_exit_interval_bins                                     None
R2_exit_interval                                           NaN
R2_exit_interval_bins                                     None
reward1_valve_open_interval                                NaN
reward1_valve_open_interval_bins                          None
reward2_valve_open_interval                                NaN
reward2_valve_open_interval_bins                          None

No data for session: 2024-11-14_16-40
No data for session: 2024-11-15_15-48
No data for session: 2024-11-20_17-46
No data for session: 2024-11-21_17-22
No data for session: 2024-11-25_16-25
No data for session: 2024-11-26_16-39
No data for session: 2024-11-28_17-41
No data for session: 2024-11-29_17-21
No data for session: 2024-12-02_16-09
No data for session: 2024-12-03_16-23
No data for session: 2024-12-04_18-06
No data for session: 2024-12-06_16-49
No data for session: 2024-12-09_17-45
No data for session: 2024-12-10_17-20
No data for session: 2024-12-11_17-42
No data for session: 2024-12-12_16-13
No data for session: 2024-12-13_17-10
No data for session: 2025-01-14_18-08
No data for session: 2025-01-15_17-18
No data for session: 2025-01-16_17-47
No data for session: 2025-01-17_16-55
No data for session: 2025-01-21_18-49
No data for session: 2025-01-22_17-51
No data for session: 2025-01-23_16-48
No data for session: 2025-01-24_12-24
No data for session: 2025-01-24_19-37
No data for session: 2025-01-25_21-29
No data for session: 2025-01-26_21-48

2026-02-26 16:47:13,723|DEBUG|41770|analytics|_compute_sess_analytic
	Computed analytic EnsembleT0Projection:
                                                 from_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0                      8000000
                                       0                      8040000
                                       0                      8080000
                                       0                      8120000
                                       0                      8160000
...                                                               ...
                                       1108                4402200000
                                       1108                4402240000
                                       1108                4402280000
                                       1108                4402320000
                                       1108                4402360000

                                                 to_ephys_timestamp  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0                    8040000
                                       0                    8080000
                                       0                    8120000
                                       0                    8160000
                                       0                    8200000
...                                                             ...
                                       1108              4402240000
                                       1108              4402280000
                                       1108              4402320000
                                       1108              4402360000
                                       1108              4402400000

                                                 Assembly001  Assembly002  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0            0.079839    -0.305053
                                       0           -0.042934     0.026102
                                       0            0.165075     0.095812
                                       0            0.329630     0.101751
                                       0            0.163835    -0.250025
...                                                      ...          ...
                                       1108         0.018032    -0.425217
                                       1108        -0.161524     0.784179
                                       1108        -0.053947    -0.126021
                                       1108        -0.077455    -0.351810
                                       1108         0.005057     0.036111

                                                 Assembly003  Assembly004  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0           -0.318668    -1.367933
                                       0            0.020024     0.259658
                                       0           -0.225539     0.332391
                                       0           -0.228189    -0.017287
                                       0            0.277860    -1.137033
...                                                      ...          ...
                                       1108         0.453529    -0.392653
                                       1108         0.100941    -0.860001
                                       1108         0.913100     1.616778
                                       1108         4.636653    -0.125254
                                       1108         0.180242     0.439290

                                                 Assembly005  Assembly006  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0           -0.286269    -0.116629
                                       0            0.204184    -0.722144
                                       0           -0.155173    -0.103708
                                       0           -0.437331     0.645012
                                       0           -0.267621    -0.264177
...                                                      ...          ...
                                       1108         0.965303     1.896331
                                       1108        -0.681862    -1.390363
                                       1108        -0.541986    -0.329676
                                       1108        -1.157996    -0.126453
                                       1108        -0.119962    -0.211053

                                                 Assembly007  Assembly008  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0           -0.943241    -0.259747
                                       0            0.200062    -0.117542
                                       0           -0.138162     0.175818
                                       0           -0.176793     0.085317
                                       0           -0.434675     0.085451
...                                                      ...          ...
                                       1108        -0.488662     0.203128
                                       1108         1.958204    -1.515878
                                       1108         0.572239    -0.119326
                                       1108        -0.267539    -0.106393
                                       1108        -0.060047    -0.202716

                                                 ...  trial_id  cue  \
session_id       paradigm_id animal_id entry_id  ...
2025-01-27_13-39 1100        6         0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
                                       0         ...       1.0  2.0
...                                              ...       ...  ...
                                       1108      ...     152.0  2.0
                                       1108      ...     152.0  2.0
                                       1108      ...     152.0  2.0
                                       1108      ...     152.0  2.0
                                       1108      ...     152.0  2.0

                                                 trial_outcome  choice_R1  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
                                       0                   1.0        1.0
...                                                        ...        ...
                                       1108                1.0        0.0
                                       1108                1.0        0.0
                                       1108                1.0        0.0
                                       1108                1.0        0.0
                                       1108                1.0        0.0

                                                 choice_R2     t0_event_name  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
                                       0               1.0   cueZone_visible
...                                                    ...               ...
                                       1108            1.0  exit_reward2Zone
                                       1108            1.0  exit_reward2Zone
                                       1108            1.0  exit_reward2Zone
                                       1108            1.0  exit_reward2Zone
                                       1108            1.0  exit_reward2Zone

                                                         t0  x_position  \
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0            8200000 -120.596633
                                       0            8200000 -120.596633
                                       0            8200000 -120.596633
                                       0            8200000 -120.596633
                                       0            8200000 -120.596633
...                                                     ...         ...
                                       1108      4401200000  229.449700
                                       1108      4401200000  229.449700
                                       1108      4401200000  229.449700
                                       1108      4401200000  229.449700
                                       1108      4401200000  229.449700

                                                 x_alignment     interval_name
session_id       paradigm_id animal_id entry_id
2025-01-27_13-39 1100        6         0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
                                       0              -120.0  pre_cue_interval
...                                                      ...               ...
                                       1108            230.0  R2_exit_interval
                                       1108            230.0  R2_exit_interval
                                       1108            230.0  R2_exit_interval
                                       1108            230.0  R2_exit_interval
                                       1108            230.0  R2_exit_interval

[38000 rows x 35 columns]
from_ephys_timestamp     uint64
to_ephys_timestamp       uint64
Assembly001             float64
Assembly002             float64
Assembly003             float64
Assembly004             float64
Assembly005             float64
Assembly006             float64
Assembly007             float64
Assembly008             float64
Assembly009             float64
Assembly010             float64
Assembly011             float64
Assembly012             float64
Assembly013             float64
Assembly014             float64
Assembly015             float64
Assembly016             float64
Assembly017             float64
Assembly018             float64
Assembly019             float64
Assembly020             float64
Assembly021             float64
Assembly022             float64
Assembly023             float64
trial_id                float64
cue                     float64
trial_outcome           float64
choice_R1               float64
choice_R2               float64
t0_event_name            object
t0                        int64
x_position              float64
x_alignment             float64
interval_name            object
dtype: object
================================================================================

In [11]:
t0_ens = analytics.get_analytics('EnsembleT0Projection', session_names=session_names, )
t0_ens

2026-02-26 17:06:14,488|DEBUG|41770|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-26 17:06:14,832|DEBUG|41770|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-26 17:06:14,833|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:14,880|INFO|41770|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-26 17:06:14,881|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-26 17:06:15,472|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-26 17:06:16,289|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-26 17:06:16,778|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-26 17:06:17,163|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-26 17:06:17,192|INFO|41770|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-26 17:06:17,193|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-26 17:06:17,784|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-26 17:06:18,289|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-26 17:06:18,299|INFO|41770|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-26 17:06:18,300|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:19,106|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-26 17:06:19,702|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:20,393|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:21,118|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-26 17:06:21,599|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-26 17:06:22,115|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:22,573|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-26 17:06:23,048|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:23,652|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:24,159|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:24,749|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:25,560|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-26 17:06:26,408|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-26 17:06:27,338|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-26 17:06:28,333|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-26 17:06:29,144|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-26 17:06:29,265|INFO|41770|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-26 17:06:29,266|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-26 17:06:31,216|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-26 17:06:31,229|INFO|41770|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-26 17:06:31,229|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-26 17:06:32,512|DEBUG|41770|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-26 17:06:33,618|INFO|41770|analytics|get_analytics
	Returning EnsembleT0Projection for 25 sessions.
2026-02-26 17:06:33,791|DEBUG|41770|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      4400000
                                       1                      4440000
                                       2                      4480000
                                       3                      4520000
                                       4                      4560000
...                                                               ...
                      2025-01-27_13-39 37995               4402200000
                                       37996               4402240000
                                       37997               4402280000
                                       37998               4402320000
                                       37999               4402360000

                                                 to_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    4440000
                                       1                    4480000
                                       2                    4520000
                                       3                    4560000
                                       4                    4600000
...                                                             ...
                      2025-01-27_13-39 37995             4402240000
                                       37996             4402280000
                                       37997             4402320000
                                       37998             4402360000
                                       37999             4402400000

                                                 Assembly001  Assembly002  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.044591    -0.079732
                                       1            0.353522    -0.208656
                                       2           -0.090020    -0.381483
                                       3           -0.082682    -0.003392
                                       4            0.169519    -0.213003
...                                                      ...          ...
                      2025-01-27_13-39 37995        0.018032    -0.425217
                                       37996       -0.161524     0.784179
                                       37997       -0.053947    -0.126021
                                       37998       -0.077455    -0.351810
                                       37999        0.005057     0.036111

                                                 Assembly003  Assembly004  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.117157    -0.100619
                                       1           -0.050525    -0.098752
                                       2            0.185447     1.103287
                                       3            0.093962    -0.152654
                                       4           -0.009496    -0.107002
...                                                      ...          ...
                      2025-01-27_13-39 37995        0.453529    -0.392653
                                       37996        0.100941    -0.860001
                                       37997        0.913100     1.616778
                                       37998        4.636653    -0.125254
                                       37999        0.180242     0.439290

                                                 Assembly005  Assembly006  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.049611    -0.245620
                                       1            0.562233     0.299666
                                       2           -1.082371     1.418429
                                       3           -0.208707     0.906473
                                       4           -0.100514    -0.125251
...                                                      ...          ...
                      2025-01-27_13-39 37995        0.965303     1.896331
                                       37996       -0.681862    -1.390363
                                       37997       -0.541986    -0.329676
                                       37998       -1.157996    -0.126453
                                       37999       -0.119962    -0.211053

                                                 Assembly007  Assembly008  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            1.360649    -0.219548
                                       1           -0.155457    -0.102385
                                       2           -0.112464    -0.994913
                                       3           -0.094875    -0.003057
                                       4           -0.154239     0.000961
...                                                      ...          ...
                      2025-01-27_13-39 37995       -0.488662     0.203128
                                       37996        1.958204    -1.515878
                                       37997        0.572239    -0.119326
                                       37998       -0.267539    -0.106393
                                       37999       -0.060047    -0.202716

                                                 ...  trial_id  cue  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 0         ...       1.0  1.0
                                       1         ...       1.0  1.0
                                       2         ...       1.0  1.0
                                       3         ...       1.0  1.0
                                       4         ...       1.0  1.0
...                                              ...       ...  ...
                      2025-01-27_13-39 37995     ...     152.0  2.0
                                       37996     ...     152.0  2.0
                                       37997     ...     152.0  2.0
                                       37998     ...     152.0  2.0
                                       37999     ...     152.0  2.0

                                                 trial_outcome  choice_R1  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                   0.0        0.0
                                       1                   0.0        0.0
                                       2                   0.0        0.0
                                       3                   0.0        0.0
                                       4                   0.0        0.0
...                                                        ...        ...
                      2025-01-27_13-39 37995               1.0        0.0
                                       37996               1.0        0.0
                                       37997               1.0        0.0
                                       37998               1.0        0.0
                                       37999               1.0        0.0

                                                 choice_R2     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0   cueZone_visible
                                       1               0.0   cueZone_visible
                                       2               0.0   cueZone_visible
                                       3               0.0   cueZone_visible
                                       4               0.0   cueZone_visible
...                                                    ...               ...
                      2025-01-27_13-39 37995           1.0  exit_reward2Zone
                                       37996           1.0  exit_reward2Zone
                                       37997           1.0  exit_reward2Zone
                                       37998           1.0  exit_reward2Zone
                                       37999           1.0  exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            4600000 -119.732067
                                       1            4600000 -119.732067
                                       2            4600000 -119.732067
                                       3            4600000 -119.732067
                                       4            4600000 -119.732067
...                                                     ...         ...
                      2025-01-27_13-39 37995     4401200000  229.449700
                                       37996     4401200000  229.449700

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      4400000
                                       1                      4440000
                                       2                      4480000
                                       3                      4520000
                                       4                      4560000
...                                                               ...
                      2025-01-27_13-39 37995               4402200000
                                       37996               4402240000
                                       37997               4402280000
                                       37998               4402320000
                                       37999               4402360000

                                                 to_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    4440000
                                       1                    4480000
                                       2                    4520000
                                       3                    4560000
                                       4                    4600000
...                                                             ...
                      2025-01-27_13-39 37995             4402240000
                                       37996             4402280000
                                       37997             4402320000
                                       37998             4402360000
                                       37999             4402400000

                                                 Assembly001  Assembly002  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.044591    -0.079732
                                       1            0.353522    -0.208656
                                       2           -0.090020    -0.381483
                                       3           -0.082682    -0.003392
                                       4            0.169519    -0.213003
...                                                      ...          ...
                      2025-01-27_13-39 37995        0.018032    -0.425217
                                       37996       -0.161524     0.784179
                                       37997       -0.053947    -0.126021
                                       37998       -0.077455    -0.351810
                                       37999        0.005057     0.036111

                                                 Assembly003  Assembly004  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.117157    -0.100619
                                       1           -0.050525    -0.098752
                                       2            0.185447     1.103287
                                       3            0.093962    -0.152654
                                       4           -0.009496    -0.107002
...                                                      ...          ...
                      2025-01-27_13-39 37995        0.453529    -0.392653
                                       37996        0.100941    -0.860001
                                       37997        0.913100     1.616778
                                       37998        4.636653    -0.125254
                                       37999        0.180242     0.439290

                                                 Assembly005  Assembly006  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.049611    -0.245620
                                       1            0.562233     0.299666
                                       2           -1.082371     1.418429
                                       3           -0.208707     0.906473
                                       4           -0.100514    -0.125251
...                                                      ...          ...
                      2025-01-27_13-39 37995        0.965303     1.896331
                                       37996       -0.681862    -1.390363
                                       37997       -0.541986    -0.329676
                                       37998       -1.157996    -0.126453
                                       37999       -0.119962    -0.211053

                                                 Assembly007  Assembly008  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            1.360649    -0.219548
                                       1           -0.155457    -0.102385
                                       2           -0.112464    -0.994913
                                       3           -0.094875    -0.003057
                                       4           -0.154239     0.000961
...                                                      ...          ...
                      2025-01-27_13-39 37995       -0.488662     0.203128
                                       37996        1.958204    -1.515878
                                       37997        0.572239    -0.119326
                                       37998       -0.267539    -0.106393
                                       37999       -0.060047    -0.202716

                                                 ...  trial_id  cue  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 0         ...       1.0  1.0
                                       1         ...       1.0  1.0
                                       2         ...       1.0  1.0
                                       3         ...       1.0  1.0
                                       4         ...       1.0  1.0
...                                              ...       ...  ...
                      2025-01-27_13-39 37995     ...     152.0  2.0
                                       37996     ...     152.0  2.0
                                       37997     ...     152.0  2.0
                                       37998     ...     152.0  2.0
                                       37999     ...     152.0  2.0

                                                 trial_outcome  choice_R1  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                   0.0        0.0
                                       1                   0.0        0.0
                                       2                   0.0        0.0
                                       3                   0.0        0.0
                                       4                   0.0        0.0
...                                                        ...        ...
                      2025-01-27_13-39 37995               1.0        0.0
                                       37996               1.0        0.0
                                       37997               1.0        0.0
                                       37998               1.0        0.0
                                       37999               1.0        0.0

                                                 choice_R2     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0   cueZone_visible
                                       1               0.0   cueZone_visible
                                       2               0.0   cueZone_visible
                                       3               0.0   cueZone_visible
                                       4               0.0   cueZone_visible
...                                                    ...               ...
                      2025-01-27_13-39 37995           1.0  exit_reward2Zone
                                       37996           1.0  exit_reward2Zone
                                       37997           1.0  exit_reward2Zone
                                       37998           1.0  exit_reward2Zone
                                       37999           1.0  exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            4600000 -119.732067
                                       1            4600000 -119.732067
                                       2            4600000 -119.732067
                                       3            4600000 -119.732067
                                       4            4600000 -119.732067
...                                                     ...         ...
                      2025-01-27_13-39 37995     4401200000  229.449700
                                       37996     4401200000  229.449700
                                       37997     4401200000  229.449700
                                       37998     4401200000  229.449700
                                       37999     4401200000  229.449700

                                                 x_alignment     interval_name
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              -120.0  pre_cue_interval
                                       1              -120.0  pre_cue_interval
                                       2              -120.0  pre_cue_interval
                                       3              -120.0  pre_cue_interval
                                       4              -120.0  pre_cue_interval
...                                                      ...               ...
                      2025-01-27_13-39 37995           230.0  R2_exit_interval
                                       37996           230.0  R2_exit_interval
                                       37997           230.0  R2_exit_interval
                                       37998           230.0  R2_exit_interval
                                       37999           230.0  R2_exit_interval

[679000 rows x 35 columns]