In [1]:
import os
import sys
import re
import numpy as np
import pandas as pd
import plotly.express as px
import scipy.stats as stats
from scipy.stats import pearsonr
from dash import html, dcc, Input, Output, Dash
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots

sys.path.append(os.path.join(os.getcwd(), '..', '..', '..'))
from baseVR.base_functionality import init_import_paths
init_import_paths() 

from CustomLogger import CustomLogger as Logger
from analytics_processing import analytics

from analytics_processing.sessions_from_nas_parsing import sessionlist_fullfnames_from_args, fullfnames2snames
from dashsrc.plot_components.plots import plot_TrackFiringRate
from dashsrc.plot_components.plots import plot_unit_fr_stability

In [2]:
Logger().init_logger(None, None, logging_level="DEBUG")
animal_ids = [6]
paradigm = [1100]
session_range = [1,33]
session_ids = None
normalize = True
smooth = False
excl_session_names =  ['2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min', '2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min', '2025-01-22_17-51_rYL006_P1100_LinearTrackStop_5min', '2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min'] # ignore short sessions (10, 24,25)

session_dirs = sessionlist_fullfnames_from_args(paradigm, animal_ids, session_ids, excl_session_names=excl_session_names)[0]
session_names= fullfnames2snames(session_dirs)

2026-02-28 15:58:06,256|DEBUG|53778|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Searching NAS for applicable sessions...
2026-02-28 15:58:06,513|DEBUG|53778|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Session 2024-11-29_17-21_rYL006_P1100_LinearTrackStop_28min.hdf5 excluded
2026-02-28 15:58:06,661|DEBUG|53778|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Session 2024-12-11_17-42_rYL006_P1100_LinearTrackStop_30min.hdf5 excluded
2026-02-28 15:58:06,807|DEBUG|53778|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Session 2025-01-21_18-49_rYL006_P1100_LinearTrackStop_30min.hdf5 excluded
2026-02-28 15:58:06,829|DEBUG|53778|sessions_from_nas_parsing|get_sessionlist_fullfnames
	Session 2025-01-22_17-51_rYL006_P1100_LinearTrackStop_5min.hdf5 excluded
2026-02-28 15:58:07,012|DEBUG|53778|sessions_from_nas_parsing|get_sessionlist_fullfnames
	For paradigms [1100], animals [6], found 30 sessions.
2026-02-28 15:58:07,012|DEBUG|53778|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: [1100], animal_ids: [6], session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

In [3]:
# firing rates and behavior data
fr = analytics.get_analytics('FiringRate40msHz', session_names=session_names)
fr_track = analytics.get_analytics('FiringRateTrackwiseHz', session_names=session_names)
# fr_z_scored  = analytics.get_analytics('FiringRate40msZ', session_names=session_names)
fr_z_all_sess = fr.apply(lambda unit_fr: ((unit_fr - unit_fr.mean()) / unit_fr.std()))
behav = analytics.get_analytics('BehaviorTrackwise', session_names=session_names)
# behav.index = behav.index.droplevel(('animal_id', 'paradigm_id', 'entry_id'))

2026-02-28 15:58:07,019|DEBUG|53778|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-28 15:58:07,208|DEBUG|53778|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-28 15:58:07,209|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:07,215|INFO|53778|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-28 15:58:07,215|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-28 15:58:07,476|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-28 15:58:07,750|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-28 15:58:07,914|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-28 15:58:08,097|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-28 15:58:08,104|INFO|53778|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-28 15:58:08,104|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-28 15:58:08,236|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-28 15:58:08,402|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-28 15:58:08,414|INFO|53778|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-28 15:58:08,415|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:08,620|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-28 15:58:08,827|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:09,026|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:09,229|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-28 15:58:09,416|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-28 15:58:09,631|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:09,837|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-28 15:58:10,038|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:10,251|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:10,481|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:10,685|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:10,899|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:58:11,101|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-28 15:58:11,380|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-28 15:58:11,668|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-28 15:58:11,944|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-28 15:58:11,951|INFO|53778|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-28 15:58:11,951|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-28 15:58:12,380|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-28 15:58:12,386|INFO|53778|analytics|get_analytics
	Analytic `FiringRate40msHz` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-28 15:58:12,386|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-28 15:58:12,756|DEBUG|53778|analytics|get_analytics
	Processing FiringRate40msHz, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-28 15:58:13,603|INFO|53778|analytics|get_analytics
	Returning FiringRate40msHz for 25 sessions.
2026-02-28 15:58:13,722|DEBUG|53778|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 Unit0001  Unit0002  Unit0003  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0004  Unit0005  Unit0006  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0007  Unit0008  Unit0009  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898           0         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0010  ...  Unit0070  \
paradigm_id animal_id session_id       entry_id            ...
1100        6         2024-11-14_16-40 0                0  ...         0
                                       1                0  ...         0
                                       2                0  ...         0
                                       3                0  ...         0
                                       4                0  ...         0
...                                                   ...  ...       ...
                      2025-01-27_13-39 110898           0  ...         0
                                       110899           0  ...         0
                                       110900           0  ...         0
                                       110901           0  ...         0
                                       110902           0  ...        25

                                                 Unit0071  Unit0072  Unit0073  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898          25         0         0
                                       110899          25         0         0
                                       110900          25         0         0
                                       110901           0         0         0
                                       110902           0         0         0

                                                 Unit0074  Unit0075  Unit0076  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0         0         0
                                       1                0         0         0
                                       2                0         0         0
                                       3                0         0         0
                                       4                0         0         0
...                                                   ...       ...       ...
                      2025-01-27_13-39 110898          50         0         0
                                       110899           0         0         0
                                       110900           0         0         0
                                       110901           0         0         0
                                       110902           0        25         0

                                                 Unit0077  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                0
                                       1                0
                                       2                0
                                       3                0
                                       4                0
...                                                   ...
                      2025-01-27_13-39 110898           0
                                       110899           0
                                       110900           0
                                       110901           0
                                       110902           0

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                            0
                                       1                        40000
                                       2                        80000
                                       3                       120000
                                       4                       160000
...                                                               ...
                      2025-01-27_13-39 110898              4435920000
                                       110899              4435960000
                                       110900              4436000000
                                       110901              4436040000
                                       110902              4436080000

                                                 to_ephys_timestamp
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      40000
                                       1                      80000
                                       2                     120000
                                       3                     160000
                                       4                     200000
...                                                             ...
                      2025-01-27_13-39 110898            4435960000
                                       110899            4436000000
                                       110900            4436040000
                                       110901            4436080000
                                       110902            4436120000

[1272389 rows x 79 columns]
paradigm_id                      1100
animal_id                           6
session_id           2025-01-14_18-08
entry_id                        21644
Unit0001                         25.0
Unit0002                          0.0
Unit0003                          0.0
Unit0004                          0.0
Unit0005                         25.0
...                               ...
Unit0075                         25.0
Unit0076                          0.0
Unit0077                          0.0
from_ephys_timestamp      865760000.0
to_ephys_timestamp        865800000.0

[79 rows x 1 columns]
2026-02-28 15:58:13,727|DEBUG|53778|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...

In [4]:
behav.keys()

Index(['from_position_bin', 'to_position_bin', 'posbin_position',
       'posbin_velocity', 'posbin_acc', 'posbin_raw', 'posbin_yaw',
       'posbin_pitch', 'posbin_raw_500msMedian', 'posbin_yaw_500msMedian',
       'posbin_pitch_500msMedian', 'posbin_raw_abs_acc_500msMedian',
       'posbin_yaw_abs_acc_500msMedian', 'posbin_pitch_abs_acc_500msMedian',
       'posbin_RawYawPitch_abs_vel_sum',
       'posbin_RawYawPitch_abs_vel_sum_500msMedian',
       'posbin_RawYawPitch_abs_acc_sum_500msMedian',
       'posbin_YawPitch_abs_vel_sum_500msMedian',
       'posbin_YawPitch_abs_acc_sum_500msMedian', 'forward_vs_rotation_corr',
       'posbin_forward_prop', 'posbin_below_velocity_thr',
       'facecam_pose_nose_neck_body1_angle_velocity',
       'facecam_pose_body1_body2_body3_angle_velocity',
       'velocity_threshold_at_R1', 'velocity_threshold_at_R2',
       'facecam_pose_nose_x', 'facecam_pose_nose_y',
       'facecam_pose_nose_likelihood', 'facecam_pose_neck_x',
       'facecam_pose_neck_y', 'facecam_pose_neck_likelihood',
       'facecam_pose_body_1_x', 'facecam_pose_body_1_y',
       'facecam_pose_body_1_likelihood', 'facecam_pose_body_2_x',
       'facecam_pose_body_2_y', 'facecam_pose_body_2_likelihood',
       'facecam_pose_body_3_x', 'facecam_pose_body_3_y',
       'facecam_pose_body_3_likelihood', 'facecam_pose_ephys_timestamp',
       'facecam_pose_pc_timestamp', 'facecam_pose_nose_neck_length',
       'facecam_pose_neck_body1_length', 'facecam_pose_nose_neck_body1_angle',
       'facecam_pose_body1_body2_body3_angle',
       'facecam_pose_nose_neck_body1_angle_likelihood',
       'facecam_pose_body1_body2_body3_angle_likelihood', 'lick_count',
       'reward-removed_count', 'reward-sound_count', 'reward-valve-open_count',
       'posbin_to_pc_timestamp', 'posbin_to_ephys_timestamp', 'trial_id',
       'track_zone', 'track_zone_int', 'lick_detected',
       'reward-removed_detected', 'reward-sound_detected',
       'reward-valve-open_detected', 'trial_outcome', 'cue',
       'both_R1_R2_rewarded', 'choice_R1', 'choice_R2',
       'posbin_from_ephys_timestamp', 'posbin_from_pc_timestamp',
       'nframes_in_posbin', 'flip_Cue1R1_Cue2R2'],
      dtype='object')

In [9]:
t0_events = analytics.get_analytics('TrialWiseT0Events40ms', session_names=session_names)
t0_events

2026-02-28 16:40:51,841|DEBUG|53778|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-28 16:40:52,126|DEBUG|53778|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-28 16:40:52,127|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:52,139|INFO|53778|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-28 16:40:52,142|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-28 16:40:52,318|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-28 16:40:52,358|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-28 16:40:52,401|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-28 16:40:52,460|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-28 16:40:52,473|INFO|53778|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-28 16:40:52,474|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-28 16:40:52,511|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-28 16:40:52,559|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-28 16:40:52,578|INFO|53778|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-28 16:40:52,579|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:52,645|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-28 16:40:52,693|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:52,740|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:52,793|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-28 16:40:52,840|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-28 16:40:52,884|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:52,942|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-28 16:40:52,987|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:53,036|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:53,093|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:53,133|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:53,180|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:40:53,235|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-28 16:40:53,285|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-28 16:40:53,337|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-28 16:40:53,379|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-28 16:40:53,388|INFO|53778|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-28 16:40:53,389|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-28 16:40:53,436|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-28 16:40:53,448|INFO|53778|analytics|get_analytics
	Analytic `TrialWiseT0Events40ms` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-28 16:40:53,449|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-28 16:40:53,508|DEBUG|53778|analytics|get_analytics
	Processing TrialWiseT0Events40ms, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-28 16:40:53,601|INFO|53778|analytics|get_analytics
	Returning TrialWiseT0Events40ms for 25 sessions.
2026-02-28 16:40:53,617|DEBUG|53778|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              1.0  1.0            0.0
                                       1              1.0  1.0            0.0
                                       2              1.0  1.0            0.0
                                       3              1.0  1.0            0.0
                                       4              1.0  1.0            0.0
...                                                   ...  ...            ...
                      2025-01-27_13-39 1104         152.0  2.0            1.0
                                       1105         152.0  2.0            1.0
                                       1106         152.0  2.0            1.0
                                       1107         152.0  2.0            1.0
                                       1108         152.0  2.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0        0.0
                                       1               0.0        0.0
                                       2               0.0        0.0
                                       3               0.0        0.0
                                       4               0.0        0.0
...                                                    ...        ...
                      2025-01-27_13-39 1104            0.0        1.0
                                       1105            0.0        1.0
                                       1106            0.0        1.0
                                       1107            0.0        1.0
                                       1108            0.0        1.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                      2025-01-27_13-39 1104           cueZone_exit
                                       1105      enter_reward1Zone
                                       1106      enter_reward2Zone
                                       1107       exit_reward1Zone
                                       1108       exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            4600000 -119.732067
                                       1            5400000  -79.536247
                                       2            6760000   24.898020
                                       3            7080000   51.438920
                                       4            9480000  170.376450
...                                                     ...         ...
                      2025-01-27_13-39 1104      4396000000   25.843260
                                       1105      4396480000   49.770475
                                       1106      4398880000  170.561500
                                       1107      4397720000  109.711900
                                       1108      4401200000  229.449700

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                      2025-01-27_13-39 1104             25.0
                                       1105             50.0
                                       1106            170.0
                                       1107            110.0
                                       1108            230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-14_16-40 0         (4400000.0, 4600000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                      2025-01-27_13-39 1104                         NaN  ...
                                       1105                         NaN  ...
                                       1106                         NaN  ...
                                       1107                         NaN  ...
                                       1108                         NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4              (9080000.0, 10680000.0]
...                                                                       ...
                      2025-01-27_13-39 1104                               NaN
                                       1105                               NaN
                                       1106      (4398480000.0, 4400080000.0]
                                       1107                               NaN
                                       1108                               NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                      2025-01-27_13-39 1104                                                   None
                                       1105                                                   None
                                       1106                                                   None
                                       1107                                                   None
                                       1108                                                   None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 1104                               NaN
                                       1105                               NaN
                                       1106                               NaN
                                       1107      (4397320000.0, 4398920000.0]
                                       1108                               NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                         None
                                       1                         None
                                       2                         None

                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              1.0  1.0            0.0
                                       1              1.0  1.0            0.0
                                       2              1.0  1.0            0.0
                                       3              1.0  1.0            0.0
                                       4              1.0  1.0            0.0
...                                                   ...  ...            ...
                      2025-01-27_13-39 1104         152.0  2.0            1.0
                                       1105         152.0  2.0            1.0
                                       1106         152.0  2.0            1.0
                                       1107         152.0  2.0            1.0
                                       1108         152.0  2.0            1.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0        0.0
                                       1               0.0        0.0
                                       2               0.0        0.0
                                       3               0.0        0.0
                                       4               0.0        0.0
...                                                    ...        ...
                      2025-01-27_13-39 1104            0.0        1.0
                                       1105            0.0        1.0
                                       1106            0.0        1.0
                                       1107            0.0        1.0
                                       1108            0.0        1.0

                                                     t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0           cueZone_visible
                                       1             cueZone_entry
                                       2              cueZone_exit
                                       3         enter_reward1Zone
                                       4         enter_reward2Zone
...                                                            ...
                      2025-01-27_13-39 1104           cueZone_exit
                                       1105      enter_reward1Zone
                                       1106      enter_reward2Zone
                                       1107       exit_reward1Zone
                                       1108       exit_reward2Zone

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            4600000 -119.732067
                                       1            5400000  -79.536247
                                       2            6760000   24.898020
                                       3            7080000   51.438920
                                       4            9480000  170.376450
...                                                     ...         ...
                      2025-01-27_13-39 1104      4396000000   25.843260
                                       1105      4396480000   49.770475
                                       1106      4398880000  170.561500
                                       1107      4397720000  109.711900
                                       1108      4401200000  229.449700

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              -120.0
                                       1               -80.0
                                       2                25.0
                                       3                50.0
                                       4               170.0
...                                                      ...
                      2025-01-27_13-39 1104             25.0
                                       1105             50.0
                                       1106            170.0
                                       1107            110.0
                                       1108            230.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-14_16-40 0         (4400000.0, 4600000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...
...                                                                 ...  ...
                      2025-01-27_13-39 1104                         NaN  ...
                                       1105                         NaN  ...
                                       1106                         NaN  ...
                                       1107                         NaN  ...
                                       1108                         NaN  ...

                                                            R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4              (9080000.0, 10680000.0]
...                                                                       ...
                      2025-01-27_13-39 1104                               NaN
                                       1105                               NaN
                                       1106      (4398480000.0, 4400080000.0]
                                       1107                               NaN
                                       1108                               NaN

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...
...                                                                                            ...
                      2025-01-27_13-39 1104                                                   None
                                       1105                                                   None
                                       1106                                                   None
                                       1107                                                   None
                                       1108                                                   None

                                                             R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 1104                               NaN
                                       1105                               NaN
                                       1106                               NaN
                                       1107      (4397320000.0, 4398920000.0]
                                       1108                               NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                      2025-01-27_13-39 1104                      None
                                       1105                      None
                                       1106                      None
                                       1107                      None
                                       1108                      None

                                                             R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                  NaN
                                       1                                  NaN
                                       2                                  NaN
                                       3                                  NaN
                                       4                                  NaN
...                                                                       ...
                      2025-01-27_13-39 1104                               NaN
                                       1105                               NaN
                                       1106                               NaN
                                       1107                               NaN
                                       1108      (4400800000.0, 4402400000.0]

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None
...                                                               ...
                      2025-01-27_13-39 1104                      None
                                       1105                      None
                                       1106                      None
                                       1107                      None
                                       1108                      None

                                                reward1_sound_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                      2025-01-27_13-39 1104                        NaN
                                       1105                        NaN
                                       1106                        NaN
                                       1107                        NaN
                                       1108                        NaN

                                                reward1_sound_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                               None
                                       1                               None
                                       2                               None
                                       3                               None
                                       4                               None
...                                                                     ...
                      2025-01-27_13-39 1104                            None
                                       1105                            None
                                       1106                            None
                                       1107                            None
                                       1108                            None

                                                reward2_sound_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                      2025-01-27_13-39 1104                        NaN
                                       1105                        NaN
                                       1106                        NaN
                                       1107                        NaN
                                       1108                        NaN

                                                reward2_sound_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                               None
                                       1                               None
                                       2                               None
                                       3                               None
                                       4                               None
...                                                                     ...
                      2025-01-27_13-39 1104                            None
                                       1105                            None
                                       1106                            None
                                       1107                            None
                                       1108                            None

[19722 rows x 29 columns]

In [6]:
behav['reward-valve-open_detected']

paradigm_id  animal_id  session_id        entry_id
1100         6          2024-11-14_15-01  0           0.0
                                          1           0.0
                                          2           0.0
                                          3           0.0
                                          4           0.0
                                                     ...
                        2025-01-27_13-39  65051       0.0
                                          65052       0.0
                                          65053       0.0
                                          65054       0.0
                                          65055       0.0
Name: reward-valve-open_detected, Length: 1442177, dtype: float64

In [7]:
behavior = analytics.get_analytics(analytic="Behavior40msAligned", session_names=session_names)
behavior

2026-02-28 15:59:45,497|DEBUG|53778|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-28 15:59:45,720|DEBUG|53778|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-28 15:59:45,721|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:45,725|INFO|53778|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-28 15:59:45,726|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-28 15:59:46,221|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-28 15:59:47,003|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-28 15:59:47,484|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-28 15:59:48,066|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-28 15:59:48,078|INFO|53778|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-28 15:59:48,078|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-28 15:59:48,477|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-28 15:59:48,992|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-28 15:59:49,012|INFO|53778|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-28 15:59:49,012|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:49,622|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-28 15:59:50,191|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:50,818|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:51,378|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-28 15:59:51,921|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-28 15:59:52,486|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:53,061|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-28 15:59:53,545|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:54,143|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:54,716|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:55,331|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:55,960|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-28 15:59:56,584|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-28 15:59:57,418|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-28 15:59:58,207|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-28 15:59:59,025|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-28 15:59:59,026|INFO|53778|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-28 15:59:59,026|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-28 16:00:00,230|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-28 16:00:00,231|INFO|53778|analytics|get_analytics
	Analytic `Behavior40msAligned` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-28 16:00:00,231|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-28 16:00:01,349|DEBUG|53778|analytics|get_analytics
	Processing Behavior40msAligned, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-28 16:00:02,849|INFO|53778|analytics|get_analytics
	Returning Behavior40msAligned for 25 sessions.
2026-02-28 16:00:02,985|DEBUG|53778|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 frame_raw_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                      2025-01-27_13-39 110898                      NaN
                                       110899                      NaN
                                       110900                      NaN
                                       110901                      NaN
                                       110902                      NaN

                                                 frame_raw_abs_acc_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                   NaN
                                       1                                   NaN
                                       2                                   NaN
                                       3                                   NaN
                                       4                                   NaN
...                                                                        ...
                      2025-01-27_13-39 110898                              NaN
                                       110899                              NaN
                                       110900                              NaN
                                       110901                              NaN
                                       110902                              NaN

                                                 frame_YawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                      2025-01-27_13-39 110898                                       NaN
                                       110899                                       NaN
                                       110900                                       NaN
                                       110901                                       NaN
                                       110902                                       NaN

                                                 frame_YawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                      2025-01-27_13-39 110898                                       NaN
                                       110899                                       NaN
                                       110900                                       NaN
                                       110901                                       NaN
                                       110902                                       NaN

                                                 frame_RawYawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                      2025-01-27_13-39 110898                                          NaN
                                       110899                                          NaN
                                       110900                                          NaN
                                       110901                                          NaN
                                       110902                                          NaN

                                                 frame_RawYawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                      2025-01-27_13-39 110898                                          NaN
                                       110899                                          NaN
                                       110900                                          NaN
                                       110901                                          NaN
                                       110902                                          NaN

                                                 frame_forward_prop  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                        NaN
                                       1                        NaN
                                       2                        NaN
                                       3                        NaN
                                       4                        NaN
...                                                             ...
                      2025-01-27_13-39 110898                   NaN
                                       110899                   NaN
                                       110900                   NaN
                                       110901                   NaN
                                       110902                   NaN

                                                 forward_vs_rotation_corr  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                              NaN
                                       1                              NaN
                                       2                              NaN
                                       3                              NaN
                                       4                              NaN
...                                                                   ...
                      2025-01-27_13-39 110898                         NaN
                                       110899                         NaN
                                       110900                         NaN
                                       110901                         NaN
                                       110902                         NaN

                                                 frame_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    NaN
                                       1                    NaN
                                       2                    NaN
                                       3                    NaN
                                       4                    NaN
...                                                         ...
                      2025-01-27_13-39 110898               NaN
                                       110899               NaN
                                       110900               NaN
                                       110901               NaN
                                       110902               NaN


                                                 frame_raw_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                      2025-01-27_13-39 110898                      NaN
                                       110899                      NaN
                                       110900                      NaN
                                       110901                      NaN
                                       110902                      NaN

                                                 frame_raw_abs_acc_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                   NaN
                                       1                                   NaN
                                       2                                   NaN
                                       3                                   NaN
                                       4                                   NaN
...                                                                        ...
                      2025-01-27_13-39 110898                              NaN
                                       110899                              NaN
                                       110900                              NaN
                                       110901                              NaN
                                       110902                              NaN

                                                 frame_YawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                      2025-01-27_13-39 110898                                       NaN
                                       110899                                       NaN
                                       110900                                       NaN
                                       110901                                       NaN
                                       110902                                       NaN

                                                 frame_YawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                            NaN
                                       1                                            NaN
                                       2                                            NaN
                                       3                                            NaN
                                       4                                            NaN
...                                                                                 ...
                      2025-01-27_13-39 110898                                       NaN
                                       110899                                       NaN
                                       110900                                       NaN
                                       110901                                       NaN
                                       110902                                       NaN

                                                 frame_RawYawPitch_abs_vel_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                      2025-01-27_13-39 110898                                          NaN
                                       110899                                          NaN
                                       110900                                          NaN
                                       110901                                          NaN
                                       110902                                          NaN

                                                 frame_RawYawPitch_abs_acc_sum_500msMedian  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                               NaN
                                       1                                               NaN
                                       2                                               NaN
                                       3                                               NaN
                                       4                                               NaN
...                                                                                    ...
                      2025-01-27_13-39 110898                                          NaN
                                       110899                                          NaN
                                       110900                                          NaN
                                       110901                                          NaN
                                       110902                                          NaN

                                                 frame_forward_prop  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                        NaN
                                       1                        NaN
                                       2                        NaN
                                       3                        NaN
                                       4                        NaN
...                                                             ...
                      2025-01-27_13-39 110898                   NaN
                                       110899                   NaN
                                       110900                   NaN
                                       110901                   NaN
                                       110902                   NaN

                                                 forward_vs_rotation_corr  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                              NaN
                                       1                              NaN
                                       2                              NaN
                                       3                              NaN
                                       4                              NaN
...                                                                   ...
                      2025-01-27_13-39 110898                         NaN
                                       110899                         NaN
                                       110900                         NaN
                                       110901                         NaN
                                       110902                         NaN

                                                 frame_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    NaN
                                       1                    NaN
                                       2                    NaN
                                       3                    NaN
                                       4                    NaN
...                                                         ...
                      2025-01-27_13-39 110898               NaN
                                       110899               NaN
                                       110900               NaN
                                       110901               NaN
                                       110902               NaN

                                                 frame_head_angle_vel  ...  \
paradigm_id animal_id session_id       entry_id                        ...
1100        6         2024-11-14_16-40 0                          NaN  ...
                                       1                          NaN  ...
                                       2                          NaN  ...
                                       3                          NaN  ...
                                       4                          NaN  ...
...                                                               ...  ...
                      2025-01-27_13-39 110898                     NaN  ...
                                       110899                     NaN  ...
                                       110900                     NaN  ...
                                       110901                     NaN  ...
                                       110902                     NaN  ...

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               NaN        NaN
                                       1               NaN        NaN
                                       2               NaN        NaN
                                       3               NaN        NaN
                                       4               NaN        NaN
...                                                    ...        ...
                      2025-01-27_13-39 110898          NaN        NaN
                                       110899          NaN        NaN
                                       110900          NaN        NaN
                                       110901          NaN        NaN
                                       110902          NaN        NaN

                                                 lick_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                   NaN
                                       1                   NaN
                                       2                   NaN
                                       3                   NaN
                                       4                   NaN
...                                                        ...
                      2025-01-27_13-39 110898              NaN
                                       110899              NaN
                                       110900              NaN
                                       110901              NaN
                                       110902              NaN

                                                 reward-sound_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                           NaN
                                       1                           NaN
                                       2                           NaN
                                       3                           NaN
                                       4                           NaN
...                                                                ...
                      2025-01-27_13-39 110898                      NaN
                                       110899                      NaN
                                       110900                      NaN
                                       110901                      NaN
                                       110902                      NaN

                                                 reward-valve-open_detected  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN
...                                                                     ...
                      2025-01-27_13-39 110898                           NaN
                                       110899                           NaN
                                       110900                           NaN
                                       110901                           NaN
                                       110902                           NaN

                                                 track_zone  track_zone_int  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                NaN             NaN
                                       1                NaN             NaN
                                       2                NaN             NaN
                                       3                NaN             NaN
                                       4                NaN             NaN
...                                                     ...             ...
                      2025-01-27_13-39 110898           NaN             NaN
                                       110899           NaN             NaN
                                       110900           NaN             NaN
                                       110901           NaN             NaN
                                       110902           NaN             NaN

                                                 cue_visible  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                 NaN
                                       1                 NaN
                                       2                 NaN
                                       3                 NaN
                                       4                 NaN
...                                                      ...
                      2025-01-27_13-39 110898            NaN
                                       110899            NaN
                                       110900            NaN
                                       110901            NaN
                                       110902            NaN

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                            0
                                       1                        40000
                                       2                        80000
                                       3                       120000
                                       4                       160000
...                                                               ...
                      2025-01-27_13-39 110898              4435920000
                                       110899              4435960000
                                       110900              4436000000
                                       110901              4436040000
                                       110902              4436080000

                                                 to_ephys_timestamp
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      40000
                                       1                      80000
                                       2                     120000
                                       3                     160000
                                       4                     200000
...                                                             ...
                      2025-01-27_13-39 110898            4435960000
                                       110899            4436000000
                                       110900            4436040000
                                       110901            4436080000
                                       110902            4436120000

[1272389 rows x 27 columns]

In [ ]:
behavior.keys()

Index(['frame_raw_500msMedian', 'frame_raw_abs_acc_500msMedian',
       'frame_YawPitch_abs_vel_sum_500msMedian',
       'frame_YawPitch_abs_acc_sum_500msMedian',
       'frame_RawYawPitch_abs_vel_sum_500msMedian',
       'frame_RawYawPitch_abs_acc_sum_500msMedian', 'frame_forward_prop',
       'forward_vs_rotation_corr', 'frame_position',
       'facecam_pose_nose_neck_body1_angle_velocity',
       'facecam_pose_nose_neck_body1_angle',
       'facecam_pose_nose_neck_body1_angle_likelihood',
       'frame_ephys_timestamp', 'frame_pc_timestamp', 'trial_id', 'cue',
       'trial_outcome', 'choice_R1', 'choice_R2', 'lick_detected',
       'reward-sound_detected', 'reward-valve-open_detected', 'track_zone',
       'from_ephys_timestamp', 'to_ephys_timestamp'],
      dtype='object')

In [ ]:
reward_timings = behavior[behavior['reward-valve-open_detected'] == True]
reward_timings #['trial_id'].min()

1.0

In [ ]:
# display(t0_ens.head())
t0_events.head()

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      4400000
                                       1                      4440000
                                       2                      4480000
                                       3                      4520000
                                       4                      4560000

                                                 to_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    4440000
                                       1                    4480000
                                       2                    4520000
                                       3                    4560000
                                       4                    4600000

                                                 Assembly001  Assembly002  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.044591    -0.079732
                                       1            0.353522    -0.208656
                                       2           -0.090020    -0.381483
                                       3           -0.082682    -0.003392
                                       4            0.169519    -0.213003

                                                 Assembly003  Assembly004  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.117157    -0.100619
                                       1           -0.050525    -0.098752
                                       2            0.185447     1.103287
                                       3            0.093962    -0.152654
                                       4           -0.009496    -0.107002

                                                 Assembly005  Assembly006  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.049611    -0.245620
                                       1            0.562233     0.299666
                                       2           -1.082371     1.418429
                                       3           -0.208707     0.906473
                                       4           -0.100514    -0.125251

                                                 Assembly007  Assembly008  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            1.360649    -0.219548
                                       1           -0.155457    -0.102385
                                       2           -0.112464    -0.994913
                                       3           -0.094875    -0.003057
                                       4           -0.154239     0.000961

                                                 ...  trial_id  cue  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 0         ...       1.0  1.0
                                       1         ...       1.0  1.0
                                       2         ...       1.0  1.0
                                       3         ...       1.0  1.0
                                       4         ...       1.0  1.0

                                                 trial_outcome  choice_R1  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                   0.0        0.0
                                       1                   0.0        0.0
                                       2                   0.0        0.0
                                       3                   0.0        0.0
                                       4                   0.0        0.0

                                                 choice_R2    t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0  cueZone_visible
                                       1               0.0  cueZone_visible
                                       2               0.0  cueZone_visible
                                       3               0.0  cueZone_visible
                                       4               0.0  cueZone_visible

                                                      t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0         4600000 -119.732067
                                       1         4600000 -119.732067
                                       2         4600000 -119.732067
                                       3         4600000 -119.732067
                                       4         4600000 -119.732067

                                                 x_alignment     interval_name
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              -120.0  pre_cue_interval
                                       1              -120.0  pre_cue_interval
                                       2              -120.0  pre_cue_interval
                                       3              -120.0  pre_cue_interval
                                       4              -120.0  pre_cue_interval

[5 rows x 35 columns]

                                                 trial_id  cue  trial_outcome  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              1.0  1.0            0.0
                                       1              1.0  1.0            0.0
                                       2              1.0  1.0            0.0
                                       3              1.0  1.0            0.0
                                       4              1.0  1.0            0.0

                                                 choice_R1  choice_R2  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0        0.0
                                       1               0.0        0.0
                                       2               0.0        0.0
                                       3               0.0        0.0
                                       4               0.0        0.0

                                                     t0_event_name       t0  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0           cueZone_visible  4600000
                                       1             cueZone_entry  5400000
                                       2              cueZone_exit  6760000
                                       3         enter_reward1Zone  7080000
                                       4         enter_reward2Zone  9480000

                                                 x_position  x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0        -119.732067       -120.0
                                       1         -79.536247        -80.0
                                       2          24.898020         25.0
                                       3          51.438920         50.0
                                       4         170.376450        170.0

                                                       pre_cue_interval  ...  \
paradigm_id animal_id session_id       entry_id                          ...
1100        6         2024-11-14_16-40 0         (4400000.0, 4600000.0]  ...
                                       1                            NaN  ...
                                       2                            NaN  ...
                                       3                            NaN  ...
                                       4                            NaN  ...

                                                       R2_entry_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                             NaN
                                       1                             NaN
                                       2                             NaN
                                       3                             NaN
                                       4         (9080000.0, 10680000.0]

                                                                            R2_entry_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                                      None
                                       1                                                      None
                                       2                                                      None
                                       3                                                      None
                                       4         [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1...

                                                R1_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                     NaN
                                       1                     NaN
                                       2                     NaN
                                       3                     NaN
                                       4                     NaN

                                                R1_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None

                                                R2_exit_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                     NaN
                                       1                     NaN
                                       2                     NaN
                                       3                     NaN
                                       4                     NaN

                                                R2_exit_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                         None
                                       1                         None
                                       2                         None
                                       3                         None
                                       4                         None

                                                reward1_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN

                                                reward1_valve_open_interval_bins  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None

                                                reward2_valve_open_interval  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                NaN
                                       1                                NaN
                                       2                                NaN
                                       3                                NaN
                                       4                                NaN

                                                reward2_valve_open_interval_bins
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                                    None
                                       1                                    None
                                       2                                    None
                                       3                                    None
                                       4                                    None

[5 rows x 29 columns]

In [ ]:
# t0_ens['interval_name'].unique()
# print (t0_ens['interval_name'].unique())
# print(t0_events['t0_event_name'].unique())

['pre_cue_interval' 'nextto_cue_interval' 'cue_entry_interval'
 'cue_exit_interval' 'R1_entry_interval' 'R2_entry_interval'
 'R1_exit_interval' 'R2_exit_interval']
['cueZone_visible' 'cueZone_entry' 'cueZone_exit' 'enter_reward1Zone'
 'enter_reward2Zone' 'exit_reward1Zone' 'exit_reward2Zone' 'reward1_sound'
 'reward2_sound']

In [11]:
t0_ens = analytics.get_analytics('EnsembleT0Projection', session_names=session_names,)
t0_ens

2026-02-28 16:49:48,428|DEBUG|53778|sessions_from_nas_parsing|sessionnames2fullfnames
	Inferring NAS paths for list of session names...
2026-02-28 16:49:48,750|DEBUG|53778|sessions_from_nas_parsing|sessionlist_fullfnames_from_args
	Paradigm_ids: None, animal_ids: None, session_ids: None, from_date: None, to_date: None
	Merging 30 sessions

2026-02-28 16:49:48,751|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-14_15-01') 2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_15-01_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:48,769|INFO|53778|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2024-11-14_15-01'), compute first, or check for typo
2026-02-28 16:49:48,769|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-14_16-40') 2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-14_16-40_rYL006_P1100_LinearTrackStop_21min
2026-02-28 16:49:49,359|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-15_15-48') 2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-15_15-48_rYL006_P1100_LinearTrackStop_35min
2026-02-28 16:49:50,074|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-20_17-46') 2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-20_17-46_rYL006_P1100_LinearTrackStop_22min
2026-02-28 16:49:50,477|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-21_17-22') 2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-21_17-22_rYL006_P1100_LinearTrackStop_25min
2026-02-28 16:49:50,918|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-22_16-01') 2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-22_16-01_rYL006_P1100_LinearTrackStop_24min
2026-02-28 16:49:50,956|INFO|53778|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2024-11-22_16-01'), compute first, or check for typo
2026-02-28 16:49:50,957|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-25_16-25') 2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-25_16-25_rYL006_P1100_LinearTrackStop_18min
2026-02-28 16:49:51,243|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-26_16-39') 2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-26_16-39_rYL006_P1100_LinearTrackStop_25min
2026-02-28 16:49:51,796|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-27_16-11') 2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-27_16-11_rYL006_P1100_LinearTrackStop_31min
2026-02-28 16:49:51,808|INFO|53778|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2024-11-27_16-11'), compute first, or check for typo
2026-02-28 16:49:51,808|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-11-28_17-41') 2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-11-28_17-41_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:52,560|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-02_16-09') 2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-02_16-09_rYL006_P1100_LinearTrackStop_28min
2026-02-28 16:49:53,145|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-03_16-23') 2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-03_16-23_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:53,873|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-04_18-06') 2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-04_18-06_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:54,597|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-06_16-49') 2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-06_16-49_rYL006_P1100_LinearTrackStop_25min
2026-02-28 16:49:55,187|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-09_17-45') 2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-09_17-45_rYL006_P1100_LinearTrackStop_26min
2026-02-28 16:49:55,699|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-10_17-20') 2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-10_17-20_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:56,329|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-12_16-13') 2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-12_16-13_rYL006_P1100_LinearTrackStop_26min
2026-02-28 16:49:56,873|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2024-12-13_17-10') 2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2024-12-13_17-10_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:57,518|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-14_18-08') 2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-14_18-08_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:57,991|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-15_17-18') 2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-15_17-18_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:58,538|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-16_17-47') 2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-16_17-47_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:59,309|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-17_16-55') 2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-17_16-55_rYL006_P1100_LinearTrackStop_30min
2026-02-28 16:49:59,869|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-23_16-48') 2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-23_16-48_rYL006_P1100_LinearTrackStop_42min
2026-02-28 16:50:00,571|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-24_12-24') 2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_12-24_rYL006_P1100_LinearTrackStop_41min
2026-02-28 16:50:01,429|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-24_19-37') 2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-24_19-37_rYL006_P1100_LinearTrackStop_40min
2026-02-28 16:50:02,160|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-25_10-55') 2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_10-55_rYL006_P1100_LinearTrackStop_60min
2026-02-28 16:50:02,179|INFO|53778|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2025-01-25_10-55'), compute first, or check for typo
2026-02-28 16:50:02,180|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-25_21-29') 2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-25_21-29_rYL006_P1100_LinearTrackStop_61min
2026-02-28 16:50:03,369|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-26_13-45') 2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_13-45_rYL006_P1100_LinearTrackStop_67min
2026-02-28 16:50:03,388|INFO|53778|analytics|get_analytics
	Analytic `EnsembleT0Projection` does not exist for (1100, 6, '2025-01-26_13-45'), compute first, or check for typo
2026-02-28 16:50:03,389|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-26_21-48') 2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-26_21-48_rYL006_P1100_LinearTrackStop_55min
2026-02-28 16:50:04,513|DEBUG|53778|analytics|get_analytics
	Processing EnsembleT0Projection, (1100, 6, '2025-01-27_13-39') 2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min.hdf5
/Volumes/large/BMI/VirtualReality/SpatialSequenceLearning/RUN_rYL006/rYL006_P1100/2025-01-27_13-39_rYL006_P1100_LinearTrackStop_73min
================================================================================

2026-02-28 16:50:05,677|INFO|53778|analytics|get_analytics
	Returning EnsembleT0Projection for 25 sessions.
2026-02-28 16:50:05,956|DEBUG|53778|analytics|get_analytics
	Paradigm_ids: [1100], Animal_ids: [6]
                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      4400000
                                       1                      4440000
                                       2                      4480000
                                       3                      4520000
                                       4                      4560000
...                                                               ...
                      2025-01-27_13-39 39795               4275440000
                                       39796               4275480000
                                       39797               4275520000
                                       39798               4275560000
                                       39799               4275600000

                                                 to_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    4440000
                                       1                    4480000
                                       2                    4520000
                                       3                    4560000
                                       4                    4600000
...                                                             ...
                      2025-01-27_13-39 39795             4275480000
                                       39796             4275520000
                                       39797             4275560000
                                       39798             4275600000
                                       39799             4275640000

                                                 Assembly001  Assembly002  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.044591    -0.079732
                                       1            0.353522    -0.208656
                                       2           -0.090020    -0.381483
                                       3           -0.082682    -0.003392
                                       4            0.169519    -0.213003
...                                                      ...          ...
                      2025-01-27_13-39 39795       -0.121557    -0.456305
                                       39796       -0.166517    -0.094205
                                       39797       -0.062079    -0.142495
                                       39798       -0.032098     0.095632
                                       39799        0.065874     0.164919

                                                 Assembly003  Assembly004  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.117157    -0.100619
                                       1           -0.050525    -0.098752
                                       2            0.185447     1.103287
                                       3            0.093962    -0.152654
                                       4           -0.009496    -0.107002
...                                                      ...          ...
                      2025-01-27_13-39 39795        1.920625    -1.375872
                                       39796        0.436531    -0.603980
                                       39797       -0.051984    -0.121114
                                       39798       -0.241508     0.670083
                                       39799       -0.220040     0.440637

                                                 Assembly005  Assembly006  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.049611    -0.245620
                                       1            0.562233     0.299666
                                       2           -1.082371     1.418429
                                       3           -0.208707     0.906473
                                       4           -0.100514    -0.125251
...                                                      ...          ...
                      2025-01-27_13-39 39795        0.081050     4.388406
                                       39796       -1.419928     0.242145
                                       39797        0.103459     0.065734
                                       39798        0.083675    -0.297539
                                       39799       -0.149096     0.124804

                                                 Assembly007  Assembly008  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            1.360649    -0.219548
                                       1           -0.155457    -0.102385
                                       2           -0.112464    -0.994913
                                       3           -0.094875    -0.003057
                                       4           -0.154239     0.000961
...                                                      ...          ...
                      2025-01-27_13-39 39795       -0.109789     1.071399
                                       39796       -0.768531     0.385439
                                       39797       -0.171436    -0.100902
                                       39798       -0.318186    -0.117073
                                       39799       -0.145230    -0.007504

                                                 ...  trial_id  cue  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 0         ...       1.0  1.0
                                       1         ...       1.0  1.0
                                       2         ...       1.0  1.0
                                       3         ...       1.0  1.0
                                       4         ...       1.0  1.0
...                                              ...       ...  ...
                      2025-01-27_13-39 39795     ...     148.0  2.0
                                       39796     ...     148.0  2.0
                                       39797     ...     148.0  2.0
                                       39798     ...     148.0  2.0
                                       39799     ...     148.0  2.0

                                                 trial_outcome  choice_R1  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                   0.0        0.0
                                       1                   0.0        0.0
                                       2                   0.0        0.0
                                       3                   0.0        0.0
                                       4                   0.0        0.0
...                                                        ...        ...
                      2025-01-27_13-39 39795               1.0        0.0
                                       39796               1.0        0.0
                                       39797               1.0        0.0
                                       39798               1.0        0.0
                                       39799               1.0        0.0

                                                 choice_R2    t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0  cueZone_visible
                                       1               0.0  cueZone_visible
                                       2               0.0  cueZone_visible
                                       3               0.0  cueZone_visible
                                       4               0.0  cueZone_visible
...                                                    ...              ...
                      2025-01-27_13-39 39795           1.0    reward2_sound
                                       39796           1.0    reward2_sound
                                       39797           1.0    reward2_sound
                                       39798           1.0    reward2_sound
                                       39799           1.0    reward2_sound

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            4600000 -119.732067
                                       1            4600000 -119.732067
                                       2            4600000 -119.732067
                                       3            4600000 -119.732067
                                       4            4600000 -119.732067
...                                                     ...         ...
                      2025-01-27_13-39 39795     4274080000  173.798950
                                       39796     4274080000  173.798950

                                                 from_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                      4400000
                                       1                      4440000
                                       2                      4480000
                                       3                      4520000
                                       4                      4560000
...                                                               ...
                      2025-01-27_13-39 39795               4275440000
                                       39796               4275480000
                                       39797               4275520000
                                       39798               4275560000
                                       39799               4275600000

                                                 to_ephys_timestamp  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                    4440000
                                       1                    4480000
                                       2                    4520000
                                       3                    4560000
                                       4                    4600000
...                                                             ...
                      2025-01-27_13-39 39795             4275480000
                                       39796             4275520000
                                       39797             4275560000
                                       39798             4275600000
                                       39799             4275640000

                                                 Assembly001  Assembly002  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.044591    -0.079732
                                       1            0.353522    -0.208656
                                       2           -0.090020    -0.381483
                                       3           -0.082682    -0.003392
                                       4            0.169519    -0.213003
...                                                      ...          ...
                      2025-01-27_13-39 39795       -0.121557    -0.456305
                                       39796       -0.166517    -0.094205
                                       39797       -0.062079    -0.142495
                                       39798       -0.032098     0.095632
                                       39799        0.065874     0.164919

                                                 Assembly003  Assembly004  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.117157    -0.100619
                                       1           -0.050525    -0.098752
                                       2            0.185447     1.103287
                                       3            0.093962    -0.152654
                                       4           -0.009496    -0.107002
...                                                      ...          ...
                      2025-01-27_13-39 39795        1.920625    -1.375872
                                       39796        0.436531    -0.603980
                                       39797       -0.051984    -0.121114
                                       39798       -0.241508     0.670083
                                       39799       -0.220040     0.440637

                                                 Assembly005  Assembly006  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            0.049611    -0.245620
                                       1            0.562233     0.299666
                                       2           -1.082371     1.418429
                                       3           -0.208707     0.906473
                                       4           -0.100514    -0.125251
...                                                      ...          ...
                      2025-01-27_13-39 39795        0.081050     4.388406
                                       39796       -1.419928     0.242145
                                       39797        0.103459     0.065734
                                       39798        0.083675    -0.297539
                                       39799       -0.149096     0.124804

                                                 Assembly007  Assembly008  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            1.360649    -0.219548
                                       1           -0.155457    -0.102385
                                       2           -0.112464    -0.994913
                                       3           -0.094875    -0.003057
                                       4           -0.154239     0.000961
...                                                      ...          ...
                      2025-01-27_13-39 39795       -0.109789     1.071399
                                       39796       -0.768531     0.385439
                                       39797       -0.171436    -0.100902
                                       39798       -0.318186    -0.117073
                                       39799       -0.145230    -0.007504

                                                 ...  trial_id  cue  \
paradigm_id animal_id session_id       entry_id  ...
1100        6         2024-11-14_16-40 0         ...       1.0  1.0
                                       1         ...       1.0  1.0
                                       2         ...       1.0  1.0
                                       3         ...       1.0  1.0
                                       4         ...       1.0  1.0
...                                              ...       ...  ...
                      2025-01-27_13-39 39795     ...     148.0  2.0
                                       39796     ...     148.0  2.0
                                       39797     ...     148.0  2.0
                                       39798     ...     148.0  2.0
                                       39799     ...     148.0  2.0

                                                 trial_outcome  choice_R1  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0                   0.0        0.0
                                       1                   0.0        0.0
                                       2                   0.0        0.0
                                       3                   0.0        0.0
                                       4                   0.0        0.0
...                                                        ...        ...
                      2025-01-27_13-39 39795               1.0        0.0
                                       39796               1.0        0.0
                                       39797               1.0        0.0
                                       39798               1.0        0.0
                                       39799               1.0        0.0

                                                 choice_R2    t0_event_name  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               0.0  cueZone_visible
                                       1               0.0  cueZone_visible
                                       2               0.0  cueZone_visible
                                       3               0.0  cueZone_visible
                                       4               0.0  cueZone_visible
...                                                    ...              ...
                      2025-01-27_13-39 39795           1.0    reward2_sound
                                       39796           1.0    reward2_sound
                                       39797           1.0    reward2_sound
                                       39798           1.0    reward2_sound
                                       39799           1.0    reward2_sound

                                                         t0  x_position  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0            4600000 -119.732067
                                       1            4600000 -119.732067
                                       2            4600000 -119.732067
                                       3            4600000 -119.732067
                                       4            4600000 -119.732067
...                                                     ...         ...
                      2025-01-27_13-39 39795     4274080000  173.798950
                                       39796     4274080000  173.798950
                                       39797     4274080000  173.798950
                                       39798     4274080000  173.798950
                                       39799     4274080000  173.798950

                                                 x_alignment  \
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0              -120.0
                                       1              -120.0
                                       2              -120.0
                                       3              -120.0
                                       4              -120.0
...                                                      ...
                      2025-01-27_13-39 39795             NaN
                                       39796             NaN
                                       39797             NaN
                                       39798             NaN
                                       39799             NaN

                                                          interval_name
paradigm_id animal_id session_id       entry_id
1100        6         2024-11-14_16-40 0               pre_cue_interval
                                       1               pre_cue_interval
                                       2               pre_cue_interval
                                       3               pre_cue_interval
                                       4               pre_cue_interval
...                                                                 ...
                      2025-01-27_13-39 39795     reward2_sound_interval
                                       39796     reward2_sound_interval
                                       39797     reward2_sound_interval
                                       39798     reward2_sound_interval
                                       39799     reward2_sound_interval

[707400 rows x 35 columns]

In [ ]:
t0_events['']
#t0_ens['interval_name'].unique()

array(['pre_cue_interval', 'nextto_cue_interval', 'cue_entry_interval',
       'cue_exit_interval', 'R1_entry_interval', 'R2_entry_interval',
       'R1_exit_interval', 'R2_exit_interval'], dtype=object)